// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: auth/auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Old or new contact status
type SendOTPToContactRequest_ContactStatus int32

const (
	SendOTPToContactRequest_OLD SendOTPToContactRequest_ContactStatus = 0 // Send OTP to old contact
	SendOTPToContactRequest_NEW SendOTPToContactRequest_ContactStatus = 1 // Send OTP to new contact
)

// Enum value maps for SendOTPToContactRequest_ContactStatus.
var (
	SendOTPToContactRequest_ContactStatus_name = map[int32]string{
		0: "OLD",
		1: "NEW",
	}
	SendOTPToContactRequest_ContactStatus_value = map[string]int32{
		"OLD": 0,
		"NEW": 1,
	}
)

func (x SendOTPToContactRequest_ContactStatus) Enum() *SendOTPToContactRequest_ContactStatus {
	p := new(SendOTPToContactRequest_ContactStatus)
	*p = x
	return p
}

func (x SendOTPToContactRequest_ContactStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendOTPToContactRequest_ContactStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_auth_proto_enumTypes[0].Descriptor()
}

func (SendOTPToContactRequest_ContactStatus) Type() protoreflect.EnumType {
	return &file_auth_auth_proto_enumTypes[0]
}

func (x SendOTPToContactRequest_ContactStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SendOTPToContactRequest_ContactStatus.Descriptor instead.
func (SendOTPToContactRequest_ContactStatus) EnumDescriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{11, 0}
}

// Purpose of OTP (e.g., "update_contact", "verify_contact")
type SendOTPToContactRequest_OTPPurpose int32

const (
	SendOTPToContactRequest_UPDATE_CONTACT SendOTPToContactRequest_OTPPurpose = 0 // OTP for updating contact
	SendOTPToContactRequest_VERIFY_CONTACT SendOTPToContactRequest_OTPPurpose = 1 // OTP for verifying contact
)

// Enum value maps for SendOTPToContactRequest_OTPPurpose.
var (
	SendOTPToContactRequest_OTPPurpose_name = map[int32]string{
		0: "UPDATE_CONTACT",
		1: "VERIFY_CONTACT",
	}
	SendOTPToContactRequest_OTPPurpose_value = map[string]int32{
		"UPDATE_CONTACT": 0,
		"VERIFY_CONTACT": 1,
	}
)

func (x SendOTPToContactRequest_OTPPurpose) Enum() *SendOTPToContactRequest_OTPPurpose {
	p := new(SendOTPToContactRequest_OTPPurpose)
	*p = x
	return p
}

func (x SendOTPToContactRequest_OTPPurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendOTPToContactRequest_OTPPurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_auth_proto_enumTypes[1].Descriptor()
}

func (SendOTPToContactRequest_OTPPurpose) Type() protoreflect.EnumType {
	return &file_auth_auth_proto_enumTypes[1]
}

func (x SendOTPToContactRequest_OTPPurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SendOTPToContactRequest_OTPPurpose.Descriptor instead.
func (SendOTPToContactRequest_OTPPurpose) EnumDescriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{11, 1}
}

// User represents a user from the auth service
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Entity ID (linked entity in Mithiril)
	EntityId string `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	// Email address
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// Phone number
	PhoneNumber string `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// User role
	Role string `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	// Permissions list
	Permissions []string `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// User status
	Status string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	// Jurisdiction (e.g., "KE", "UG", "TZ")
	Jurisdiction string `protobuf:"bytes,8,opt,name=jurisdiction,proto3" json:"jurisdiction,omitempty"`
	// Created timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Cloud9 tag (e.g., "$username") — canonical tag from hama's users table
	Cloud9Tag     string `protobuf:"bytes,10,opt,name=cloud9_tag,json=cloud9Tag,proto3" json:"cloud9_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *User) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *User) GetJurisdiction() string {
	if x != nil {
		return x.Jurisdiction
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetCloud9Tag() string {
	if x != nil {
		return x.Cloud9Tag
	}
	return ""
}

// ValidateTokenRequest for token validation
type ValidateTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JWT token to validate
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// ValidateTokenResponse
type ValidateTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the token is valid
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// User details (if valid)
	User *User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// Error message (if invalid)
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ValidateTokenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetUserRequest
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID to retrieve
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetUserResponse
type GetUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User details
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// GetUserByEntityIDRequest
type GetUserByEntityIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entity ID to look up (matches entity_id stored on the hama user record)
	EntityId      string `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByEntityIDRequest) Reset() {
	*x = GetUserByEntityIDRequest{}
	mi := &file_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByEntityIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByEntityIDRequest) ProtoMessage() {}

func (x *GetUserByEntityIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByEntityIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByEntityIDRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserByEntityIDRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

// GetUserByEntityIDResponse
type GetUserByEntityIDResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User details
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByEntityIDResponse) Reset() {
	*x = GetUserByEntityIDResponse{}
	mi := &file_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByEntityIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByEntityIDResponse) ProtoMessage() {}

func (x *GetUserByEntityIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByEntityIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserByEntityIDResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserByEntityIDResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// CheckPermissionRequest
type CheckPermissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Permission to check
	Permission    string `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{7}
}

func (x *CheckPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckPermissionRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

// CheckPermissionResponse
type CheckPermissionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the user has the permission
	HasPermission bool `protobuf:"varint,1,opt,name=has_permission,json=hasPermission,proto3" json:"has_permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResponse) Reset() {
	*x = CheckPermissionResponse{}
	mi := &file_auth_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResponse) ProtoMessage() {}

func (x *CheckPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{8}
}

func (x *CheckPermissionResponse) GetHasPermission() bool {
	if x != nil {
		return x.HasPermission
	}
	return false
}

// UpdateUserRequest for updating user phone number, email, and/or cloud9 tag
type UpdateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entity ID of the user to update
	EntityId string `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	// Phone number in E.164 format (e.g., "+254712345678")
	PhoneNumber *string `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3,oneof" json:"phone_number,omitempty"`
	// Email address
	Email *string `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	// Cloud9 tag (e.g. "$alice")
	Cloud9Tag     *string `protobuf:"bytes,4,opt,name=cloud9_tag,json=cloud9Tag,proto3,oneof" json:"cloud9_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_auth_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *UpdateUserRequest) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetCloud9Tag() string {
	if x != nil && x.Cloud9Tag != nil {
		return *x.Cloud9Tag
	}
	return ""
}

// UpdateUserResponse
type UpdateUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the update was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Status message
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_auth_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Initiates OTP to existing number
type SendOTPToContactRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entity ID of the user to send OTP to
	EntityId string `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	// Phone number in E.164 format (e.g., "+254712345678")
	PhoneNumber *string `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3,oneof" json:"phone_number,omitempty"`
	// Email address
	Email         *string                               `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	ContactStatus SendOTPToContactRequest_ContactStatus `protobuf:"varint,4,opt,name=contact_status,json=contactStatus,proto3,enum=cloud9.auth.SendOTPToContactRequest_ContactStatus" json:"contact_status,omitempty"`
	OtpPurpose    SendOTPToContactRequest_OTPPurpose    `protobuf:"varint,5,opt,name=otp_purpose,json=otpPurpose,proto3,enum=cloud9.auth.SendOTPToContactRequest_OTPPurpose" json:"otp_purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOTPToContactRequest) Reset() {
	*x = SendOTPToContactRequest{}
	mi := &file_auth_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOTPToContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOTPToContactRequest) ProtoMessage() {}

func (x *SendOTPToContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOTPToContactRequest.ProtoReflect.Descriptor instead.
func (*SendOTPToContactRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{11}
}

func (x *SendOTPToContactRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *SendOTPToContactRequest) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

func (x *SendOTPToContactRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *SendOTPToContactRequest) GetContactStatus() SendOTPToContactRequest_ContactStatus {
	if x != nil {
		return x.ContactStatus
	}
	return SendOTPToContactRequest_OLD
}

func (x *SendOTPToContactRequest) GetOtpPurpose() SendOTPToContactRequest_OTPPurpose {
	if x != nil {
		return x.OtpPurpose
	}
	return SendOTPToContactRequest_UPDATE_CONTACT
}

type SendOTPToContactResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the OTP was sent successfully
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Status message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Verification token to be used for OTP verification
	VerificationToken string `protobuf:"bytes,3,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	// Expiration time for the OTP
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Verification status
	Verified      bool `protobuf:"varint,5,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOTPToContactResponse) Reset() {
	*x = SendOTPToContactResponse{}
	mi := &file_auth_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOTPToContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOTPToContactResponse) ProtoMessage() {}

func (x *SendOTPToContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOTPToContactResponse.ProtoReflect.Descriptor instead.
func (*SendOTPToContactResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{12}
}

func (x *SendOTPToContactResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendOTPToContactResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendOTPToContactResponse) GetVerificationToken() string {
	if x != nil {
		return x.VerificationToken
	}
	return ""
}

func (x *SendOTPToContactResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *SendOTPToContactResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

// Validates code and marks old contact as verified
type VerifyContactOTPRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Verification token received from SendOTPToOldContactResponse
	VerificationToken string `protobuf:"bytes,1,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	// OTP code received by the user
	OtpCode string `protobuf:"bytes,2,opt,name=otp_code,json=otpCode,proto3" json:"otp_code,omitempty"`
	// entity ID of the user to verify
	EntityId      string `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyContactOTPRequest) Reset() {
	*x = VerifyContactOTPRequest{}
	mi := &file_auth_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyContactOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyContactOTPRequest) ProtoMessage() {}

func (x *VerifyContactOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyContactOTPRequest.ProtoReflect.Descriptor instead.
func (*VerifyContactOTPRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{13}
}

func (x *VerifyContactOTPRequest) GetVerificationToken() string {
	if x != nil {
		return x.VerificationToken
	}
	return ""
}

func (x *VerifyContactOTPRequest) GetOtpCode() string {
	if x != nil {
		return x.OtpCode
	}
	return ""
}

func (x *VerifyContactOTPRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type VerifyContactOTPResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the verification was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Status message
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyContactOTPResponse) Reset() {
	*x = VerifyContactOTPResponse{}
	mi := &file_auth_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyContactOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyContactOTPResponse) ProtoMessage() {}

func (x *VerifyContactOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyContactOTPResponse.ProtoReflect.Descriptor instead.
func (*VerifyContactOTPResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{14}
}

func (x *VerifyContactOTPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifyContactOTPResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_auth_auth_proto protoreflect.FileDescriptor

const file_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x0fauth/auth.proto\x12\vcloud9.auth\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x02\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12 \n" +
	"\vpermissions\x18\x06 \x03(\tR\vpermissions\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\"\n" +
	"\fjurisdiction\x18\b \x01(\tR\fjurisdiction\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"cloud9_tag\x18\n" +
	" \x01(\tR\tcloud9Tag\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"j\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12%\n" +
	"\x04user\x18\x02 \x01(\v2\x11.cloud9.auth.UserR\x04user\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"8\n" +
	"\x0fGetUserResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.cloud9.auth.UserR\x04user\"7\n" +
	"\x18GetUserByEntityIDRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\"B\n" +
	"\x19GetUserByEntityIDResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.cloud9.auth.UserR\x04user\"Q\n" +
	"\x16CheckPermissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"permission\x18\x02 \x01(\tR\n" +
	"permission\"@\n" +
	"\x17CheckPermissionResponse\x12%\n" +
	"\x0ehas_permission\x18\x01 \x01(\bR\rhasPermission\"\xc1\x01\n" +
	"\x11UpdateUserRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12&\n" +
	"\fphone_number\x18\x02 \x01(\tH\x00R\vphoneNumber\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x01R\x05email\x88\x01\x01\x12\"\n" +
	"\n" +
	"cloud9_tag\x18\x04 \x01(\tH\x02R\tcloud9Tag\x88\x01\x01B\x0f\n" +
	"\r_phone_numberB\b\n" +
	"\x06_emailB\r\n" +
	"\v_cloud9_tag\"H\n" +
	"\x12UpdateUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9a\x03\n" +
	"\x17SendOTPToContactRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12&\n" +
	"\fphone_number\x18\x02 \x01(\tH\x00R\vphoneNumber\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x01R\x05email\x88\x01\x01\x12Y\n" +
	"\x0econtact_status\x18\x04 \x01(\x0e22.cloud9.auth.SendOTPToContactRequest.ContactStatusR\rcontactStatus\x12P\n" +
	"\votp_purpose\x18\x05 \x01(\x0e2/.cloud9.auth.SendOTPToContactRequest.OTPPurposeR\n" +
	"otpPurpose\"!\n" +
	"\rContactStatus\x12\a\n" +
	"\x03OLD\x10\x00\x12\a\n" +
	"\x03NEW\x10\x01\"4\n" +
	"\n" +
	"OTPPurpose\x12\x12\n" +
	"\x0eUPDATE_CONTACT\x10\x00\x12\x12\n" +
	"\x0eVERIFY_CONTACT\x10\x01B\x0f\n" +
	"\r_phone_numberB\b\n" +
	"\x06_email\"\xd4\x01\n" +
	"\x18SendOTPToContactResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x12verification_token\x18\x03 \x01(\tR\x11verificationToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1a\n" +
	"\bverified\x18\x05 \x01(\bR\bverified\"\x80\x01\n" +
	"\x17VerifyContactOTPRequest\x12-\n" +
	"\x12verification_token\x18\x01 \x01(\tR\x11verificationToken\x12\x19\n" +
	"\botp_code\x18\x02 \x01(\tR\aotpCode\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\"N\n" +
	"\x18VerifyContactOTPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xfe\x04\n" +
	"\vAuthService\x12V\n" +
	"\rValidateToken\x12!.cloud9.auth.ValidateTokenRequest\x1a\".cloud9.auth.ValidateTokenResponse\x12D\n" +
	"\aGetUser\x12\x1b.cloud9.auth.GetUserRequest\x1a\x1c.cloud9.auth.GetUserResponse\x12b\n" +
	"\x11GetUserByEntityID\x12%.cloud9.auth.GetUserByEntityIDRequest\x1a&.cloud9.auth.GetUserByEntityIDResponse\x12\\\n" +
	"\x0fCheckPermission\x12#.cloud9.auth.CheckPermissionRequest\x1a$.cloud9.auth.CheckPermissionResponse\x12M\n" +
	"\n" +
	"UpdateUser\x12\x1e.cloud9.auth.UpdateUserRequest\x1a\x1f.cloud9.auth.UpdateUserResponse\x12_\n" +
	"\x10SendOTPToContact\x12$.cloud9.auth.SendOTPToContactRequest\x1a%.cloud9.auth.SendOTPToContactResponse\x12_\n" +
	"\x10VerifyContactOTP\x12$.cloud9.auth.VerifyContactOTPRequest\x1a%.cloud9.auth.VerifyContactOTPResponseB5Z3github.com/Cloud9Money/api-protos/proto/auth;authpbb\x06proto3"

var (
	file_auth_auth_proto_rawDescOnce sync.Once
	file_auth_auth_proto_rawDescData []byte
)

func file_auth_auth_proto_rawDescGZIP() []byte {
	file_auth_auth_proto_rawDescOnce.Do(func() {
		file_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)))
	})
	return file_auth_auth_proto_rawDescData
}

var file_auth_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_auth_auth_proto_goTypes = []any{
	(SendOTPToContactRequest_ContactStatus)(0), // 0: cloud9.auth.SendOTPToContactRequest.ContactStatus
	(SendOTPToContactRequest_OTPPurpose)(0),    // 1: cloud9.auth.SendOTPToContactRequest.OTPPurpose
	(*User)(nil),                               // 2: cloud9.auth.User
	(*ValidateTokenRequest)(nil),               // 3: cloud9.auth.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),              // 4: cloud9.auth.ValidateTokenResponse
	(*GetUserRequest)(nil),                     // 5: cloud9.auth.GetUserRequest
	(*GetUserResponse)(nil),                    // 6: cloud9.auth.GetUserResponse
	(*GetUserByEntityIDRequest)(nil),           // 7: cloud9.auth.GetUserByEntityIDRequest
	(*GetUserByEntityIDResponse)(nil),          // 8: cloud9.auth.GetUserByEntityIDResponse
	(*CheckPermissionRequest)(nil),             // 9: cloud9.auth.CheckPermissionRequest
	(*CheckPermissionResponse)(nil),            // 10: cloud9.auth.CheckPermissionResponse
	(*UpdateUserRequest)(nil),                  // 11: cloud9.auth.UpdateUserRequest
	(*UpdateUserResponse)(nil),                 // 12: cloud9.auth.UpdateUserResponse
	(*SendOTPToContactRequest)(nil),            // 13: cloud9.auth.SendOTPToContactRequest
	(*SendOTPToContactResponse)(nil),           // 14: cloud9.auth.SendOTPToContactResponse
	(*VerifyContactOTPRequest)(nil),            // 15: cloud9.auth.VerifyContactOTPRequest
	(*VerifyContactOTPResponse)(nil),           // 16: cloud9.auth.VerifyContactOTPResponse
	(*timestamppb.Timestamp)(nil),              // 17: google.protobuf.Timestamp
}
var file_auth_auth_proto_depIdxs = []int32{
	17, // 0: cloud9.auth.User.created_at:type_name -> google.protobuf.Timestamp
	2,  // 1: cloud9.auth.ValidateTokenResponse.user:type_name -> cloud9.auth.User
	2,  // 2: cloud9.auth.GetUserResponse.user:type_name -> cloud9.auth.User
	2,  // 3: cloud9.auth.GetUserByEntityIDResponse.user:type_name -> cloud9.auth.User
	0,  // 4: cloud9.auth.SendOTPToContactRequest.contact_status:type_name -> cloud9.auth.SendOTPToContactRequest.ContactStatus
	1,  // 5: cloud9.auth.SendOTPToContactRequest.otp_purpose:type_name -> cloud9.auth.SendOTPToContactRequest.OTPPurpose
	17, // 6: cloud9.auth.SendOTPToContactResponse.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 7: cloud9.auth.AuthService.ValidateToken:input_type -> cloud9.auth.ValidateTokenRequest
	5,  // 8: cloud9.auth.AuthService.GetUser:input_type -> cloud9.auth.GetUserRequest
	7,  // 9: cloud9.auth.AuthService.GetUserByEntityID:input_type -> cloud9.auth.GetUserByEntityIDRequest
	9,  // 10: cloud9.auth.AuthService.CheckPermission:input_type -> cloud9.auth.CheckPermissionRequest
	11, // 11: cloud9.auth.AuthService.UpdateUser:input_type -> cloud9.auth.UpdateUserRequest
	13, // 12: cloud9.auth.AuthService.SendOTPToContact:input_type -> cloud9.auth.SendOTPToContactRequest
	15, // 13: cloud9.auth.AuthService.VerifyContactOTP:input_type -> cloud9.auth.VerifyContactOTPRequest
	4,  // 14: cloud9.auth.AuthService.ValidateToken:output_type -> cloud9.auth.ValidateTokenResponse
	6,  // 15: cloud9.auth.AuthService.GetUser:output_type -> cloud9.auth.GetUserResponse
	8,  // 16: cloud9.auth.AuthService.GetUserByEntityID:output_type -> cloud9.auth.GetUserByEntityIDResponse
	10, // 17: cloud9.auth.AuthService.CheckPermission:output_type -> cloud9.auth.CheckPermissionResponse
	12, // 18: cloud9.auth.AuthService.UpdateUser:output_type -> cloud9.auth.UpdateUserResponse
	14, // 19: cloud9.auth.AuthService.SendOTPToContact:output_type -> cloud9.auth.SendOTPToContactResponse
	16, // 20: cloud9.auth.AuthService.VerifyContactOTP:output_type -> cloud9.auth.VerifyContactOTPResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_auth_auth_proto_init() }
func file_auth_auth_proto_init() {
	if File_auth_auth_proto != nil {
		return
	}
	file_auth_auth_proto_msgTypes[9].OneofWrappers = []any{}
	file_auth_auth_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_auth_proto_goTypes,
		DependencyIndexes: file_auth_auth_proto_depIdxs,
		EnumInfos:         file_auth_auth_proto_enumTypes,
		MessageInfos:      file_auth_auth_proto_msgTypes,
	}.Build()
	File_auth_auth_proto = out.File
	file_auth_auth_proto_goTypes = nil
	file_auth_auth_proto_depIdxs = nil
}
