// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/push/v1/push.proto

package pushv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PushService_RegisterDevice_FullMethodName                = "/push.v1.PushService/RegisterDevice"
	PushService_UnregisterDevice_FullMethodName              = "/push.v1.PushService/UnregisterDevice"
	PushService_UnregisterAllDevices_FullMethodName          = "/push.v1.PushService/UnregisterAllDevices"
	PushService_SendPush_FullMethodName                      = "/push.v1.PushService/SendPush"
	PushService_SendPushToEntity_FullMethodName              = "/push.v1.PushService/SendPushToEntity"
	PushService_SendTemplatePush_FullMethodName              = "/push.v1.PushService/SendTemplatePush"
	PushService_GetUserDevices_FullMethodName                = "/push.v1.PushService/GetUserDevices"
	PushService_GetNotificationPreferences_FullMethodName    = "/push.v1.PushService/GetNotificationPreferences"
	PushService_UpdateNotificationPreferences_FullMethodName = "/push.v1.PushService/UpdateNotificationPreferences"
	PushService_GetPushStatus_FullMethodName                 = "/push.v1.PushService/GetPushStatus"
	PushService_ListPushNotifications_FullMethodName         = "/push.v1.PushService/ListPushNotifications"
)

// PushServiceClient is the client API for PushService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PushService provides push notification capabilities
type PushServiceClient interface {
	// RegisterDevice registers a device for push notifications
	RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error)
	// UnregisterDevice removes a device from push notifications
	UnregisterDevice(ctx context.Context, in *UnregisterDeviceRequest, opts ...grpc.CallOption) (*UnregisterDeviceResponse, error)
	// UnregisterAllDevices removes all devices for a user
	UnregisterAllDevices(ctx context.Context, in *UnregisterAllDevicesRequest, opts ...grpc.CallOption) (*UnregisterAllDevicesResponse, error)
	// SendPush sends a push notification to a user
	SendPush(ctx context.Context, in *SendPushRequest, opts ...grpc.CallOption) (*SendPushResponse, error)
	// SendPushToEntity sends a push notification to all users of an entity
	SendPushToEntity(ctx context.Context, in *SendPushToEntityRequest, opts ...grpc.CallOption) (*SendPushResponse, error)
	// SendTemplatePush sends a push notification using a template
	SendTemplatePush(ctx context.Context, in *SendTemplatePushRequest, opts ...grpc.CallOption) (*SendPushResponse, error)
	// GetUserDevices returns all active devices for a user
	GetUserDevices(ctx context.Context, in *GetUserDevicesRequest, opts ...grpc.CallOption) (*GetUserDevicesResponse, error)
	// GetNotificationPreferences returns notification preferences for a user
	GetNotificationPreferences(ctx context.Context, in *GetNotificationPreferencesRequest, opts ...grpc.CallOption) (*NotificationPreferences, error)
	// UpdateNotificationPreferences updates notification preferences for a user
	UpdateNotificationPreferences(ctx context.Context, in *UpdateNotificationPreferencesRequest, opts ...grpc.CallOption) (*NotificationPreferences, error)
	// GetPushStatus retrieves the status of a sent push notification
	GetPushStatus(ctx context.Context, in *GetPushStatusRequest, opts ...grpc.CallOption) (*PushStatus, error)
	// ListPushNotifications lists push notifications with filtering
	ListPushNotifications(ctx context.Context, in *ListPushNotificationsRequest, opts ...grpc.CallOption) (*ListPushNotificationsResponse, error)
}

type pushServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPushServiceClient(cc grpc.ClientConnInterface) PushServiceClient {
	return &pushServiceClient{cc}
}

func (c *pushServiceClient) RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDeviceResponse)
	err := c.cc.Invoke(ctx, PushService_RegisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushServiceClient) UnregisterDevice(ctx context.Context, in *UnregisterDeviceRequest, opts ...grpc.CallOption) (*UnregisterDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterDeviceResponse)
	err := c.cc.Invoke(ctx, PushService_UnregisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushServiceClient) UnregisterAllDevices(ctx context.Context, in *UnregisterAllDevicesRequest, opts ...grpc.CallOption) (*UnregisterAllDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterAllDevicesResponse)
	err := c.cc.Invoke(ctx, PushService_UnregisterAllDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushServiceClient) SendPush(ctx context.Context, in *SendPushRequest, opts ...grpc.CallOption) (*SendPushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendPushResponse)
	err := c.cc.Invoke(ctx, PushService_SendPush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushServiceClient) SendPushToEntity(ctx context.Context, in *SendPushToEntityRequest, opts ...grpc.CallOption) (*SendPushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendPushResponse)
	err := c.cc.Invoke(ctx, PushService_SendPushToEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushServiceClient) SendTemplatePush(ctx context.Context, in *SendTemplatePushRequest, opts ...grpc.CallOption) (*SendPushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendPushResponse)
	err := c.cc.Invoke(ctx, PushService_SendTemplatePush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushServiceClient) GetUserDevices(ctx context.Context, in *GetUserDevicesRequest, opts ...grpc.CallOption) (*GetUserDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserDevicesResponse)
	err := c.cc.Invoke(ctx, PushService_GetUserDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushServiceClient) GetNotificationPreferences(ctx context.Context, in *GetNotificationPreferencesRequest, opts ...grpc.CallOption) (*NotificationPreferences, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificationPreferences)
	err := c.cc.Invoke(ctx, PushService_GetNotificationPreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushServiceClient) UpdateNotificationPreferences(ctx context.Context, in *UpdateNotificationPreferencesRequest, opts ...grpc.CallOption) (*NotificationPreferences, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificationPreferences)
	err := c.cc.Invoke(ctx, PushService_UpdateNotificationPreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushServiceClient) GetPushStatus(ctx context.Context, in *GetPushStatusRequest, opts ...grpc.CallOption) (*PushStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushStatus)
	err := c.cc.Invoke(ctx, PushService_GetPushStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushServiceClient) ListPushNotifications(ctx context.Context, in *ListPushNotificationsRequest, opts ...grpc.CallOption) (*ListPushNotificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPushNotificationsResponse)
	err := c.cc.Invoke(ctx, PushService_ListPushNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushServiceServer is the server API for PushService service.
// All implementations must embed UnimplementedPushServiceServer
// for forward compatibility.
//
// PushService provides push notification capabilities
type PushServiceServer interface {
	// RegisterDevice registers a device for push notifications
	RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error)
	// UnregisterDevice removes a device from push notifications
	UnregisterDevice(context.Context, *UnregisterDeviceRequest) (*UnregisterDeviceResponse, error)
	// UnregisterAllDevices removes all devices for a user
	UnregisterAllDevices(context.Context, *UnregisterAllDevicesRequest) (*UnregisterAllDevicesResponse, error)
	// SendPush sends a push notification to a user
	SendPush(context.Context, *SendPushRequest) (*SendPushResponse, error)
	// SendPushToEntity sends a push notification to all users of an entity
	SendPushToEntity(context.Context, *SendPushToEntityRequest) (*SendPushResponse, error)
	// SendTemplatePush sends a push notification using a template
	SendTemplatePush(context.Context, *SendTemplatePushRequest) (*SendPushResponse, error)
	// GetUserDevices returns all active devices for a user
	GetUserDevices(context.Context, *GetUserDevicesRequest) (*GetUserDevicesResponse, error)
	// GetNotificationPreferences returns notification preferences for a user
	GetNotificationPreferences(context.Context, *GetNotificationPreferencesRequest) (*NotificationPreferences, error)
	// UpdateNotificationPreferences updates notification preferences for a user
	UpdateNotificationPreferences(context.Context, *UpdateNotificationPreferencesRequest) (*NotificationPreferences, error)
	// GetPushStatus retrieves the status of a sent push notification
	GetPushStatus(context.Context, *GetPushStatusRequest) (*PushStatus, error)
	// ListPushNotifications lists push notifications with filtering
	ListPushNotifications(context.Context, *ListPushNotificationsRequest) (*ListPushNotificationsResponse, error)
	mustEmbedUnimplementedPushServiceServer()
}

// UnimplementedPushServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPushServiceServer struct{}

func (UnimplementedPushServiceServer) RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedPushServiceServer) UnregisterDevice(context.Context, *UnregisterDeviceRequest) (*UnregisterDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterDevice not implemented")
}
func (UnimplementedPushServiceServer) UnregisterAllDevices(context.Context, *UnregisterAllDevicesRequest) (*UnregisterAllDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterAllDevices not implemented")
}
func (UnimplementedPushServiceServer) SendPush(context.Context, *SendPushRequest) (*SendPushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPush not implemented")
}
func (UnimplementedPushServiceServer) SendPushToEntity(context.Context, *SendPushToEntityRequest) (*SendPushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPushToEntity not implemented")
}
func (UnimplementedPushServiceServer) SendTemplatePush(context.Context, *SendTemplatePushRequest) (*SendPushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendTemplatePush not implemented")
}
func (UnimplementedPushServiceServer) GetUserDevices(context.Context, *GetUserDevicesRequest) (*GetUserDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserDevices not implemented")
}
func (UnimplementedPushServiceServer) GetNotificationPreferences(context.Context, *GetNotificationPreferencesRequest) (*NotificationPreferences, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNotificationPreferences not implemented")
}
func (UnimplementedPushServiceServer) UpdateNotificationPreferences(context.Context, *UpdateNotificationPreferencesRequest) (*NotificationPreferences, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNotificationPreferences not implemented")
}
func (UnimplementedPushServiceServer) GetPushStatus(context.Context, *GetPushStatusRequest) (*PushStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPushStatus not implemented")
}
func (UnimplementedPushServiceServer) ListPushNotifications(context.Context, *ListPushNotificationsRequest) (*ListPushNotificationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPushNotifications not implemented")
}
func (UnimplementedPushServiceServer) mustEmbedUnimplementedPushServiceServer() {}
func (UnimplementedPushServiceServer) testEmbeddedByValue()                     {}

// UnsafePushServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushServiceServer will
// result in compilation errors.
type UnsafePushServiceServer interface {
	mustEmbedUnimplementedPushServiceServer()
}

func RegisterPushServiceServer(s grpc.ServiceRegistrar, srv PushServiceServer) {
	// If the following call panics, it indicates UnimplementedPushServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PushService_ServiceDesc, srv)
}

func _PushService_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushService_RegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).RegisterDevice(ctx, req.(*RegisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_UnregisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).UnregisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushService_UnregisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).UnregisterDevice(ctx, req.(*UnregisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_UnregisterAllDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterAllDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).UnregisterAllDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushService_UnregisterAllDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).UnregisterAllDevices(ctx, req.(*UnregisterAllDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_SendPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).SendPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushService_SendPush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).SendPush(ctx, req.(*SendPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_SendPushToEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPushToEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).SendPushToEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushService_SendPushToEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).SendPushToEntity(ctx, req.(*SendPushToEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_SendTemplatePush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTemplatePushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).SendTemplatePush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushService_SendTemplatePush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).SendTemplatePush(ctx, req.(*SendTemplatePushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_GetUserDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).GetUserDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushService_GetUserDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).GetUserDevices(ctx, req.(*GetUserDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_GetNotificationPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotificationPreferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).GetNotificationPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushService_GetNotificationPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).GetNotificationPreferences(ctx, req.(*GetNotificationPreferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_UpdateNotificationPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNotificationPreferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).UpdateNotificationPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushService_UpdateNotificationPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).UpdateNotificationPreferences(ctx, req.(*UpdateNotificationPreferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_GetPushStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPushStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).GetPushStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushService_GetPushStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).GetPushStatus(ctx, req.(*GetPushStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_ListPushNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPushNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).ListPushNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushService_ListPushNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).ListPushNotifications(ctx, req.(*ListPushNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PushService_ServiceDesc is the grpc.ServiceDesc for PushService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PushService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "push.v1.PushService",
	HandlerType: (*PushServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDevice",
			Handler:    _PushService_RegisterDevice_Handler,
		},
		{
			MethodName: "UnregisterDevice",
			Handler:    _PushService_UnregisterDevice_Handler,
		},
		{
			MethodName: "UnregisterAllDevices",
			Handler:    _PushService_UnregisterAllDevices_Handler,
		},
		{
			MethodName: "SendPush",
			Handler:    _PushService_SendPush_Handler,
		},
		{
			MethodName: "SendPushToEntity",
			Handler:    _PushService_SendPushToEntity_Handler,
		},
		{
			MethodName: "SendTemplatePush",
			Handler:    _PushService_SendTemplatePush_Handler,
		},
		{
			MethodName: "GetUserDevices",
			Handler:    _PushService_GetUserDevices_Handler,
		},
		{
			MethodName: "GetNotificationPreferences",
			Handler:    _PushService_GetNotificationPreferences_Handler,
		},
		{
			MethodName: "UpdateNotificationPreferences",
			Handler:    _PushService_UpdateNotificationPreferences_Handler,
		},
		{
			MethodName: "GetPushStatus",
			Handler:    _PushService_GetPushStatus_Handler,
		},
		{
			MethodName: "ListPushNotifications",
			Handler:    _PushService_ListPushNotifications_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/push/v1/push.proto",
}
