// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/common/money.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Money represents a monetary amount with currency
type Money struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Currency code (ISO 4217)
	Currency string `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	// Amount in minor units (e.g., cents for USD, cents for KES)
	// Stored as int64 to avoid floating point precision issues
	AmountMinorUnits int64 `protobuf:"varint,2,opt,name=amount_minor_units,json=amountMinorUnits,proto3" json:"amount_minor_units,omitempty"`
	// Human-readable amount (e.g., "1000.50")
	// For display purposes only, not for calculations
	DisplayAmount string `protobuf:"bytes,3,opt,name=display_amount,json=displayAmount,proto3" json:"display_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_proto_common_money_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_money_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_proto_common_money_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Money) GetAmountMinorUnits() int64 {
	if x != nil {
		return x.AmountMinorUnits
	}
	return 0
}

func (x *Money) GetDisplayAmount() string {
	if x != nil {
		return x.DisplayAmount
	}
	return ""
}

// Currency represents a supported currency
type Currency struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Currency code (ISO 4217)
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Currency name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Symbol (e.g., $, Ksh, USh)
	Symbol string `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Number of decimal places
	DecimalPlaces int32 `protobuf:"varint,4,opt,name=decimal_places,json=decimalPlaces,proto3" json:"decimal_places,omitempty"`
	// Minor unit name (e.g., cent, centime)
	MinorUnit     string `protobuf:"bytes,5,opt,name=minor_unit,json=minorUnit,proto3" json:"minor_unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_proto_common_money_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_money_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_proto_common_money_proto_rawDescGZIP(), []int{1}
}

func (x *Currency) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Currency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Currency) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Currency) GetDecimalPlaces() int32 {
	if x != nil {
		return x.DecimalPlaces
	}
	return 0
}

func (x *Currency) GetMinorUnit() string {
	if x != nil {
		return x.MinorUnit
	}
	return ""
}

// ExchangeRate represents FX conversion rate
type ExchangeRate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source currency code
	FromCurrency string `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	// Target currency code
	ToCurrency string `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	// Exchange rate
	Rate float64 `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`
	// Timestamp when rate was retrieved
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Provider (e.g., "choice_bank", "woodcore")
	Provider      string `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRate) Reset() {
	*x = ExchangeRate{}
	mi := &file_proto_common_money_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRate) ProtoMessage() {}

func (x *ExchangeRate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_money_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRate.ProtoReflect.Descriptor instead.
func (*ExchangeRate) Descriptor() ([]byte, []int) {
	return file_proto_common_money_proto_rawDescGZIP(), []int{2}
}

func (x *ExchangeRate) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *ExchangeRate) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *ExchangeRate) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *ExchangeRate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ExchangeRate) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

var File_proto_common_money_proto protoreflect.FileDescriptor

const file_proto_common_money_proto_rawDesc = "" +
	"\n" +
	"\x18proto/common/money.proto\x12\rcloud9.common\"x\n" +
	"\x05Money\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12,\n" +
	"\x12amount_minor_units\x18\x02 \x01(\x03R\x10amountMinorUnits\x12%\n" +
	"\x0edisplay_amount\x18\x03 \x01(\tR\rdisplayAmount\"\x90\x01\n" +
	"\bCurrency\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12%\n" +
	"\x0edecimal_places\x18\x04 \x01(\x05R\rdecimalPlaces\x12\x1d\n" +
	"\n" +
	"minor_unit\x18\x05 \x01(\tR\tminorUnit\"\xa2\x01\n" +
	"\fExchangeRate\x12#\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrency\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x01R\x04rate\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bproviderB)Z'github.com/cloud9/proto/common;commonpbb\x06proto3"

var (
	file_proto_common_money_proto_rawDescOnce sync.Once
	file_proto_common_money_proto_rawDescData []byte
)

func file_proto_common_money_proto_rawDescGZIP() []byte {
	file_proto_common_money_proto_rawDescOnce.Do(func() {
		file_proto_common_money_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_money_proto_rawDesc), len(file_proto_common_money_proto_rawDesc)))
	})
	return file_proto_common_money_proto_rawDescData
}

var file_proto_common_money_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_common_money_proto_goTypes = []any{
	(*Money)(nil),        // 0: cloud9.common.Money
	(*Currency)(nil),     // 1: cloud9.common.Currency
	(*ExchangeRate)(nil), // 2: cloud9.common.ExchangeRate
}
var file_proto_common_money_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_common_money_proto_init() }
func file_proto_common_money_proto_init() {
	if File_proto_common_money_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_money_proto_rawDesc), len(file_proto_common_money_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_money_proto_goTypes,
		DependencyIndexes: file_proto_common_money_proto_depIdxs,
		MessageInfos:      file_proto_common_money_proto_msgTypes,
	}.Build()
	File_proto_common_money_proto = out.File
	file_proto_common_money_proto_goTypes = nil
	file_proto_common_money_proto_depIdxs = nil
}
