// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: kyc/kyc.proto

package kycpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KYCService_GetEntityIDByProviderRequestID_FullMethodName = "/cloud9.kyc.KYCService/GetEntityIDByProviderRequestID"
	KYCService_GetVerificationByEntityID_FullMethodName      = "/cloud9.kyc.KYCService/GetVerificationByEntityID"
)

// KYCServiceClient is the client API for KYCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KYCService provides KYC verification operations for internal services
type KYCServiceClient interface {
	// GetEntityIDByProviderRequestID retrieves the entity ID associated with a provider request ID
	// This is used by Mithiril to look up entity IDs when processing onboarding completion webhooks
	GetEntityIDByProviderRequestID(ctx context.Context, in *GetEntityIDByProviderRequestIDRequest, opts ...grpc.CallOption) (*GetEntityIDByProviderRequestIDResponse, error)
	// GetVerificationByEntityID retrieves the latest KYC verification for an entity
	GetVerificationByEntityID(ctx context.Context, in *GetVerificationByEntityIDRequest, opts ...grpc.CallOption) (*GetVerificationByEntityIDResponse, error)
}

type kYCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKYCServiceClient(cc grpc.ClientConnInterface) KYCServiceClient {
	return &kYCServiceClient{cc}
}

func (c *kYCServiceClient) GetEntityIDByProviderRequestID(ctx context.Context, in *GetEntityIDByProviderRequestIDRequest, opts ...grpc.CallOption) (*GetEntityIDByProviderRequestIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntityIDByProviderRequestIDResponse)
	err := c.cc.Invoke(ctx, KYCService_GetEntityIDByProviderRequestID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kYCServiceClient) GetVerificationByEntityID(ctx context.Context, in *GetVerificationByEntityIDRequest, opts ...grpc.CallOption) (*GetVerificationByEntityIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVerificationByEntityIDResponse)
	err := c.cc.Invoke(ctx, KYCService_GetVerificationByEntityID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KYCServiceServer is the server API for KYCService service.
// All implementations must embed UnimplementedKYCServiceServer
// for forward compatibility.
//
// KYCService provides KYC verification operations for internal services
type KYCServiceServer interface {
	// GetEntityIDByProviderRequestID retrieves the entity ID associated with a provider request ID
	// This is used by Mithiril to look up entity IDs when processing onboarding completion webhooks
	GetEntityIDByProviderRequestID(context.Context, *GetEntityIDByProviderRequestIDRequest) (*GetEntityIDByProviderRequestIDResponse, error)
	// GetVerificationByEntityID retrieves the latest KYC verification for an entity
	GetVerificationByEntityID(context.Context, *GetVerificationByEntityIDRequest) (*GetVerificationByEntityIDResponse, error)
	mustEmbedUnimplementedKYCServiceServer()
}

// UnimplementedKYCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKYCServiceServer struct{}

func (UnimplementedKYCServiceServer) GetEntityIDByProviderRequestID(context.Context, *GetEntityIDByProviderRequestIDRequest) (*GetEntityIDByProviderRequestIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntityIDByProviderRequestID not implemented")
}
func (UnimplementedKYCServiceServer) GetVerificationByEntityID(context.Context, *GetVerificationByEntityIDRequest) (*GetVerificationByEntityIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVerificationByEntityID not implemented")
}
func (UnimplementedKYCServiceServer) mustEmbedUnimplementedKYCServiceServer() {}
func (UnimplementedKYCServiceServer) testEmbeddedByValue()                    {}

// UnsafeKYCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KYCServiceServer will
// result in compilation errors.
type UnsafeKYCServiceServer interface {
	mustEmbedUnimplementedKYCServiceServer()
}

func RegisterKYCServiceServer(s grpc.ServiceRegistrar, srv KYCServiceServer) {
	// If the following call panics, it indicates UnimplementedKYCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KYCService_ServiceDesc, srv)
}

func _KYCService_GetEntityIDByProviderRequestID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityIDByProviderRequestIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KYCServiceServer).GetEntityIDByProviderRequestID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KYCService_GetEntityIDByProviderRequestID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KYCServiceServer).GetEntityIDByProviderRequestID(ctx, req.(*GetEntityIDByProviderRequestIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KYCService_GetVerificationByEntityID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVerificationByEntityIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KYCServiceServer).GetVerificationByEntityID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KYCService_GetVerificationByEntityID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KYCServiceServer).GetVerificationByEntityID(ctx, req.(*GetVerificationByEntityIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KYCService_ServiceDesc is the grpc.ServiceDesc for KYCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KYCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud9.kyc.KYCService",
	HandlerType: (*KYCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEntityIDByProviderRequestID",
			Handler:    _KYCService_GetEntityIDByProviderRequestID_Handler,
		},
		{
			MethodName: "GetVerificationByEntityID",
			Handler:    _KYCService_GetVerificationByEntityID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kyc/kyc.proto",
}
