// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: entities/business_membership.proto

package entitiespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BusinessMembershipService_GetInviteDetails_FullMethodName             = "/cloud9.entities.BusinessMembershipService/GetInviteDetails"
	BusinessMembershipService_AcceptBusinessInvite_FullMethodName         = "/cloud9.entities.BusinessMembershipService/AcceptBusinessInvite"
	BusinessMembershipService_GetBusinessMemberPermissions_FullMethodName = "/cloud9.entities.BusinessMembershipService/GetBusinessMemberPermissions"
)

// BusinessMembershipServiceClient is the client API for BusinessMembershipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BusinessMembershipService provides business team-membership operations —
// invite issuance/acceptance and per-request permission lookups — for
// internal services (hama, rohan, citadel).
type BusinessMembershipServiceClient interface {
	// GetInviteDetails is called (via hama's public invite-accept screen) to
	// render either the director KYB-prefill screen or the plain
	// business-member "join" screen. Safe to call unauthenticated — the token
	// itself is the credential.
	GetInviteDetails(ctx context.Context, in *GetInviteDetailsRequest, opts ...grpc.CallOption) (*GetInviteDetailsResponse, error)
	// AcceptBusinessInvite activates the linked business_members row (if any)
	// and records accepted_by_user_id for the director-linkage consumer to
	// pick up. Idempotent — safe to retry; succeeds if already accepted by the
	// same user_id.
	AcceptBusinessInvite(ctx context.Context, in *AcceptBusinessInviteRequest, opts ...grpc.CallOption) (*AcceptBusinessInviteResponse, error)
	// GetBusinessMemberPermissions resolves a user's permissions on a specific
	// business. Called by rohan (through a cache) before authorizing
	// transaction writes for a business-acting entity.
	GetBusinessMemberPermissions(ctx context.Context, in *GetBusinessMemberPermissionsRequest, opts ...grpc.CallOption) (*GetBusinessMemberPermissionsResponse, error)
}

type businessMembershipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBusinessMembershipServiceClient(cc grpc.ClientConnInterface) BusinessMembershipServiceClient {
	return &businessMembershipServiceClient{cc}
}

func (c *businessMembershipServiceClient) GetInviteDetails(ctx context.Context, in *GetInviteDetailsRequest, opts ...grpc.CallOption) (*GetInviteDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInviteDetailsResponse)
	err := c.cc.Invoke(ctx, BusinessMembershipService_GetInviteDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessMembershipServiceClient) AcceptBusinessInvite(ctx context.Context, in *AcceptBusinessInviteRequest, opts ...grpc.CallOption) (*AcceptBusinessInviteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptBusinessInviteResponse)
	err := c.cc.Invoke(ctx, BusinessMembershipService_AcceptBusinessInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessMembershipServiceClient) GetBusinessMemberPermissions(ctx context.Context, in *GetBusinessMemberPermissionsRequest, opts ...grpc.CallOption) (*GetBusinessMemberPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBusinessMemberPermissionsResponse)
	err := c.cc.Invoke(ctx, BusinessMembershipService_GetBusinessMemberPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusinessMembershipServiceServer is the server API for BusinessMembershipService service.
// All implementations must embed UnimplementedBusinessMembershipServiceServer
// for forward compatibility.
//
// BusinessMembershipService provides business team-membership operations —
// invite issuance/acceptance and per-request permission lookups — for
// internal services (hama, rohan, citadel).
type BusinessMembershipServiceServer interface {
	// GetInviteDetails is called (via hama's public invite-accept screen) to
	// render either the director KYB-prefill screen or the plain
	// business-member "join" screen. Safe to call unauthenticated — the token
	// itself is the credential.
	GetInviteDetails(context.Context, *GetInviteDetailsRequest) (*GetInviteDetailsResponse, error)
	// AcceptBusinessInvite activates the linked business_members row (if any)
	// and records accepted_by_user_id for the director-linkage consumer to
	// pick up. Idempotent — safe to retry; succeeds if already accepted by the
	// same user_id.
	AcceptBusinessInvite(context.Context, *AcceptBusinessInviteRequest) (*AcceptBusinessInviteResponse, error)
	// GetBusinessMemberPermissions resolves a user's permissions on a specific
	// business. Called by rohan (through a cache) before authorizing
	// transaction writes for a business-acting entity.
	GetBusinessMemberPermissions(context.Context, *GetBusinessMemberPermissionsRequest) (*GetBusinessMemberPermissionsResponse, error)
	mustEmbedUnimplementedBusinessMembershipServiceServer()
}

// UnimplementedBusinessMembershipServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBusinessMembershipServiceServer struct{}

func (UnimplementedBusinessMembershipServiceServer) GetInviteDetails(context.Context, *GetInviteDetailsRequest) (*GetInviteDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInviteDetails not implemented")
}
func (UnimplementedBusinessMembershipServiceServer) AcceptBusinessInvite(context.Context, *AcceptBusinessInviteRequest) (*AcceptBusinessInviteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptBusinessInvite not implemented")
}
func (UnimplementedBusinessMembershipServiceServer) GetBusinessMemberPermissions(context.Context, *GetBusinessMemberPermissionsRequest) (*GetBusinessMemberPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusinessMemberPermissions not implemented")
}
func (UnimplementedBusinessMembershipServiceServer) mustEmbedUnimplementedBusinessMembershipServiceServer() {
}
func (UnimplementedBusinessMembershipServiceServer) testEmbeddedByValue() {}

// UnsafeBusinessMembershipServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BusinessMembershipServiceServer will
// result in compilation errors.
type UnsafeBusinessMembershipServiceServer interface {
	mustEmbedUnimplementedBusinessMembershipServiceServer()
}

func RegisterBusinessMembershipServiceServer(s grpc.ServiceRegistrar, srv BusinessMembershipServiceServer) {
	// If the following call pancis, it indicates UnimplementedBusinessMembershipServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BusinessMembershipService_ServiceDesc, srv)
}

func _BusinessMembershipService_GetInviteDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInviteDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessMembershipServiceServer).GetInviteDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessMembershipService_GetInviteDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessMembershipServiceServer).GetInviteDetails(ctx, req.(*GetInviteDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessMembershipService_AcceptBusinessInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptBusinessInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessMembershipServiceServer).AcceptBusinessInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessMembershipService_AcceptBusinessInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessMembershipServiceServer).AcceptBusinessInvite(ctx, req.(*AcceptBusinessInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessMembershipService_GetBusinessMemberPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBusinessMemberPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessMembershipServiceServer).GetBusinessMemberPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessMembershipService_GetBusinessMemberPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessMembershipServiceServer).GetBusinessMemberPermissions(ctx, req.(*GetBusinessMemberPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BusinessMembershipService_ServiceDesc is the grpc.ServiceDesc for BusinessMembershipService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BusinessMembershipService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud9.entities.BusinessMembershipService",
	HandlerType: (*BusinessMembershipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInviteDetails",
			Handler:    _BusinessMembershipService_GetInviteDetails_Handler,
		},
		{
			MethodName: "AcceptBusinessInvite",
			Handler:    _BusinessMembershipService_AcceptBusinessInvite_Handler,
		},
		{
			MethodName: "GetBusinessMemberPermissions",
			Handler:    _BusinessMembershipService_GetBusinessMemberPermissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "entities/business_membership.proto",
}
