// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: entities/entities.proto

package entitiespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EntityService_GetEntity_FullMethodName            = "/cloud9.entities.EntityService/GetEntity"
	EntityService_GetBusinessDirectors_FullMethodName = "/cloud9.entities.EntityService/GetBusinessDirectors"
	EntityService_ListLLCShareholders_FullMethodName  = "/cloud9.entities.EntityService/ListLLCShareholders"
)

// EntityServiceClient is the client API for EntityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EntityService provides entity operations for internal services
type EntityServiceClient interface {
	// GetEntity retrieves an entity by ID with all details
	GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error)
	// GetBusinessDirectors retrieves all directors for a business entity
	GetBusinessDirectors(ctx context.Context, in *GetBusinessDirectorsRequest, opts ...grpc.CallOption) (*GetBusinessDirectorsResponse, error)
	// ListLLCShareholders returns all shareholder company details for an LLC business entity
	ListLLCShareholders(ctx context.Context, in *ListLLCShareholdersRequest, opts ...grpc.CallOption) (*ListLLCShareholdersResponse, error)
}

type entityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEntityServiceClient(cc grpc.ClientConnInterface) EntityServiceClient {
	return &entityServiceClient{cc}
}

func (c *entityServiceClient) GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntityResponse)
	err := c.cc.Invoke(ctx, EntityService_GetEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) GetBusinessDirectors(ctx context.Context, in *GetBusinessDirectorsRequest, opts ...grpc.CallOption) (*GetBusinessDirectorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBusinessDirectorsResponse)
	err := c.cc.Invoke(ctx, EntityService_GetBusinessDirectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) ListLLCShareholders(ctx context.Context, in *ListLLCShareholdersRequest, opts ...grpc.CallOption) (*ListLLCShareholdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLLCShareholdersResponse)
	err := c.cc.Invoke(ctx, EntityService_ListLLCShareholders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntityServiceServer is the server API for EntityService service.
// All implementations must embed UnimplementedEntityServiceServer
// for forward compatibility.
//
// EntityService provides entity operations for internal services
type EntityServiceServer interface {
	// GetEntity retrieves an entity by ID with all details
	GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error)
	// GetBusinessDirectors retrieves all directors for a business entity
	GetBusinessDirectors(context.Context, *GetBusinessDirectorsRequest) (*GetBusinessDirectorsResponse, error)
	// ListLLCShareholders returns all shareholder company details for an LLC business entity
	ListLLCShareholders(context.Context, *ListLLCShareholdersRequest) (*ListLLCShareholdersResponse, error)
	mustEmbedUnimplementedEntityServiceServer()
}

// UnimplementedEntityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEntityServiceServer struct{}

func (UnimplementedEntityServiceServer) GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntity not implemented")
}
func (UnimplementedEntityServiceServer) GetBusinessDirectors(context.Context, *GetBusinessDirectorsRequest) (*GetBusinessDirectorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusinessDirectors not implemented")
}
func (UnimplementedEntityServiceServer) ListLLCShareholders(context.Context, *ListLLCShareholdersRequest) (*ListLLCShareholdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLLCShareholders not implemented")
}
func (UnimplementedEntityServiceServer) mustEmbedUnimplementedEntityServiceServer() {}
func (UnimplementedEntityServiceServer) testEmbeddedByValue()                       {}

// UnsafeEntityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntityServiceServer will
// result in compilation errors.
type UnsafeEntityServiceServer interface {
	mustEmbedUnimplementedEntityServiceServer()
}

func RegisterEntityServiceServer(s grpc.ServiceRegistrar, srv EntityServiceServer) {
	// If the following call pancis, it indicates UnimplementedEntityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EntityService_ServiceDesc, srv)
}

func _EntityService_GetEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).GetEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityService_GetEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).GetEntity(ctx, req.(*GetEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_GetBusinessDirectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBusinessDirectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).GetBusinessDirectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityService_GetBusinessDirectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).GetBusinessDirectors(ctx, req.(*GetBusinessDirectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_ListLLCShareholders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLLCShareholdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).ListLLCShareholders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityService_ListLLCShareholders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).ListLLCShareholders(ctx, req.(*ListLLCShareholdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EntityService_ServiceDesc is the grpc.ServiceDesc for EntityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EntityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud9.entities.EntityService",
	HandlerType: (*EntityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEntity",
			Handler:    _EntityService_GetEntity_Handler,
		},
		{
			MethodName: "GetBusinessDirectors",
			Handler:    _EntityService_GetBusinessDirectors_Handler,
		},
		{
			MethodName: "ListLLCShareholders",
			Handler:    _EntityService_ListLLCShareholders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "entities/entities.proto",
}
