// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: entities/entities.proto

package entitiespb

import (
	common "github.com/Cloud9Money/api-protos/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Entity represents a base entity (person or business)
type Entity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entity ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Entity type (PERSON or BUSINESS)
	Type common.EntityType `protobuf:"varint,2,opt,name=type,proto3,enum=cloud9.common.EntityType" json:"type,omitempty"`
	// Country (ISO 3166-1 alpha-3)
	Country string `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	// Phone number (E.164 format)
	PhoneNumber string `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// Email address
	Email string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	// Tax PIN
	TaxPin string `protobuf:"bytes,6,opt,name=tax_pin,json=taxPin,proto3" json:"tax_pin,omitempty"`
	// KYC status
	KycStatus string `protobuf:"bytes,7,opt,name=kyc_status,json=kycStatus,proto3" json:"kyc_status,omitempty"`
	// Address
	Address *Address `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	// Created timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Updated timestamp
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_entities_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{0}
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetType() common.EntityType {
	if x != nil {
		return x.Type
	}
	return common.EntityType(0)
}

func (x *Entity) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Entity) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Entity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Entity) GetTaxPin() string {
	if x != nil {
		return x.TaxPin
	}
	return ""
}

func (x *Entity) GetKycStatus() string {
	if x != nil {
		return x.KycStatus
	}
	return ""
}

func (x *Entity) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Entity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Entity) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Address represents a physical address
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line1         string                 `protobuf:"bytes,1,opt,name=line1,proto3" json:"line1,omitempty"`
	Line2         string                 `protobuf:"bytes,2,opt,name=line2,proto3" json:"line2,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode    string                 `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_entities_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetLine1() string {
	if x != nil {
		return x.Line1
	}
	return ""
}

func (x *Address) GetLine2() string {
	if x != nil {
		return x.Line2
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

// EntityPerson represents a person entity
type EntityPerson struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base entity
	Entity *Entity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	// First name
	FirstName string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// Last name
	LastName string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Middle name (optional)
	MiddleName string `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	// ID type (Passport, NationalID, etc.)
	IdType common.IDType `protobuf:"varint,5,opt,name=id_type,json=idType,proto3,enum=cloud9.common.IDType" json:"id_type,omitempty"`
	// ID number
	IdNumber string `protobuf:"bytes,6,opt,name=id_number,json=idNumber,proto3" json:"id_number,omitempty"`
	// Date of birth (YYYY-MM-DD format)
	DateOfBirth string `protobuf:"bytes,7,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	// Gender
	Gender common.Gender `protobuf:"varint,8,opt,name=gender,proto3,enum=cloud9.common.Gender" json:"gender,omitempty"`
	// Employment status
	EmploymentStatus common.EmploymentStatus `protobuf:"varint,9,opt,name=employment_status,json=employmentStatus,proto3,enum=cloud9.common.EmploymentStatus" json:"employment_status,omitempty"`
	// Monthly income range
	MonthlyIncome common.IncomeRange `protobuf:"varint,10,opt,name=monthly_income,json=monthlyIncome,proto3,enum=cloud9.common.IncomeRange" json:"monthly_income,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityPerson) Reset() {
	*x = EntityPerson{}
	mi := &file_entities_entities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityPerson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityPerson) ProtoMessage() {}

func (x *EntityPerson) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityPerson.ProtoReflect.Descriptor instead.
func (*EntityPerson) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{2}
}

func (x *EntityPerson) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *EntityPerson) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *EntityPerson) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *EntityPerson) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *EntityPerson) GetIdType() common.IDType {
	if x != nil {
		return x.IdType
	}
	return common.IDType(0)
}

func (x *EntityPerson) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

func (x *EntityPerson) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *EntityPerson) GetGender() common.Gender {
	if x != nil {
		return x.Gender
	}
	return common.Gender(0)
}

func (x *EntityPerson) GetEmploymentStatus() common.EmploymentStatus {
	if x != nil {
		return x.EmploymentStatus
	}
	return common.EmploymentStatus(0)
}

func (x *EntityPerson) GetMonthlyIncome() common.IncomeRange {
	if x != nil {
		return x.MonthlyIncome
	}
	return common.IncomeRange(0)
}

// EntityBusiness represents a business entity
type EntityBusiness struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base entity
	Entity *Entity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	// Business type
	BusinessType string `protobuf:"bytes,2,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	// Business legal name
	BusinessLegalName string `protobuf:"bytes,3,opt,name=business_legal_name,json=businessLegalName,proto3" json:"business_legal_name,omitempty"`
	// Registration number
	RegistrationNumber string `protobuf:"bytes,4,opt,name=registration_number,json=registrationNumber,proto3" json:"registration_number,omitempty"`
	// Industry
	Industry string `protobuf:"bytes,5,opt,name=industry,proto3" json:"industry,omitempty"`
	// Specific industry (if applicable)
	SpecifyIndustry string `protobuf:"bytes,6,opt,name=specify_industry,json=specifyIndustry,proto3" json:"specify_industry,omitempty"`
	// Director entity IDs
	Directors     []string `protobuf:"bytes,7,rep,name=directors,proto3" json:"directors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityBusiness) Reset() {
	*x = EntityBusiness{}
	mi := &file_entities_entities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityBusiness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityBusiness) ProtoMessage() {}

func (x *EntityBusiness) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityBusiness.ProtoReflect.Descriptor instead.
func (*EntityBusiness) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{3}
}

func (x *EntityBusiness) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *EntityBusiness) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *EntityBusiness) GetBusinessLegalName() string {
	if x != nil {
		return x.BusinessLegalName
	}
	return ""
}

func (x *EntityBusiness) GetRegistrationNumber() string {
	if x != nil {
		return x.RegistrationNumber
	}
	return ""
}

func (x *EntityBusiness) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *EntityBusiness) GetSpecifyIndustry() string {
	if x != nil {
		return x.SpecifyIndustry
	}
	return ""
}

func (x *EntityBusiness) GetDirectors() []string {
	if x != nil {
		return x.Directors
	}
	return nil
}

// GetEntityRequest
type GetEntityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entity ID
	EntityId      string `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityRequest) Reset() {
	*x = GetEntityRequest{}
	mi := &file_entities_entities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityRequest) ProtoMessage() {}

func (x *GetEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityRequest.ProtoReflect.Descriptor instead.
func (*GetEntityRequest) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{4}
}

func (x *GetEntityRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

// GetEntityResponse
type GetEntityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entity type
	EntityType common.EntityType `protobuf:"varint,1,opt,name=entity_type,json=entityType,proto3,enum=cloud9.common.EntityType" json:"entity_type,omitempty"`
	// Person data (if entity is a person)
	Person *EntityPerson `protobuf:"bytes,2,opt,name=person,proto3" json:"person,omitempty"`
	// Business data (if entity is a business)
	Business      *EntityBusiness `protobuf:"bytes,3,opt,name=business,proto3" json:"business,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityResponse) Reset() {
	*x = GetEntityResponse{}
	mi := &file_entities_entities_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityResponse) ProtoMessage() {}

func (x *GetEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityResponse.ProtoReflect.Descriptor instead.
func (*GetEntityResponse) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{5}
}

func (x *GetEntityResponse) GetEntityType() common.EntityType {
	if x != nil {
		return x.EntityType
	}
	return common.EntityType(0)
}

func (x *GetEntityResponse) GetPerson() *EntityPerson {
	if x != nil {
		return x.Person
	}
	return nil
}

func (x *GetEntityResponse) GetBusiness() *EntityBusiness {
	if x != nil {
		return x.Business
	}
	return nil
}

var File_entities_entities_proto protoreflect.FileDescriptor

const file_entities_entities_proto_rawDesc = "" +
	"\n" +
	"\x17entities/entities.proto\x12\x0fcloud9.entities\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19common/entity_types.proto\"\xfc\x02\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.cloud9.common.EntityTypeR\x04type\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x17\n" +
	"\atax_pin\x18\x06 \x01(\tR\x06taxPin\x12\x1d\n" +
	"\n" +
	"kyc_status\x18\a \x01(\tR\tkycStatus\x122\n" +
	"\aaddress\x18\b \x01(\v2\x18.cloud9.entities.AddressR\aaddress\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9a\x01\n" +
	"\aAddress\x12\x14\n" +
	"\x05line1\x18\x01 \x01(\tR\x05line1\x12\x14\n" +
	"\x05line2\x18\x02 \x01(\tR\x05line2\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x1f\n" +
	"\vpostal_code\x18\x06 \x01(\tR\n" +
	"postalCode\"\xcd\x03\n" +
	"\fEntityPerson\x12/\n" +
	"\x06entity\x18\x01 \x01(\v2\x17.cloud9.entities.EntityR\x06entity\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1f\n" +
	"\vmiddle_name\x18\x04 \x01(\tR\n" +
	"middleName\x12.\n" +
	"\aid_type\x18\x05 \x01(\x0e2\x15.cloud9.common.IDTypeR\x06idType\x12\x1b\n" +
	"\tid_number\x18\x06 \x01(\tR\bidNumber\x12\"\n" +
	"\rdate_of_birth\x18\a \x01(\tR\vdateOfBirth\x12-\n" +
	"\x06gender\x18\b \x01(\x0e2\x15.cloud9.common.GenderR\x06gender\x12L\n" +
	"\x11employment_status\x18\t \x01(\x0e2\x1f.cloud9.common.EmploymentStatusR\x10employmentStatus\x12A\n" +
	"\x0emonthly_income\x18\n" +
	" \x01(\x0e2\x1a.cloud9.common.IncomeRangeR\rmonthlyIncome\"\xac\x02\n" +
	"\x0eEntityBusiness\x12/\n" +
	"\x06entity\x18\x01 \x01(\v2\x17.cloud9.entities.EntityR\x06entity\x12#\n" +
	"\rbusiness_type\x18\x02 \x01(\tR\fbusinessType\x12.\n" +
	"\x13business_legal_name\x18\x03 \x01(\tR\x11businessLegalName\x12/\n" +
	"\x13registration_number\x18\x04 \x01(\tR\x12registrationNumber\x12\x1a\n" +
	"\bindustry\x18\x05 \x01(\tR\bindustry\x12)\n" +
	"\x10specify_industry\x18\x06 \x01(\tR\x0fspecifyIndustry\x12\x1c\n" +
	"\tdirectors\x18\a \x03(\tR\tdirectors\"/\n" +
	"\x10GetEntityRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\"\xc3\x01\n" +
	"\x11GetEntityResponse\x12:\n" +
	"\ventity_type\x18\x01 \x01(\x0e2\x19.cloud9.common.EntityTypeR\n" +
	"entityType\x125\n" +
	"\x06person\x18\x02 \x01(\v2\x1d.cloud9.entities.EntityPersonR\x06person\x12;\n" +
	"\bbusiness\x18\x03 \x01(\v2\x1f.cloud9.entities.EntityBusinessR\bbusiness2c\n" +
	"\rEntityService\x12R\n" +
	"\tGetEntity\x12!.cloud9.entities.GetEntityRequest\x1a\".cloud9.entities.GetEntityResponseB=Z;github.com/Cloud9Money/api-protos/proto/entities;entitiespbb\x06proto3"

var (
	file_entities_entities_proto_rawDescOnce sync.Once
	file_entities_entities_proto_rawDescData []byte
)

func file_entities_entities_proto_rawDescGZIP() []byte {
	file_entities_entities_proto_rawDescOnce.Do(func() {
		file_entities_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_entities_proto_rawDesc), len(file_entities_entities_proto_rawDesc)))
	})
	return file_entities_entities_proto_rawDescData
}

var file_entities_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_entities_entities_proto_goTypes = []any{
	(*Entity)(nil),                // 0: cloud9.entities.Entity
	(*Address)(nil),               // 1: cloud9.entities.Address
	(*EntityPerson)(nil),          // 2: cloud9.entities.EntityPerson
	(*EntityBusiness)(nil),        // 3: cloud9.entities.EntityBusiness
	(*GetEntityRequest)(nil),      // 4: cloud9.entities.GetEntityRequest
	(*GetEntityResponse)(nil),     // 5: cloud9.entities.GetEntityResponse
	(common.EntityType)(0),        // 6: cloud9.common.EntityType
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(common.IDType)(0),            // 8: cloud9.common.IDType
	(common.Gender)(0),            // 9: cloud9.common.Gender
	(common.EmploymentStatus)(0),  // 10: cloud9.common.EmploymentStatus
	(common.IncomeRange)(0),       // 11: cloud9.common.IncomeRange
}
var file_entities_entities_proto_depIdxs = []int32{
	6,  // 0: cloud9.entities.Entity.type:type_name -> cloud9.common.EntityType
	1,  // 1: cloud9.entities.Entity.address:type_name -> cloud9.entities.Address
	7,  // 2: cloud9.entities.Entity.created_at:type_name -> google.protobuf.Timestamp
	7,  // 3: cloud9.entities.Entity.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: cloud9.entities.EntityPerson.entity:type_name -> cloud9.entities.Entity
	8,  // 5: cloud9.entities.EntityPerson.id_type:type_name -> cloud9.common.IDType
	9,  // 6: cloud9.entities.EntityPerson.gender:type_name -> cloud9.common.Gender
	10, // 7: cloud9.entities.EntityPerson.employment_status:type_name -> cloud9.common.EmploymentStatus
	11, // 8: cloud9.entities.EntityPerson.monthly_income:type_name -> cloud9.common.IncomeRange
	0,  // 9: cloud9.entities.EntityBusiness.entity:type_name -> cloud9.entities.Entity
	6,  // 10: cloud9.entities.GetEntityResponse.entity_type:type_name -> cloud9.common.EntityType
	2,  // 11: cloud9.entities.GetEntityResponse.person:type_name -> cloud9.entities.EntityPerson
	3,  // 12: cloud9.entities.GetEntityResponse.business:type_name -> cloud9.entities.EntityBusiness
	4,  // 13: cloud9.entities.EntityService.GetEntity:input_type -> cloud9.entities.GetEntityRequest
	5,  // 14: cloud9.entities.EntityService.GetEntity:output_type -> cloud9.entities.GetEntityResponse
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_entities_entities_proto_init() }
func file_entities_entities_proto_init() {
	if File_entities_entities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_entities_proto_rawDesc), len(file_entities_entities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_entities_entities_proto_goTypes,
		DependencyIndexes: file_entities_entities_proto_depIdxs,
		MessageInfos:      file_entities_entities_proto_msgTypes,
	}.Build()
	File_entities_entities_proto = out.File
	file_entities_entities_proto_goTypes = nil
	file_entities_entities_proto_depIdxs = nil
}
