// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: entities/entities.proto

package entitiespb

import (
	common "github.com/Cloud9Money/api-protos/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Entity represents a base entity (person or business)
type Entity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entity ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Entity type (PERSON or BUSINESS)
	Type common.EntityType `protobuf:"varint,2,opt,name=type,proto3,enum=cloud9.common.EntityType" json:"type,omitempty"`
	// Country (ISO 3166-1 alpha-3)
	Country string `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	// Phone number (E.164 format)
	PhoneNumber string `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// Email address
	Email string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	// Tax PIN
	TaxPin string `protobuf:"bytes,6,opt,name=tax_pin,json=taxPin,proto3" json:"tax_pin,omitempty"`
	// KYC status
	KycStatus string `protobuf:"bytes,7,opt,name=kyc_status,json=kycStatus,proto3" json:"kyc_status,omitempty"`
	// KYC verification level (0=None, 1=CIP, 2=CDD, 3=EDD)
	KycLevel int32 `protobuf:"varint,11,opt,name=kyc_level,json=kycLevel,proto3" json:"kyc_level,omitempty"`
	// Address
	Address *Address `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	// Created timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Updated timestamp
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_entities_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{0}
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetType() common.EntityType {
	if x != nil {
		return x.Type
	}
	return common.EntityType(0)
}

func (x *Entity) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Entity) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Entity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Entity) GetTaxPin() string {
	if x != nil {
		return x.TaxPin
	}
	return ""
}

func (x *Entity) GetKycStatus() string {
	if x != nil {
		return x.KycStatus
	}
	return ""
}

func (x *Entity) GetKycLevel() int32 {
	if x != nil {
		return x.KycLevel
	}
	return 0
}

func (x *Entity) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Entity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Entity) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Address represents a physical address
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line1         string                 `protobuf:"bytes,1,opt,name=line1,proto3" json:"line1,omitempty"`
	Line2         string                 `protobuf:"bytes,2,opt,name=line2,proto3" json:"line2,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode    string                 `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_entities_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetLine1() string {
	if x != nil {
		return x.Line1
	}
	return ""
}

func (x *Address) GetLine2() string {
	if x != nil {
		return x.Line2
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

// EntityPerson represents a person entity
type EntityPerson struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base entity
	Entity *Entity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	// First name
	FirstName string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// Last name
	LastName string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Middle name (optional)
	MiddleName string `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	// ID type (Passport, NationalID, etc.)
	IdType common.IDType `protobuf:"varint,5,opt,name=id_type,json=idType,proto3,enum=cloud9.common.IDType" json:"id_type,omitempty"`
	// ID number
	IdNumber string `protobuf:"bytes,6,opt,name=id_number,json=idNumber,proto3" json:"id_number,omitempty"`
	// Date of birth (YYYY-MM-DD format)
	DateOfBirth string `protobuf:"bytes,7,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	// Gender
	Gender common.Gender `protobuf:"varint,8,opt,name=gender,proto3,enum=cloud9.common.Gender" json:"gender,omitempty"`
	// Employment status
	EmploymentStatus common.EmploymentStatus `protobuf:"varint,9,opt,name=employment_status,json=employmentStatus,proto3,enum=cloud9.common.EmploymentStatus" json:"employment_status,omitempty"`
	// Monthly income range
	MonthlyIncome common.IncomeRange `protobuf:"varint,10,opt,name=monthly_income,json=monthlyIncome,proto3,enum=cloud9.common.IncomeRange" json:"monthly_income,omitempty"`
	// Source of funds (required for high-risk customers e.g. Kenya)
	SourceOfFunds common.SourceOfFunds `protobuf:"varint,11,opt,name=source_of_funds,json=sourceOfFunds,proto3,enum=cloud9.common.SourceOfFunds" json:"source_of_funds,omitempty"`
	// Account purpose (required for high-risk customers e.g. Kenya)
	AccountPurpose common.AccountPurpose `protobuf:"varint,12,opt,name=account_purpose,json=accountPurpose,proto3,enum=cloud9.common.AccountPurpose" json:"account_purpose,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EntityPerson) Reset() {
	*x = EntityPerson{}
	mi := &file_entities_entities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityPerson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityPerson) ProtoMessage() {}

func (x *EntityPerson) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityPerson.ProtoReflect.Descriptor instead.
func (*EntityPerson) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{2}
}

func (x *EntityPerson) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *EntityPerson) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *EntityPerson) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *EntityPerson) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *EntityPerson) GetIdType() common.IDType {
	if x != nil {
		return x.IdType
	}
	return common.IDType(0)
}

func (x *EntityPerson) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

func (x *EntityPerson) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *EntityPerson) GetGender() common.Gender {
	if x != nil {
		return x.Gender
	}
	return common.Gender(0)
}

func (x *EntityPerson) GetEmploymentStatus() common.EmploymentStatus {
	if x != nil {
		return x.EmploymentStatus
	}
	return common.EmploymentStatus(0)
}

func (x *EntityPerson) GetMonthlyIncome() common.IncomeRange {
	if x != nil {
		return x.MonthlyIncome
	}
	return common.IncomeRange(0)
}

func (x *EntityPerson) GetSourceOfFunds() common.SourceOfFunds {
	if x != nil {
		return x.SourceOfFunds
	}
	return common.SourceOfFunds(0)
}

func (x *EntityPerson) GetAccountPurpose() common.AccountPurpose {
	if x != nil {
		return x.AccountPurpose
	}
	return common.AccountPurpose(0)
}

// EntityBusiness represents a business entity
type EntityBusiness struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base entity
	Entity *Entity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	// Business type
	BusinessType string `protobuf:"bytes,2,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	// Business legal name
	BusinessLegalName string `protobuf:"bytes,3,opt,name=business_legal_name,json=businessLegalName,proto3" json:"business_legal_name,omitempty"`
	// Registration number
	RegistrationNumber string `protobuf:"bytes,4,opt,name=registration_number,json=registrationNumber,proto3" json:"registration_number,omitempty"`
	// Industry
	Industry string `protobuf:"bytes,5,opt,name=industry,proto3" json:"industry,omitempty"`
	// Specific industry (if applicable)
	SpecifyIndustry string `protobuf:"bytes,6,opt,name=specify_industry,json=specifyIndustry,proto3" json:"specify_industry,omitempty"`
	// Director entity IDs
	Directors []string `protobuf:"bytes,7,rep,name=directors,proto3" json:"directors,omitempty"`
	// Choice Bank account operating mode: 1=Singly, 2=Either to Sign, 3=Any Two to Sign,
	// 4=All of Us Jointly, 5=Other. 0 means unset — consumers default to Singly.
	OperatingMode int32 `protobuf:"varint,8,opt,name=operating_mode,json=operatingMode,proto3" json:"operating_mode,omitempty"`
	// Free-text description of the operating mode, required when operating_mode == 5.
	SpecifyOperatingMode string `protobuf:"bytes,9,opt,name=specify_operating_mode,json=specifyOperatingMode,proto3" json:"specify_operating_mode,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EntityBusiness) Reset() {
	*x = EntityBusiness{}
	mi := &file_entities_entities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityBusiness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityBusiness) ProtoMessage() {}

func (x *EntityBusiness) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityBusiness.ProtoReflect.Descriptor instead.
func (*EntityBusiness) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{3}
}

func (x *EntityBusiness) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *EntityBusiness) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *EntityBusiness) GetBusinessLegalName() string {
	if x != nil {
		return x.BusinessLegalName
	}
	return ""
}

func (x *EntityBusiness) GetRegistrationNumber() string {
	if x != nil {
		return x.RegistrationNumber
	}
	return ""
}

func (x *EntityBusiness) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *EntityBusiness) GetSpecifyIndustry() string {
	if x != nil {
		return x.SpecifyIndustry
	}
	return ""
}

func (x *EntityBusiness) GetDirectors() []string {
	if x != nil {
		return x.Directors
	}
	return nil
}

func (x *EntityBusiness) GetOperatingMode() int32 {
	if x != nil {
		return x.OperatingMode
	}
	return 0
}

func (x *EntityBusiness) GetSpecifyOperatingMode() string {
	if x != nil {
		return x.SpecifyOperatingMode
	}
	return ""
}

// BusinessDirector represents a compliance director record on a business entity
type BusinessDirector struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID from business_directors table
	FirstName    string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName     string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	MiddleName   string                 `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	IdType       string                 `protobuf:"bytes,5,opt,name=id_type,json=idType,proto3" json:"id_type,omitempty"` // NationalID | Passport | AlienID
	IdNumber     string                 `protobuf:"bytes,6,opt,name=id_number,json=idNumber,proto3" json:"id_number,omitempty"`
	DateOfBirth  string                 `protobuf:"bytes,7,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`       // YYYY-MM-DD
	Nationality  string                 `protobuf:"bytes,8,opt,name=nationality,proto3" json:"nationality,omitempty"`                            // ISO 3166-1 alpha-3
	PhoneNumber  string                 `protobuf:"bytes,9,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`         // optional, may be empty
	Email        string                 `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`                                       // optional, may be empty
	Gender       string                 `protobuf:"bytes,11,opt,name=gender,proto3" json:"gender,omitempty"`                                     // "Male" or "Female" — Choice Bank requirement
	KraPin       string                 `protobuf:"bytes,12,opt,name=kra_pin,json=kraPin,proto3" json:"kra_pin,omitempty"`                       // KRA PIN number, e.g. A123456789B
	IdFrontDocId string                 `protobuf:"bytes,13,opt,name=id_front_doc_id,json=idFrontDocId,proto3" json:"id_front_doc_id,omitempty"` // document ID for front of ID document
	IdBackDocId  string                 `protobuf:"bytes,14,opt,name=id_back_doc_id,json=idBackDocId,proto3" json:"id_back_doc_id,omitempty"`    // document ID for back of ID document
	SelfieDocId  string                 `protobuf:"bytes,15,opt,name=selfie_doc_id,json=selfieDocId,proto3" json:"selfie_doc_id,omitempty"`      // document ID for selfie photo
	KraPinDocId  string                 `protobuf:"bytes,16,opt,name=kra_pin_doc_id,json=kraPinDocId,proto3" json:"kra_pin_doc_id,omitempty"`    // document ID for KRA PIN certificate
	// Role of this record on the business — "director" (LLC/LLP) or "proprietor"
	// (SoleProprietorship). Defaults to "director" for pre-existing records.
	Role            string `protobuf:"bytes,17,opt,name=role,proto3" json:"role,omitempty"`
	KinFullName     string `protobuf:"bytes,18,opt,name=kin_full_name,json=kinFullName,proto3" json:"kin_full_name,omitempty"`
	KinRelationship string `protobuf:"bytes,19,opt,name=kin_relationship,json=kinRelationship,proto3" json:"kin_relationship,omitempty"`
	// E.164, e.g. +254712345678; consumers split
	// country code and local number as needed
	KinPhoneNumber string `protobuf:"bytes,20,opt,name=kin_phone_number,json=kinPhoneNumber,proto3" json:"kin_phone_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BusinessDirector) Reset() {
	*x = BusinessDirector{}
	mi := &file_entities_entities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessDirector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessDirector) ProtoMessage() {}

func (x *BusinessDirector) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessDirector.ProtoReflect.Descriptor instead.
func (*BusinessDirector) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{4}
}

func (x *BusinessDirector) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BusinessDirector) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *BusinessDirector) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *BusinessDirector) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *BusinessDirector) GetIdType() string {
	if x != nil {
		return x.IdType
	}
	return ""
}

func (x *BusinessDirector) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

func (x *BusinessDirector) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *BusinessDirector) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *BusinessDirector) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *BusinessDirector) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BusinessDirector) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *BusinessDirector) GetKraPin() string {
	if x != nil {
		return x.KraPin
	}
	return ""
}

func (x *BusinessDirector) GetIdFrontDocId() string {
	if x != nil {
		return x.IdFrontDocId
	}
	return ""
}

func (x *BusinessDirector) GetIdBackDocId() string {
	if x != nil {
		return x.IdBackDocId
	}
	return ""
}

func (x *BusinessDirector) GetSelfieDocId() string {
	if x != nil {
		return x.SelfieDocId
	}
	return ""
}

func (x *BusinessDirector) GetKraPinDocId() string {
	if x != nil {
		return x.KraPinDocId
	}
	return ""
}

func (x *BusinessDirector) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *BusinessDirector) GetKinFullName() string {
	if x != nil {
		return x.KinFullName
	}
	return ""
}

func (x *BusinessDirector) GetKinRelationship() string {
	if x != nil {
		return x.KinRelationship
	}
	return ""
}

func (x *BusinessDirector) GetKinPhoneNumber() string {
	if x != nil {
		return x.KinPhoneNumber
	}
	return ""
}

// LLCShareholder holds the parent company details for an LLC business entity
type LLCShareholder struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                     // unique identifier for the shareholder record
	EntityId             string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`                                         // the LLC business entity UUID
	CompanyName          string                 `protobuf:"bytes,3,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`                                // legal name of the parent/shareholder company
	RegCertDocId         string                 `protobuf:"bytes,4,opt,name=reg_cert_doc_id,json=regCertDocId,proto3" json:"reg_cert_doc_id,omitempty"`                         // document ID for the registration certificate
	UboDocId             string                 `protobuf:"bytes,5,opt,name=ubo_doc_id,json=uboDocId,proto3" json:"ubo_doc_id,omitempty"`                                       // ultimate beneficiary owner document (KYCF00023)
	CoiDocId             string                 `protobuf:"bytes,6,opt,name=coi_doc_id,json=coiDocId,proto3" json:"coi_doc_id,omitempty"`                                       // certificate of incorporation (KYCF00029)
	Cr12DocId            string                 `protobuf:"bytes,7,opt,name=cr12_doc_id,json=cr12DocId,proto3" json:"cr12_doc_id,omitempty"`                                    // CR12 document (KYCF00029)
	BoardResolutionDocId string                 `protobuf:"bytes,8,opt,name=board_resolution_doc_id,json=boardResolutionDocId,proto3" json:"board_resolution_doc_id,omitempty"` // board resolution document (KYCF00029)
	KraCertDocId         string                 `protobuf:"bytes,9,opt,name=kra_cert_doc_id,json=kraCertDocId,proto3" json:"kra_cert_doc_id,omitempty"`                         // KRA certificate (KYCF00029)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LLCShareholder) Reset() {
	*x = LLCShareholder{}
	mi := &file_entities_entities_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLCShareholder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLCShareholder) ProtoMessage() {}

func (x *LLCShareholder) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLCShareholder.ProtoReflect.Descriptor instead.
func (*LLCShareholder) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{5}
}

func (x *LLCShareholder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LLCShareholder) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *LLCShareholder) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *LLCShareholder) GetRegCertDocId() string {
	if x != nil {
		return x.RegCertDocId
	}
	return ""
}

func (x *LLCShareholder) GetUboDocId() string {
	if x != nil {
		return x.UboDocId
	}
	return ""
}

func (x *LLCShareholder) GetCoiDocId() string {
	if x != nil {
		return x.CoiDocId
	}
	return ""
}

func (x *LLCShareholder) GetCr12DocId() string {
	if x != nil {
		return x.Cr12DocId
	}
	return ""
}

func (x *LLCShareholder) GetBoardResolutionDocId() string {
	if x != nil {
		return x.BoardResolutionDocId
	}
	return ""
}

func (x *LLCShareholder) GetKraCertDocId() string {
	if x != nil {
		return x.KraCertDocId
	}
	return ""
}

type ListLLCShareholdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLLCShareholdersRequest) Reset() {
	*x = ListLLCShareholdersRequest{}
	mi := &file_entities_entities_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLLCShareholdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLLCShareholdersRequest) ProtoMessage() {}

func (x *ListLLCShareholdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLLCShareholdersRequest.ProtoReflect.Descriptor instead.
func (*ListLLCShareholdersRequest) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{6}
}

func (x *ListLLCShareholdersRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type ListLLCShareholdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shareholders  []*LLCShareholder      `protobuf:"bytes,1,rep,name=shareholders,proto3" json:"shareholders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLLCShareholdersResponse) Reset() {
	*x = ListLLCShareholdersResponse{}
	mi := &file_entities_entities_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLLCShareholdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLLCShareholdersResponse) ProtoMessage() {}

func (x *ListLLCShareholdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLLCShareholdersResponse.ProtoReflect.Descriptor instead.
func (*ListLLCShareholdersResponse) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{7}
}

func (x *ListLLCShareholdersResponse) GetShareholders() []*LLCShareholder {
	if x != nil {
		return x.Shareholders
	}
	return nil
}

type GetBusinessDirectorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // business entity UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBusinessDirectorsRequest) Reset() {
	*x = GetBusinessDirectorsRequest{}
	mi := &file_entities_entities_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBusinessDirectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusinessDirectorsRequest) ProtoMessage() {}

func (x *GetBusinessDirectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusinessDirectorsRequest.ProtoReflect.Descriptor instead.
func (*GetBusinessDirectorsRequest) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{8}
}

func (x *GetBusinessDirectorsRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type GetBusinessDirectorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directors     []*BusinessDirector    `protobuf:"bytes,1,rep,name=directors,proto3" json:"directors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBusinessDirectorsResponse) Reset() {
	*x = GetBusinessDirectorsResponse{}
	mi := &file_entities_entities_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBusinessDirectorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusinessDirectorsResponse) ProtoMessage() {}

func (x *GetBusinessDirectorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusinessDirectorsResponse.ProtoReflect.Descriptor instead.
func (*GetBusinessDirectorsResponse) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{9}
}

func (x *GetBusinessDirectorsResponse) GetDirectors() []*BusinessDirector {
	if x != nil {
		return x.Directors
	}
	return nil
}

// GetEntityRequest
type GetEntityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entity ID
	EntityId      string `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityRequest) Reset() {
	*x = GetEntityRequest{}
	mi := &file_entities_entities_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityRequest) ProtoMessage() {}

func (x *GetEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityRequest.ProtoReflect.Descriptor instead.
func (*GetEntityRequest) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{10}
}

func (x *GetEntityRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

// GetEntityResponse
type GetEntityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entity type
	EntityType common.EntityType `protobuf:"varint,1,opt,name=entity_type,json=entityType,proto3,enum=cloud9.common.EntityType" json:"entity_type,omitempty"`
	// Person data (if entity is a person)
	Person *EntityPerson `protobuf:"bytes,2,opt,name=person,proto3" json:"person,omitempty"`
	// Business data (if entity is a business)
	Business      *EntityBusiness `protobuf:"bytes,3,opt,name=business,proto3" json:"business,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityResponse) Reset() {
	*x = GetEntityResponse{}
	mi := &file_entities_entities_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityResponse) ProtoMessage() {}

func (x *GetEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityResponse.ProtoReflect.Descriptor instead.
func (*GetEntityResponse) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{11}
}

func (x *GetEntityResponse) GetEntityType() common.EntityType {
	if x != nil {
		return x.EntityType
	}
	return common.EntityType(0)
}

func (x *GetEntityResponse) GetPerson() *EntityPerson {
	if x != nil {
		return x.Person
	}
	return nil
}

func (x *GetEntityResponse) GetBusiness() *EntityBusiness {
	if x != nil {
		return x.Business
	}
	return nil
}

// EntityExistsRequest is used to check if an entity exists by ID, phone number, or email
type EntityExistsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*EntityExistsRequest_EntityId
	//	*EntityExistsRequest_PhoneNumber
	//	*EntityExistsRequest_Email
	Identifier    isEntityExistsRequest_Identifier `protobuf_oneof:"identifier"`
	EntityType    common.EntityType                `protobuf:"varint,4,opt,name=entity_type,json=entityType,proto3,enum=cloud9.common.EntityType" json:"entity_type,omitempty"` // required when using phone_number/email; ignored for entity_id
	IncludeEntity bool                             `protobuf:"varint,5,opt,name=include_entity,json=includeEntity,proto3" json:"include_entity,omitempty"`                      // if false, response omits person/business payload (cheaper)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityExistsRequest) Reset() {
	*x = EntityExistsRequest{}
	mi := &file_entities_entities_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityExistsRequest) ProtoMessage() {}

func (x *EntityExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityExistsRequest.ProtoReflect.Descriptor instead.
func (*EntityExistsRequest) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{12}
}

func (x *EntityExistsRequest) GetIdentifier() isEntityExistsRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *EntityExistsRequest) GetEntityId() string {
	if x != nil {
		if x, ok := x.Identifier.(*EntityExistsRequest_EntityId); ok {
			return x.EntityId
		}
	}
	return ""
}

func (x *EntityExistsRequest) GetPhoneNumber() string {
	if x != nil {
		if x, ok := x.Identifier.(*EntityExistsRequest_PhoneNumber); ok {
			return x.PhoneNumber
		}
	}
	return ""
}

func (x *EntityExistsRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Identifier.(*EntityExistsRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *EntityExistsRequest) GetEntityType() common.EntityType {
	if x != nil {
		return x.EntityType
	}
	return common.EntityType(0)
}

func (x *EntityExistsRequest) GetIncludeEntity() bool {
	if x != nil {
		return x.IncludeEntity
	}
	return false
}

type isEntityExistsRequest_Identifier interface {
	isEntityExistsRequest_Identifier()
}

type EntityExistsRequest_EntityId struct {
	EntityId string `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3,oneof"`
}

type EntityExistsRequest_PhoneNumber struct {
	PhoneNumber string `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3,oneof"`
}

type EntityExistsRequest_Email struct {
	Email string `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

func (*EntityExistsRequest_EntityId) isEntityExistsRequest_Identifier() {}

func (*EntityExistsRequest_PhoneNumber) isEntityExistsRequest_Identifier() {}

func (*EntityExistsRequest_Email) isEntityExistsRequest_Identifier() {}

type EntityExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	EntityType    common.EntityType      `protobuf:"varint,2,opt,name=entity_type,json=entityType,proto3,enum=cloud9.common.EntityType" json:"entity_type,omitempty"` // type of the matched entity, if found
	Person        *EntityPerson          `protobuf:"bytes,3,opt,name=person,proto3" json:"person,omitempty"`                                                          // set only if exists && type==PERSON && include_entity
	Business      *EntityBusiness        `protobuf:"bytes,4,opt,name=business,proto3" json:"business,omitempty"`                                                      // set only if exists && type==BUSINESS && include_entity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityExistsResponse) Reset() {
	*x = EntityExistsResponse{}
	mi := &file_entities_entities_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityExistsResponse) ProtoMessage() {}

func (x *EntityExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityExistsResponse.ProtoReflect.Descriptor instead.
func (*EntityExistsResponse) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{13}
}

func (x *EntityExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *EntityExistsResponse) GetEntityType() common.EntityType {
	if x != nil {
		return x.EntityType
	}
	return common.EntityType(0)
}

func (x *EntityExistsResponse) GetPerson() *EntityPerson {
	if x != nil {
		return x.Person
	}
	return nil
}

func (x *EntityExistsResponse) GetBusiness() *EntityBusiness {
	if x != nil {
		return x.Business
	}
	return nil
}

var File_entities_entities_proto protoreflect.FileDescriptor

const file_entities_entities_proto_rawDesc = "" +
	"\n" +
	"\x17entities/entities.proto\x12\x0fcloud9.entities\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19common/entity_types.proto\"\x99\x03\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.cloud9.common.EntityTypeR\x04type\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x17\n" +
	"\atax_pin\x18\x06 \x01(\tR\x06taxPin\x12\x1d\n" +
	"\n" +
	"kyc_status\x18\a \x01(\tR\tkycStatus\x12\x1b\n" +
	"\tkyc_level\x18\v \x01(\x05R\bkycLevel\x122\n" +
	"\aaddress\x18\b \x01(\v2\x18.cloud9.entities.AddressR\aaddress\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9a\x01\n" +
	"\aAddress\x12\x14\n" +
	"\x05line1\x18\x01 \x01(\tR\x05line1\x12\x14\n" +
	"\x05line2\x18\x02 \x01(\tR\x05line2\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x1f\n" +
	"\vpostal_code\x18\x06 \x01(\tR\n" +
	"postalCode\"\xdb\x04\n" +
	"\fEntityPerson\x12/\n" +
	"\x06entity\x18\x01 \x01(\v2\x17.cloud9.entities.EntityR\x06entity\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1f\n" +
	"\vmiddle_name\x18\x04 \x01(\tR\n" +
	"middleName\x12.\n" +
	"\aid_type\x18\x05 \x01(\x0e2\x15.cloud9.common.IDTypeR\x06idType\x12\x1b\n" +
	"\tid_number\x18\x06 \x01(\tR\bidNumber\x12\"\n" +
	"\rdate_of_birth\x18\a \x01(\tR\vdateOfBirth\x12-\n" +
	"\x06gender\x18\b \x01(\x0e2\x15.cloud9.common.GenderR\x06gender\x12L\n" +
	"\x11employment_status\x18\t \x01(\x0e2\x1f.cloud9.common.EmploymentStatusR\x10employmentStatus\x12A\n" +
	"\x0emonthly_income\x18\n" +
	" \x01(\x0e2\x1a.cloud9.common.IncomeRangeR\rmonthlyIncome\x12D\n" +
	"\x0fsource_of_funds\x18\v \x01(\x0e2\x1c.cloud9.common.SourceOfFundsR\rsourceOfFunds\x12F\n" +
	"\x0faccount_purpose\x18\f \x01(\x0e2\x1d.cloud9.common.AccountPurposeR\x0eaccountPurpose\"\x89\x03\n" +
	"\x0eEntityBusiness\x12/\n" +
	"\x06entity\x18\x01 \x01(\v2\x17.cloud9.entities.EntityR\x06entity\x12#\n" +
	"\rbusiness_type\x18\x02 \x01(\tR\fbusinessType\x12.\n" +
	"\x13business_legal_name\x18\x03 \x01(\tR\x11businessLegalName\x12/\n" +
	"\x13registration_number\x18\x04 \x01(\tR\x12registrationNumber\x12\x1a\n" +
	"\bindustry\x18\x05 \x01(\tR\bindustry\x12)\n" +
	"\x10specify_industry\x18\x06 \x01(\tR\x0fspecifyIndustry\x12\x1c\n" +
	"\tdirectors\x18\a \x03(\tR\tdirectors\x12%\n" +
	"\x0eoperating_mode\x18\b \x01(\x05R\roperatingMode\x124\n" +
	"\x16specify_operating_mode\x18\t \x01(\tR\x14specifyOperatingMode\"\x87\x05\n" +
	"\x10BusinessDirector\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1f\n" +
	"\vmiddle_name\x18\x04 \x01(\tR\n" +
	"middleName\x12\x17\n" +
	"\aid_type\x18\x05 \x01(\tR\x06idType\x12\x1b\n" +
	"\tid_number\x18\x06 \x01(\tR\bidNumber\x12\"\n" +
	"\rdate_of_birth\x18\a \x01(\tR\vdateOfBirth\x12 \n" +
	"\vnationality\x18\b \x01(\tR\vnationality\x12!\n" +
	"\fphone_number\x18\t \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\n" +
	" \x01(\tR\x05email\x12\x16\n" +
	"\x06gender\x18\v \x01(\tR\x06gender\x12\x17\n" +
	"\akra_pin\x18\f \x01(\tR\x06kraPin\x12%\n" +
	"\x0fid_front_doc_id\x18\r \x01(\tR\fidFrontDocId\x12#\n" +
	"\x0eid_back_doc_id\x18\x0e \x01(\tR\vidBackDocId\x12\"\n" +
	"\rselfie_doc_id\x18\x0f \x01(\tR\vselfieDocId\x12#\n" +
	"\x0ekra_pin_doc_id\x18\x10 \x01(\tR\vkraPinDocId\x12\x12\n" +
	"\x04role\x18\x11 \x01(\tR\x04role\x12\"\n" +
	"\rkin_full_name\x18\x12 \x01(\tR\vkinFullName\x12)\n" +
	"\x10kin_relationship\x18\x13 \x01(\tR\x0fkinRelationship\x12(\n" +
	"\x10kin_phone_number\x18\x14 \x01(\tR\x0ekinPhoneNumber\"\xc1\x02\n" +
	"\x0eLLCShareholder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12!\n" +
	"\fcompany_name\x18\x03 \x01(\tR\vcompanyName\x12%\n" +
	"\x0freg_cert_doc_id\x18\x04 \x01(\tR\fregCertDocId\x12\x1c\n" +
	"\n" +
	"ubo_doc_id\x18\x05 \x01(\tR\buboDocId\x12\x1c\n" +
	"\n" +
	"coi_doc_id\x18\x06 \x01(\tR\bcoiDocId\x12\x1e\n" +
	"\vcr12_doc_id\x18\a \x01(\tR\tcr12DocId\x125\n" +
	"\x17board_resolution_doc_id\x18\b \x01(\tR\x14boardResolutionDocId\x12%\n" +
	"\x0fkra_cert_doc_id\x18\t \x01(\tR\fkraCertDocId\"9\n" +
	"\x1aListLLCShareholdersRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\"b\n" +
	"\x1bListLLCShareholdersResponse\x12C\n" +
	"\fshareholders\x18\x01 \x03(\v2\x1f.cloud9.entities.LLCShareholderR\fshareholders\":\n" +
	"\x1bGetBusinessDirectorsRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\"_\n" +
	"\x1cGetBusinessDirectorsResponse\x12?\n" +
	"\tdirectors\x18\x01 \x03(\v2!.cloud9.entities.BusinessDirectorR\tdirectors\"/\n" +
	"\x10GetEntityRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\"\xc3\x01\n" +
	"\x11GetEntityResponse\x12:\n" +
	"\ventity_type\x18\x01 \x01(\x0e2\x19.cloud9.common.EntityTypeR\n" +
	"entityType\x125\n" +
	"\x06person\x18\x02 \x01(\v2\x1d.cloud9.entities.EntityPersonR\x06person\x12;\n" +
	"\bbusiness\x18\x03 \x01(\v2\x1f.cloud9.entities.EntityBusinessR\bbusiness\"\xe2\x01\n" +
	"\x13EntityExistsRequest\x12\x1d\n" +
	"\tentity_id\x18\x01 \x01(\tH\x00R\bentityId\x12#\n" +
	"\fphone_number\x18\x02 \x01(\tH\x00R\vphoneNumber\x12\x16\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05email\x12:\n" +
	"\ventity_type\x18\x04 \x01(\x0e2\x19.cloud9.common.EntityTypeR\n" +
	"entityType\x12%\n" +
	"\x0einclude_entity\x18\x05 \x01(\bR\rincludeEntityB\f\n" +
	"\n" +
	"identifier\"\xde\x01\n" +
	"\x14EntityExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12:\n" +
	"\ventity_type\x18\x02 \x01(\x0e2\x19.cloud9.common.EntityTypeR\n" +
	"entityType\x125\n" +
	"\x06person\x18\x03 \x01(\v2\x1d.cloud9.entities.EntityPersonR\x06person\x12;\n" +
	"\bbusiness\x18\x04 \x01(\v2\x1f.cloud9.entities.EntityBusinessR\bbusiness2\xa7\x03\n" +
	"\rEntityService\x12R\n" +
	"\tGetEntity\x12!.cloud9.entities.GetEntityRequest\x1a\".cloud9.entities.GetEntityResponse\x12s\n" +
	"\x14GetBusinessDirectors\x12,.cloud9.entities.GetBusinessDirectorsRequest\x1a-.cloud9.entities.GetBusinessDirectorsResponse\x12p\n" +
	"\x13ListLLCShareholders\x12+.cloud9.entities.ListLLCShareholdersRequest\x1a,.cloud9.entities.ListLLCShareholdersResponse\x12[\n" +
	"\fEntityExists\x12$.cloud9.entities.EntityExistsRequest\x1a%.cloud9.entities.EntityExistsResponseB=Z;github.com/Cloud9Money/api-protos/proto/entities;entitiespbb\x06proto3"

var (
	file_entities_entities_proto_rawDescOnce sync.Once
	file_entities_entities_proto_rawDescData []byte
)

func file_entities_entities_proto_rawDescGZIP() []byte {
	file_entities_entities_proto_rawDescOnce.Do(func() {
		file_entities_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_entities_proto_rawDesc), len(file_entities_entities_proto_rawDesc)))
	})
	return file_entities_entities_proto_rawDescData
}

var file_entities_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_entities_entities_proto_goTypes = []any{
	(*Entity)(nil),                       // 0: cloud9.entities.Entity
	(*Address)(nil),                      // 1: cloud9.entities.Address
	(*EntityPerson)(nil),                 // 2: cloud9.entities.EntityPerson
	(*EntityBusiness)(nil),               // 3: cloud9.entities.EntityBusiness
	(*BusinessDirector)(nil),             // 4: cloud9.entities.BusinessDirector
	(*LLCShareholder)(nil),               // 5: cloud9.entities.LLCShareholder
	(*ListLLCShareholdersRequest)(nil),   // 6: cloud9.entities.ListLLCShareholdersRequest
	(*ListLLCShareholdersResponse)(nil),  // 7: cloud9.entities.ListLLCShareholdersResponse
	(*GetBusinessDirectorsRequest)(nil),  // 8: cloud9.entities.GetBusinessDirectorsRequest
	(*GetBusinessDirectorsResponse)(nil), // 9: cloud9.entities.GetBusinessDirectorsResponse
	(*GetEntityRequest)(nil),             // 10: cloud9.entities.GetEntityRequest
	(*GetEntityResponse)(nil),            // 11: cloud9.entities.GetEntityResponse
	(*EntityExistsRequest)(nil),          // 12: cloud9.entities.EntityExistsRequest
	(*EntityExistsResponse)(nil),         // 13: cloud9.entities.EntityExistsResponse
	(common.EntityType)(0),               // 14: cloud9.common.EntityType
	(*timestamppb.Timestamp)(nil),        // 15: google.protobuf.Timestamp
	(common.IDType)(0),                   // 16: cloud9.common.IDType
	(common.Gender)(0),                   // 17: cloud9.common.Gender
	(common.EmploymentStatus)(0),         // 18: cloud9.common.EmploymentStatus
	(common.IncomeRange)(0),              // 19: cloud9.common.IncomeRange
	(common.SourceOfFunds)(0),            // 20: cloud9.common.SourceOfFunds
	(common.AccountPurpose)(0),           // 21: cloud9.common.AccountPurpose
}
var file_entities_entities_proto_depIdxs = []int32{
	14, // 0: cloud9.entities.Entity.type:type_name -> cloud9.common.EntityType
	1,  // 1: cloud9.entities.Entity.address:type_name -> cloud9.entities.Address
	15, // 2: cloud9.entities.Entity.created_at:type_name -> google.protobuf.Timestamp
	15, // 3: cloud9.entities.Entity.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: cloud9.entities.EntityPerson.entity:type_name -> cloud9.entities.Entity
	16, // 5: cloud9.entities.EntityPerson.id_type:type_name -> cloud9.common.IDType
	17, // 6: cloud9.entities.EntityPerson.gender:type_name -> cloud9.common.Gender
	18, // 7: cloud9.entities.EntityPerson.employment_status:type_name -> cloud9.common.EmploymentStatus
	19, // 8: cloud9.entities.EntityPerson.monthly_income:type_name -> cloud9.common.IncomeRange
	20, // 9: cloud9.entities.EntityPerson.source_of_funds:type_name -> cloud9.common.SourceOfFunds
	21, // 10: cloud9.entities.EntityPerson.account_purpose:type_name -> cloud9.common.AccountPurpose
	0,  // 11: cloud9.entities.EntityBusiness.entity:type_name -> cloud9.entities.Entity
	5,  // 12: cloud9.entities.ListLLCShareholdersResponse.shareholders:type_name -> cloud9.entities.LLCShareholder
	4,  // 13: cloud9.entities.GetBusinessDirectorsResponse.directors:type_name -> cloud9.entities.BusinessDirector
	14, // 14: cloud9.entities.GetEntityResponse.entity_type:type_name -> cloud9.common.EntityType
	2,  // 15: cloud9.entities.GetEntityResponse.person:type_name -> cloud9.entities.EntityPerson
	3,  // 16: cloud9.entities.GetEntityResponse.business:type_name -> cloud9.entities.EntityBusiness
	14, // 17: cloud9.entities.EntityExistsRequest.entity_type:type_name -> cloud9.common.EntityType
	14, // 18: cloud9.entities.EntityExistsResponse.entity_type:type_name -> cloud9.common.EntityType
	2,  // 19: cloud9.entities.EntityExistsResponse.person:type_name -> cloud9.entities.EntityPerson
	3,  // 20: cloud9.entities.EntityExistsResponse.business:type_name -> cloud9.entities.EntityBusiness
	10, // 21: cloud9.entities.EntityService.GetEntity:input_type -> cloud9.entities.GetEntityRequest
	8,  // 22: cloud9.entities.EntityService.GetBusinessDirectors:input_type -> cloud9.entities.GetBusinessDirectorsRequest
	6,  // 23: cloud9.entities.EntityService.ListLLCShareholders:input_type -> cloud9.entities.ListLLCShareholdersRequest
	12, // 24: cloud9.entities.EntityService.EntityExists:input_type -> cloud9.entities.EntityExistsRequest
	11, // 25: cloud9.entities.EntityService.GetEntity:output_type -> cloud9.entities.GetEntityResponse
	9,  // 26: cloud9.entities.EntityService.GetBusinessDirectors:output_type -> cloud9.entities.GetBusinessDirectorsResponse
	7,  // 27: cloud9.entities.EntityService.ListLLCShareholders:output_type -> cloud9.entities.ListLLCShareholdersResponse
	13, // 28: cloud9.entities.EntityService.EntityExists:output_type -> cloud9.entities.EntityExistsResponse
	25, // [25:29] is the sub-list for method output_type
	21, // [21:25] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_entities_entities_proto_init() }
func file_entities_entities_proto_init() {
	if File_entities_entities_proto != nil {
		return
	}
	file_entities_entities_proto_msgTypes[12].OneofWrappers = []any{
		(*EntityExistsRequest_EntityId)(nil),
		(*EntityExistsRequest_PhoneNumber)(nil),
		(*EntityExistsRequest_Email)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_entities_proto_rawDesc), len(file_entities_entities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_entities_entities_proto_goTypes,
		DependencyIndexes: file_entities_entities_proto_depIdxs,
		MessageInfos:      file_entities_entities_proto_msgTypes,
	}.Build()
	File_entities_entities_proto = out.File
	file_entities_entities_proto_goTypes = nil
	file_entities_entities_proto_depIdxs = nil
}
