// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: virtual_accounts/virtual_accounts.proto

package virtualaccountspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVirtualAccountDepositInstructionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVirtualAccountDepositInstructionsRequest) Reset() {
	*x = GetVirtualAccountDepositInstructionsRequest{}
	mi := &file_virtual_accounts_virtual_accounts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVirtualAccountDepositInstructionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVirtualAccountDepositInstructionsRequest) ProtoMessage() {}

func (x *GetVirtualAccountDepositInstructionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_virtual_accounts_virtual_accounts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVirtualAccountDepositInstructionsRequest.ProtoReflect.Descriptor instead.
func (*GetVirtualAccountDepositInstructionsRequest) Descriptor() ([]byte, []int) {
	return file_virtual_accounts_virtual_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *GetVirtualAccountDepositInstructionsRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *GetVirtualAccountDepositInstructionsRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetVirtualAccountDepositInstructionsResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	VirtualAccountId       string                 `protobuf:"bytes,1,opt,name=virtual_account_id,json=virtualAccountId,proto3" json:"virtual_account_id,omitempty"`
	Currency               string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	BankName               string                 `protobuf:"bytes,3,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	BankAddress            string                 `protobuf:"bytes,4,opt,name=bank_address,json=bankAddress,proto3" json:"bank_address,omitempty"`
	BankRoutingNumber      string                 `protobuf:"bytes,5,opt,name=bank_routing_number,json=bankRoutingNumber,proto3" json:"bank_routing_number,omitempty"`
	BankAccountNumber      string                 `protobuf:"bytes,6,opt,name=bank_account_number,json=bankAccountNumber,proto3" json:"bank_account_number,omitempty"`
	BankBeneficiaryName    string                 `protobuf:"bytes,7,opt,name=bank_beneficiary_name,json=bankBeneficiaryName,proto3" json:"bank_beneficiary_name,omitempty"`
	BankBeneficiaryAddress string                 `protobuf:"bytes,8,opt,name=bank_beneficiary_address,json=bankBeneficiaryAddress,proto3" json:"bank_beneficiary_address,omitempty"`
	PaymentRails           []string               `protobuf:"bytes,9,rep,name=payment_rails,json=paymentRails,proto3" json:"payment_rails,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetVirtualAccountDepositInstructionsResponse) Reset() {
	*x = GetVirtualAccountDepositInstructionsResponse{}
	mi := &file_virtual_accounts_virtual_accounts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVirtualAccountDepositInstructionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVirtualAccountDepositInstructionsResponse) ProtoMessage() {}

func (x *GetVirtualAccountDepositInstructionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_virtual_accounts_virtual_accounts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVirtualAccountDepositInstructionsResponse.ProtoReflect.Descriptor instead.
func (*GetVirtualAccountDepositInstructionsResponse) Descriptor() ([]byte, []int) {
	return file_virtual_accounts_virtual_accounts_proto_rawDescGZIP(), []int{1}
}

func (x *GetVirtualAccountDepositInstructionsResponse) GetVirtualAccountId() string {
	if x != nil {
		return x.VirtualAccountId
	}
	return ""
}

func (x *GetVirtualAccountDepositInstructionsResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetVirtualAccountDepositInstructionsResponse) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *GetVirtualAccountDepositInstructionsResponse) GetBankAddress() string {
	if x != nil {
		return x.BankAddress
	}
	return ""
}

func (x *GetVirtualAccountDepositInstructionsResponse) GetBankRoutingNumber() string {
	if x != nil {
		return x.BankRoutingNumber
	}
	return ""
}

func (x *GetVirtualAccountDepositInstructionsResponse) GetBankAccountNumber() string {
	if x != nil {
		return x.BankAccountNumber
	}
	return ""
}

func (x *GetVirtualAccountDepositInstructionsResponse) GetBankBeneficiaryName() string {
	if x != nil {
		return x.BankBeneficiaryName
	}
	return ""
}

func (x *GetVirtualAccountDepositInstructionsResponse) GetBankBeneficiaryAddress() string {
	if x != nil {
		return x.BankBeneficiaryAddress
	}
	return ""
}

func (x *GetVirtualAccountDepositInstructionsResponse) GetPaymentRails() []string {
	if x != nil {
		return x.PaymentRails
	}
	return nil
}

var File_virtual_accounts_virtual_accounts_proto protoreflect.FileDescriptor

const file_virtual_accounts_virtual_accounts_proto_rawDesc = "" +
	"\n" +
	"'virtual_accounts/virtual_accounts.proto\x12\x17cloud9.virtual_accounts\"f\n" +
	"+GetVirtualAccountDepositInstructionsRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xab\x03\n" +
	",GetVirtualAccountDepositInstructionsResponse\x12,\n" +
	"\x12virtual_account_id\x18\x01 \x01(\tR\x10virtualAccountId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x1b\n" +
	"\tbank_name\x18\x03 \x01(\tR\bbankName\x12!\n" +
	"\fbank_address\x18\x04 \x01(\tR\vbankAddress\x12.\n" +
	"\x13bank_routing_number\x18\x05 \x01(\tR\x11bankRoutingNumber\x12.\n" +
	"\x13bank_account_number\x18\x06 \x01(\tR\x11bankAccountNumber\x122\n" +
	"\x15bank_beneficiary_name\x18\a \x01(\tR\x13bankBeneficiaryName\x128\n" +
	"\x18bank_beneficiary_address\x18\b \x01(\tR\x16bankBeneficiaryAddress\x12#\n" +
	"\rpayment_rails\x18\t \x03(\tR\fpaymentRails2\xcd\x01\n" +
	"\x15VirtualAccountService\x12\xb3\x01\n" +
	"$GetVirtualAccountDepositInstructions\x12D.cloud9.virtual_accounts.GetVirtualAccountDepositInstructionsRequest\x1aE.cloud9.virtual_accounts.GetVirtualAccountDepositInstructionsResponseBLZJgithub.com/Cloud9Money/api-protos/proto/virtual_accounts;virtualaccountspbb\x06proto3"

var (
	file_virtual_accounts_virtual_accounts_proto_rawDescOnce sync.Once
	file_virtual_accounts_virtual_accounts_proto_rawDescData []byte
)

func file_virtual_accounts_virtual_accounts_proto_rawDescGZIP() []byte {
	file_virtual_accounts_virtual_accounts_proto_rawDescOnce.Do(func() {
		file_virtual_accounts_virtual_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_virtual_accounts_virtual_accounts_proto_rawDesc), len(file_virtual_accounts_virtual_accounts_proto_rawDesc)))
	})
	return file_virtual_accounts_virtual_accounts_proto_rawDescData
}

var file_virtual_accounts_virtual_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_virtual_accounts_virtual_accounts_proto_goTypes = []any{
	(*GetVirtualAccountDepositInstructionsRequest)(nil),  // 0: cloud9.virtual_accounts.GetVirtualAccountDepositInstructionsRequest
	(*GetVirtualAccountDepositInstructionsResponse)(nil), // 1: cloud9.virtual_accounts.GetVirtualAccountDepositInstructionsResponse
}
var file_virtual_accounts_virtual_accounts_proto_depIdxs = []int32{
	0, // 0: cloud9.virtual_accounts.VirtualAccountService.GetVirtualAccountDepositInstructions:input_type -> cloud9.virtual_accounts.GetVirtualAccountDepositInstructionsRequest
	1, // 1: cloud9.virtual_accounts.VirtualAccountService.GetVirtualAccountDepositInstructions:output_type -> cloud9.virtual_accounts.GetVirtualAccountDepositInstructionsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_virtual_accounts_virtual_accounts_proto_init() }
func file_virtual_accounts_virtual_accounts_proto_init() {
	if File_virtual_accounts_virtual_accounts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_virtual_accounts_virtual_accounts_proto_rawDesc), len(file_virtual_accounts_virtual_accounts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_virtual_accounts_virtual_accounts_proto_goTypes,
		DependencyIndexes: file_virtual_accounts_virtual_accounts_proto_depIdxs,
		MessageInfos:      file_virtual_accounts_virtual_accounts_proto_msgTypes,
	}.Build()
	File_virtual_accounts_virtual_accounts_proto = out.File
	file_virtual_accounts_virtual_accounts_proto_goTypes = nil
	file_virtual_accounts_virtual_accounts_proto_depIdxs = nil
}
