// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: transactions/transactions.proto

package transactionspb

import (
	common "github.com/cloud9/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransactionType categorizes transactions
type TransactionType int32

const (
	TransactionType_TRANSACTION_TYPE_UNSPECIFIED      TransactionType = 0
	TransactionType_TRANSACTION_TYPE_DEPOSIT          TransactionType = 1
	TransactionType_TRANSACTION_TYPE_WITHDRAWAL       TransactionType = 2
	TransactionType_TRANSACTION_TYPE_TRANSFER         TransactionType = 3
	TransactionType_TRANSACTION_TYPE_MPESA_DEPOSIT    TransactionType = 4
	TransactionType_TRANSACTION_TYPE_MPESA_WITHDRAWAL TransactionType = 5
	TransactionType_TRANSACTION_TYPE_CARD_PAYMENT     TransactionType = 6
	TransactionType_TRANSACTION_TYPE_REFUND           TransactionType = 7
	TransactionType_TRANSACTION_TYPE_FEE              TransactionType = 8
	TransactionType_TRANSACTION_TYPE_INTEREST         TransactionType = 9
	TransactionType_TRANSACTION_TYPE_REVERSAL         TransactionType = 10
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0:  "TRANSACTION_TYPE_UNSPECIFIED",
		1:  "TRANSACTION_TYPE_DEPOSIT",
		2:  "TRANSACTION_TYPE_WITHDRAWAL",
		3:  "TRANSACTION_TYPE_TRANSFER",
		4:  "TRANSACTION_TYPE_MPESA_DEPOSIT",
		5:  "TRANSACTION_TYPE_MPESA_WITHDRAWAL",
		6:  "TRANSACTION_TYPE_CARD_PAYMENT",
		7:  "TRANSACTION_TYPE_REFUND",
		8:  "TRANSACTION_TYPE_FEE",
		9:  "TRANSACTION_TYPE_INTEREST",
		10: "TRANSACTION_TYPE_REVERSAL",
	}
	TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_UNSPECIFIED":      0,
		"TRANSACTION_TYPE_DEPOSIT":          1,
		"TRANSACTION_TYPE_WITHDRAWAL":       2,
		"TRANSACTION_TYPE_TRANSFER":         3,
		"TRANSACTION_TYPE_MPESA_DEPOSIT":    4,
		"TRANSACTION_TYPE_MPESA_WITHDRAWAL": 5,
		"TRANSACTION_TYPE_CARD_PAYMENT":     6,
		"TRANSACTION_TYPE_REFUND":           7,
		"TRANSACTION_TYPE_FEE":              8,
		"TRANSACTION_TYPE_INTEREST":         9,
		"TRANSACTION_TYPE_REVERSAL":         10,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_transactions_transactions_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_transactions_transactions_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{0}
}

// TransactionStatus represents transaction state
type TransactionStatus int32

const (
	TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED TransactionStatus = 0
	TransactionStatus_TRANSACTION_STATUS_PENDING     TransactionStatus = 1
	TransactionStatus_TRANSACTION_STATUS_PROCESSING  TransactionStatus = 2
	TransactionStatus_TRANSACTION_STATUS_COMPLETED   TransactionStatus = 3
	TransactionStatus_TRANSACTION_STATUS_FAILED      TransactionStatus = 4
	TransactionStatus_TRANSACTION_STATUS_REVERSED    TransactionStatus = 5
	TransactionStatus_TRANSACTION_STATUS_CANCELLED   TransactionStatus = 6
)

// Enum value maps for TransactionStatus.
var (
	TransactionStatus_name = map[int32]string{
		0: "TRANSACTION_STATUS_UNSPECIFIED",
		1: "TRANSACTION_STATUS_PENDING",
		2: "TRANSACTION_STATUS_PROCESSING",
		3: "TRANSACTION_STATUS_COMPLETED",
		4: "TRANSACTION_STATUS_FAILED",
		5: "TRANSACTION_STATUS_REVERSED",
		6: "TRANSACTION_STATUS_CANCELLED",
	}
	TransactionStatus_value = map[string]int32{
		"TRANSACTION_STATUS_UNSPECIFIED": 0,
		"TRANSACTION_STATUS_PENDING":     1,
		"TRANSACTION_STATUS_PROCESSING":  2,
		"TRANSACTION_STATUS_COMPLETED":   3,
		"TRANSACTION_STATUS_FAILED":      4,
		"TRANSACTION_STATUS_REVERSED":    5,
		"TRANSACTION_STATUS_CANCELLED":   6,
	}
)

func (x TransactionStatus) Enum() *TransactionStatus {
	p := new(TransactionStatus)
	*p = x
	return p
}

func (x TransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_transactions_transactions_proto_enumTypes[1].Descriptor()
}

func (TransactionStatus) Type() protoreflect.EnumType {
	return &file_transactions_transactions_proto_enumTypes[1]
}

func (x TransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus.Descriptor instead.
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{1}
}

// TransferType categorizes transfers
type TransferType int32

const (
	TransferType_TRANSFER_TYPE_UNSPECIFIED   TransferType = 0
	TransferType_TRANSFER_TYPE_INTERNAL      TransferType = 1 // Within same bank
	TransferType_TRANSFER_TYPE_DOMESTIC      TransferType = 2 // Within same country
	TransferType_TRANSFER_TYPE_INTERNATIONAL TransferType = 3 // Cross-border
	TransferType_TRANSFER_TYPE_MOBILE_MONEY  TransferType = 4 // To mobile money
)

// Enum value maps for TransferType.
var (
	TransferType_name = map[int32]string{
		0: "TRANSFER_TYPE_UNSPECIFIED",
		1: "TRANSFER_TYPE_INTERNAL",
		2: "TRANSFER_TYPE_DOMESTIC",
		3: "TRANSFER_TYPE_INTERNATIONAL",
		4: "TRANSFER_TYPE_MOBILE_MONEY",
	}
	TransferType_value = map[string]int32{
		"TRANSFER_TYPE_UNSPECIFIED":   0,
		"TRANSFER_TYPE_INTERNAL":      1,
		"TRANSFER_TYPE_DOMESTIC":      2,
		"TRANSFER_TYPE_INTERNATIONAL": 3,
		"TRANSFER_TYPE_MOBILE_MONEY":  4,
	}
)

func (x TransferType) Enum() *TransferType {
	p := new(TransferType)
	*p = x
	return p
}

func (x TransferType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferType) Descriptor() protoreflect.EnumDescriptor {
	return file_transactions_transactions_proto_enumTypes[2].Descriptor()
}

func (TransferType) Type() protoreflect.EnumType {
	return &file_transactions_transactions_proto_enumTypes[2]
}

func (x TransferType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferType.Descriptor instead.
func (TransferType) EnumDescriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{2}
}

// BulkTransferStatus
type BulkTransferStatus int32

const (
	BulkTransferStatus_BULK_TRANSFER_STATUS_UNSPECIFIED BulkTransferStatus = 0
	BulkTransferStatus_BULK_TRANSFER_STATUS_PENDING     BulkTransferStatus = 1
	BulkTransferStatus_BULK_TRANSFER_STATUS_PROCESSING  BulkTransferStatus = 2
	BulkTransferStatus_BULK_TRANSFER_STATUS_COMPLETED   BulkTransferStatus = 3
	BulkTransferStatus_BULK_TRANSFER_STATUS_PARTIAL     BulkTransferStatus = 4 // Some failed
	BulkTransferStatus_BULK_TRANSFER_STATUS_FAILED      BulkTransferStatus = 5
)

// Enum value maps for BulkTransferStatus.
var (
	BulkTransferStatus_name = map[int32]string{
		0: "BULK_TRANSFER_STATUS_UNSPECIFIED",
		1: "BULK_TRANSFER_STATUS_PENDING",
		2: "BULK_TRANSFER_STATUS_PROCESSING",
		3: "BULK_TRANSFER_STATUS_COMPLETED",
		4: "BULK_TRANSFER_STATUS_PARTIAL",
		5: "BULK_TRANSFER_STATUS_FAILED",
	}
	BulkTransferStatus_value = map[string]int32{
		"BULK_TRANSFER_STATUS_UNSPECIFIED": 0,
		"BULK_TRANSFER_STATUS_PENDING":     1,
		"BULK_TRANSFER_STATUS_PROCESSING":  2,
		"BULK_TRANSFER_STATUS_COMPLETED":   3,
		"BULK_TRANSFER_STATUS_PARTIAL":     4,
		"BULK_TRANSFER_STATUS_FAILED":      5,
	}
)

func (x BulkTransferStatus) Enum() *BulkTransferStatus {
	p := new(BulkTransferStatus)
	*p = x
	return p
}

func (x BulkTransferStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BulkTransferStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_transactions_transactions_proto_enumTypes[3].Descriptor()
}

func (BulkTransferStatus) Type() protoreflect.EnumType {
	return &file_transactions_transactions_proto_enumTypes[3]
}

func (x BulkTransferStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BulkTransferStatus.Descriptor instead.
func (BulkTransferStatus) EnumDescriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{3}
}

// Transaction represents a financial transaction
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata
	Metadata *common.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Transaction reference (unique)
	Reference string `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	// Transaction type
	Type TransactionType `protobuf:"varint,3,opt,name=type,proto3,enum=cloud9.transactions.TransactionType" json:"type,omitempty"`
	// Transaction status
	Status TransactionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=cloud9.transactions.TransactionStatus" json:"status,omitempty"`
	// Source account ID
	SourceAccountId string `protobuf:"bytes,5,opt,name=source_account_id,json=sourceAccountId,proto3" json:"source_account_id,omitempty"`
	// Destination account ID (for transfers)
	DestinationAccountId string `protobuf:"bytes,6,opt,name=destination_account_id,json=destinationAccountId,proto3" json:"destination_account_id,omitempty"`
	// Amount
	Amount *common.Money `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	// Fee (if applicable)
	Fee *common.Money `protobuf:"bytes,8,opt,name=fee,proto3" json:"fee,omitempty"`
	// Total amount (amount + fee)
	TotalAmount *common.Money `protobuf:"bytes,9,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	// Currency
	Currency string `protobuf:"bytes,10,opt,name=currency,proto3" json:"currency,omitempty"`
	// Description
	Description string `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	// Initiated by user ID
	InitiatedBy string `protobuf:"bytes,12,opt,name=initiated_by,json=initiatedBy,proto3" json:"initiated_by,omitempty"`
	// Jurisdiction
	Jurisdiction common.Jurisdiction `protobuf:"varint,13,opt,name=jurisdiction,proto3,enum=cloud9.common.Jurisdiction" json:"jurisdiction,omitempty"`
	// Provider (choice_bank, woodcore, mpesa)
	Provider string `protobuf:"bytes,14,opt,name=provider,proto3" json:"provider,omitempty"`
	// Provider transaction ID
	ProviderTransactionId string `protobuf:"bytes,15,opt,name=provider_transaction_id,json=providerTransactionId,proto3" json:"provider_transaction_id,omitempty"`
	// Processing timestamps
	InitiatedAt *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=initiated_at,json=initiatedAt,proto3" json:"initiated_at,omitempty"`
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	FailedAt    *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	// Failure reason (if failed)
	FailureReason string `protobuf:"bytes,19,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	// Idempotency key
	IdempotencyKey string `protobuf:"bytes,20,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Additional metadata
	MetadataExtra map[string]string `protobuf:"bytes,21,rep,name=metadata_extra,json=metadataExtra,proto3" json:"metadata_extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_transactions_transactions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_transactions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Transaction) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *Transaction) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *Transaction) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *Transaction) GetSourceAccountId() string {
	if x != nil {
		return x.SourceAccountId
	}
	return ""
}

func (x *Transaction) GetDestinationAccountId() string {
	if x != nil {
		return x.DestinationAccountId
	}
	return ""
}

func (x *Transaction) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Transaction) GetFee() *common.Money {
	if x != nil {
		return x.Fee
	}
	return nil
}

func (x *Transaction) GetTotalAmount() *common.Money {
	if x != nil {
		return x.TotalAmount
	}
	return nil
}

func (x *Transaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transaction) GetInitiatedBy() string {
	if x != nil {
		return x.InitiatedBy
	}
	return ""
}

func (x *Transaction) GetJurisdiction() common.Jurisdiction {
	if x != nil {
		return x.Jurisdiction
	}
	return common.Jurisdiction(0)
}

func (x *Transaction) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Transaction) GetProviderTransactionId() string {
	if x != nil {
		return x.ProviderTransactionId
	}
	return ""
}

func (x *Transaction) GetInitiatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InitiatedAt
	}
	return nil
}

func (x *Transaction) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Transaction) GetFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FailedAt
	}
	return nil
}

func (x *Transaction) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *Transaction) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Transaction) GetMetadataExtra() map[string]string {
	if x != nil {
		return x.MetadataExtra
	}
	return nil
}

// CreateTransactionRequest
type CreateTransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transaction type
	Type TransactionType `protobuf:"varint,1,opt,name=type,proto3,enum=cloud9.transactions.TransactionType" json:"type,omitempty"`
	// Source account ID
	SourceAccountId string `protobuf:"bytes,2,opt,name=source_account_id,json=sourceAccountId,proto3" json:"source_account_id,omitempty"`
	// Destination account ID (for transfers)
	DestinationAccountId string `protobuf:"bytes,3,opt,name=destination_account_id,json=destinationAccountId,proto3" json:"destination_account_id,omitempty"`
	// Amount
	Amount *common.Money `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// Description
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Idempotency key (required)
	IdempotencyKey string `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Metadata
	Metadata      map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_transactions_transactions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_transactions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransactionRequest) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *CreateTransactionRequest) GetSourceAccountId() string {
	if x != nil {
		return x.SourceAccountId
	}
	return ""
}

func (x *CreateTransactionRequest) GetDestinationAccountId() string {
	if x != nil {
		return x.DestinationAccountId
	}
	return ""
}

func (x *CreateTransactionRequest) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreateTransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTransactionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateTransactionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CreateTransactionResponse
type CreateTransactionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created transaction
	Transaction   *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_transactions_transactions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_transactions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// GetTransactionRequest
type GetTransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transaction ID or reference
	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_transactions_transactions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_transactions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// GetTransactionResponse
type GetTransactionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transaction details
	Transaction   *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_transactions_transactions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_transactions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// ListTransactionsRequest
type ListTransactionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account ID filter
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Type filter
	Type TransactionType `protobuf:"varint,2,opt,name=type,proto3,enum=cloud9.transactions.TransactionType" json:"type,omitempty"`
	// Status filter
	Status TransactionStatus `protobuf:"varint,3,opt,name=status,proto3,enum=cloud9.transactions.TransactionStatus" json:"status,omitempty"`
	// Start date
	StartDate *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	// End date
	EndDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	// Pagination
	Pagination    *common.PaginationRequest `protobuf:"bytes,6,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_transactions_transactions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_transactions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{5}
}

func (x *ListTransactionsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListTransactionsRequest) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *ListTransactionsRequest) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *ListTransactionsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ListTransactionsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *ListTransactionsRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// ListTransactionsResponse
type ListTransactionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of transactions
	Transactions []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	// Pagination metadata
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_transactions_transactions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_transactions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{6}
}

func (x *ListTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListTransactionsResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// MpesaDeposit represents M-Pesa deposit details
type MpesaDeposit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Phone number in E.164 format
	PhoneNumber string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// Amount
	Amount *common.Money `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// Account number
	AccountNumber string `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	// Transaction reference
	TransactionReference string `protobuf:"bytes,4,opt,name=transaction_reference,json=transactionReference,proto3" json:"transaction_reference,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MpesaDeposit) Reset() {
	*x = MpesaDeposit{}
	mi := &file_transactions_transactions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MpesaDeposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpesaDeposit) ProtoMessage() {}

func (x *MpesaDeposit) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_transactions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpesaDeposit.ProtoReflect.Descriptor instead.
func (*MpesaDeposit) Descriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{7}
}

func (x *MpesaDeposit) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *MpesaDeposit) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *MpesaDeposit) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *MpesaDeposit) GetTransactionReference() string {
	if x != nil {
		return x.TransactionReference
	}
	return ""
}

// MpesaWithdrawal represents M-Pesa withdrawal details
type MpesaWithdrawal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Phone number in E.164 format
	PhoneNumber string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// Amount
	Amount *common.Money `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// Account number
	AccountNumber string `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MpesaWithdrawal) Reset() {
	*x = MpesaWithdrawal{}
	mi := &file_transactions_transactions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MpesaWithdrawal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpesaWithdrawal) ProtoMessage() {}

func (x *MpesaWithdrawal) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_transactions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpesaWithdrawal.ProtoReflect.Descriptor instead.
func (*MpesaWithdrawal) Descriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{8}
}

func (x *MpesaWithdrawal) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *MpesaWithdrawal) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *MpesaWithdrawal) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

// Transfer represents a transfer between accounts
type Transfer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source account ID
	SourceAccountId string `protobuf:"bytes,1,opt,name=source_account_id,json=sourceAccountId,proto3" json:"source_account_id,omitempty"`
	// Destination account ID
	DestinationAccountId string `protobuf:"bytes,2,opt,name=destination_account_id,json=destinationAccountId,proto3" json:"destination_account_id,omitempty"`
	// Amount
	Amount *common.Money `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// Description
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Transfer type
	TransferType  TransferType `protobuf:"varint,5,opt,name=transfer_type,json=transferType,proto3,enum=cloud9.transactions.TransferType" json:"transfer_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_transactions_transactions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_transactions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{9}
}

func (x *Transfer) GetSourceAccountId() string {
	if x != nil {
		return x.SourceAccountId
	}
	return ""
}

func (x *Transfer) GetDestinationAccountId() string {
	if x != nil {
		return x.DestinationAccountId
	}
	return ""
}

func (x *Transfer) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Transfer) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transfer) GetTransferType() TransferType {
	if x != nil {
		return x.TransferType
	}
	return TransferType_TRANSFER_TYPE_UNSPECIFIED
}

// BulkTransfer represents a batch of transfers
type BulkTransfer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Batch ID
	BatchId string `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	// Source account ID
	SourceAccountId string `protobuf:"bytes,2,opt,name=source_account_id,json=sourceAccountId,proto3" json:"source_account_id,omitempty"`
	// List of transfers
	Transfers []*Transfer `protobuf:"bytes,3,rep,name=transfers,proto3" json:"transfers,omitempty"`
	// Total amount
	TotalAmount *common.Money `protobuf:"bytes,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	// Status
	Status BulkTransferStatus `protobuf:"varint,5,opt,name=status,proto3,enum=cloud9.transactions.BulkTransferStatus" json:"status,omitempty"`
	// Progress (number of completed transfers)
	CompletedCount int32 `protobuf:"varint,6,opt,name=completed_count,json=completedCount,proto3" json:"completed_count,omitempty"`
	// Total transfers in batch
	TotalCount    int32 `protobuf:"varint,7,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkTransfer) Reset() {
	*x = BulkTransfer{}
	mi := &file_transactions_transactions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkTransfer) ProtoMessage() {}

func (x *BulkTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_transactions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkTransfer.ProtoReflect.Descriptor instead.
func (*BulkTransfer) Descriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{10}
}

func (x *BulkTransfer) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BulkTransfer) GetSourceAccountId() string {
	if x != nil {
		return x.SourceAccountId
	}
	return ""
}

func (x *BulkTransfer) GetTransfers() []*Transfer {
	if x != nil {
		return x.Transfers
	}
	return nil
}

func (x *BulkTransfer) GetTotalAmount() *common.Money {
	if x != nil {
		return x.TotalAmount
	}
	return nil
}

func (x *BulkTransfer) GetStatus() BulkTransferStatus {
	if x != nil {
		return x.Status
	}
	return BulkTransferStatus_BULK_TRANSFER_STATUS_UNSPECIFIED
}

func (x *BulkTransfer) GetCompletedCount() int32 {
	if x != nil {
		return x.CompletedCount
	}
	return 0
}

func (x *BulkTransfer) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_transactions_transactions_proto protoreflect.FileDescriptor

const file_transactions_transactions_proto_rawDesc = "" +
	"\n" +
	"\x1ftransactions/transactions.proto\x12\x13cloud9.transactions\x1a\x13common/common.proto\x1a\x12common/money.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe6\b\n" +
	"\vTransaction\x123\n" +
	"\bmetadata\x18\x01 \x01(\v2\x17.cloud9.common.MetadataR\bmetadata\x12\x1c\n" +
	"\treference\x18\x02 \x01(\tR\treference\x128\n" +
	"\x04type\x18\x03 \x01(\x0e2$.cloud9.transactions.TransactionTypeR\x04type\x12>\n" +
	"\x06status\x18\x04 \x01(\x0e2&.cloud9.transactions.TransactionStatusR\x06status\x12*\n" +
	"\x11source_account_id\x18\x05 \x01(\tR\x0fsourceAccountId\x124\n" +
	"\x16destination_account_id\x18\x06 \x01(\tR\x14destinationAccountId\x12,\n" +
	"\x06amount\x18\a \x01(\v2\x14.cloud9.common.MoneyR\x06amount\x12&\n" +
	"\x03fee\x18\b \x01(\v2\x14.cloud9.common.MoneyR\x03fee\x127\n" +
	"\ftotal_amount\x18\t \x01(\v2\x14.cloud9.common.MoneyR\vtotalAmount\x12\x1a\n" +
	"\bcurrency\x18\n" +
	" \x01(\tR\bcurrency\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x12!\n" +
	"\finitiated_by\x18\f \x01(\tR\vinitiatedBy\x12?\n" +
	"\fjurisdiction\x18\r \x01(\x0e2\x1b.cloud9.common.JurisdictionR\fjurisdiction\x12\x1a\n" +
	"\bprovider\x18\x0e \x01(\tR\bprovider\x126\n" +
	"\x17provider_transaction_id\x18\x0f \x01(\tR\x15providerTransactionId\x12=\n" +
	"\finitiated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\vinitiatedAt\x12=\n" +
	"\fcompleted_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x127\n" +
	"\tfailed_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\bfailedAt\x12%\n" +
	"\x0efailure_reason\x18\x13 \x01(\tR\rfailureReason\x12'\n" +
	"\x0fidempotency_key\x18\x14 \x01(\tR\x0eidempotencyKey\x12Z\n" +
	"\x0emetadata_extra\x18\x15 \x03(\v23.cloud9.transactions.Transaction.MetadataExtraEntryR\rmetadataExtra\x1a@\n" +
	"\x12MetadataExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc5\x03\n" +
	"\x18CreateTransactionRequest\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.cloud9.transactions.TransactionTypeR\x04type\x12*\n" +
	"\x11source_account_id\x18\x02 \x01(\tR\x0fsourceAccountId\x124\n" +
	"\x16destination_account_id\x18\x03 \x01(\tR\x14destinationAccountId\x12,\n" +
	"\x06amount\x18\x04 \x01(\v2\x14.cloud9.common.MoneyR\x06amount\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x12W\n" +
	"\bmetadata\x18\a \x03(\v2;.cloud9.transactions.CreateTransactionRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\x19CreateTransactionResponse\x12B\n" +
	"\vtransaction\x18\x01 \x01(\v2 .cloud9.transactions.TransactionR\vtransaction\">\n" +
	"\x15GetTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"\\\n" +
	"\x16GetTransactionResponse\x12B\n" +
	"\vtransaction\x18\x01 \x01(\v2 .cloud9.transactions.TransactionR\vtransaction\"\xe6\x02\n" +
	"\x17ListTransactionsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x128\n" +
	"\x04type\x18\x02 \x01(\x0e2$.cloud9.transactions.TransactionTypeR\x04type\x12>\n" +
	"\x06status\x18\x03 \x01(\x0e2&.cloud9.transactions.TransactionStatusR\x06status\x129\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12@\n" +
	"\n" +
	"pagination\x18\x06 \x01(\v2 .cloud9.common.PaginationRequestR\n" +
	"pagination\"\xa3\x01\n" +
	"\x18ListTransactionsResponse\x12D\n" +
	"\ftransactions\x18\x01 \x03(\v2 .cloud9.transactions.TransactionR\ftransactions\x12A\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2!.cloud9.common.PaginationResponseR\n" +
	"pagination\"\xbb\x01\n" +
	"\fMpesaDeposit\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12,\n" +
	"\x06amount\x18\x02 \x01(\v2\x14.cloud9.common.MoneyR\x06amount\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\x123\n" +
	"\x15transaction_reference\x18\x04 \x01(\tR\x14transactionReference\"\x89\x01\n" +
	"\x0fMpesaWithdrawal\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12,\n" +
	"\x06amount\x18\x02 \x01(\v2\x14.cloud9.common.MoneyR\x06amount\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\"\x84\x02\n" +
	"\bTransfer\x12*\n" +
	"\x11source_account_id\x18\x01 \x01(\tR\x0fsourceAccountId\x124\n" +
	"\x16destination_account_id\x18\x02 \x01(\tR\x14destinationAccountId\x12,\n" +
	"\x06amount\x18\x03 \x01(\v2\x14.cloud9.common.MoneyR\x06amount\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12F\n" +
	"\rtransfer_type\x18\x05 \x01(\x0e2!.cloud9.transactions.TransferTypeR\ftransferType\"\xd6\x02\n" +
	"\fBulkTransfer\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12*\n" +
	"\x11source_account_id\x18\x02 \x01(\tR\x0fsourceAccountId\x12;\n" +
	"\ttransfers\x18\x03 \x03(\v2\x1d.cloud9.transactions.TransferR\ttransfers\x127\n" +
	"\ftotal_amount\x18\x04 \x01(\v2\x14.cloud9.common.MoneyR\vtotalAmount\x12?\n" +
	"\x06status\x18\x05 \x01(\x0e2'.cloud9.transactions.BulkTransferStatusR\x06status\x12'\n" +
	"\x0fcompleted_count\x18\x06 \x01(\x05R\x0ecompletedCount\x12\x1f\n" +
	"\vtotal_count\x18\a \x01(\x05R\n" +
	"totalCount*\xf4\x02\n" +
	"\x0fTransactionType\x12 \n" +
	"\x1cTRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TRANSACTION_TYPE_DEPOSIT\x10\x01\x12\x1f\n" +
	"\x1bTRANSACTION_TYPE_WITHDRAWAL\x10\x02\x12\x1d\n" +
	"\x19TRANSACTION_TYPE_TRANSFER\x10\x03\x12\"\n" +
	"\x1eTRANSACTION_TYPE_MPESA_DEPOSIT\x10\x04\x12%\n" +
	"!TRANSACTION_TYPE_MPESA_WITHDRAWAL\x10\x05\x12!\n" +
	"\x1dTRANSACTION_TYPE_CARD_PAYMENT\x10\x06\x12\x1b\n" +
	"\x17TRANSACTION_TYPE_REFUND\x10\a\x12\x18\n" +
	"\x14TRANSACTION_TYPE_FEE\x10\b\x12\x1d\n" +
	"\x19TRANSACTION_TYPE_INTEREST\x10\t\x12\x1d\n" +
	"\x19TRANSACTION_TYPE_REVERSAL\x10\n" +
	"*\xfe\x01\n" +
	"\x11TransactionStatus\x12\"\n" +
	"\x1eTRANSACTION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_PENDING\x10\x01\x12!\n" +
	"\x1dTRANSACTION_STATUS_PROCESSING\x10\x02\x12 \n" +
	"\x1cTRANSACTION_STATUS_COMPLETED\x10\x03\x12\x1d\n" +
	"\x19TRANSACTION_STATUS_FAILED\x10\x04\x12\x1f\n" +
	"\x1bTRANSACTION_STATUS_REVERSED\x10\x05\x12 \n" +
	"\x1cTRANSACTION_STATUS_CANCELLED\x10\x06*\xa6\x01\n" +
	"\fTransferType\x12\x1d\n" +
	"\x19TRANSFER_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TRANSFER_TYPE_INTERNAL\x10\x01\x12\x1a\n" +
	"\x16TRANSFER_TYPE_DOMESTIC\x10\x02\x12\x1f\n" +
	"\x1bTRANSFER_TYPE_INTERNATIONAL\x10\x03\x12\x1e\n" +
	"\x1aTRANSFER_TYPE_MOBILE_MONEY\x10\x04*\xe8\x01\n" +
	"\x12BulkTransferStatus\x12$\n" +
	" BULK_TRANSFER_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cBULK_TRANSFER_STATUS_PENDING\x10\x01\x12#\n" +
	"\x1fBULK_TRANSFER_STATUS_PROCESSING\x10\x02\x12\"\n" +
	"\x1eBULK_TRANSFER_STATUS_COMPLETED\x10\x03\x12 \n" +
	"\x1cBULK_TRANSFER_STATUS_PARTIAL\x10\x04\x12\x1f\n" +
	"\x1bBULK_TRANSFER_STATUS_FAILED\x10\x05B5Z3github.com/cloud9/proto/transactions;transactionspbb\x06proto3"

var (
	file_transactions_transactions_proto_rawDescOnce sync.Once
	file_transactions_transactions_proto_rawDescData []byte
)

func file_transactions_transactions_proto_rawDescGZIP() []byte {
	file_transactions_transactions_proto_rawDescOnce.Do(func() {
		file_transactions_transactions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transactions_transactions_proto_rawDesc), len(file_transactions_transactions_proto_rawDesc)))
	})
	return file_transactions_transactions_proto_rawDescData
}

var file_transactions_transactions_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_transactions_transactions_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_transactions_transactions_proto_goTypes = []any{
	(TransactionType)(0),              // 0: cloud9.transactions.TransactionType
	(TransactionStatus)(0),            // 1: cloud9.transactions.TransactionStatus
	(TransferType)(0),                 // 2: cloud9.transactions.TransferType
	(BulkTransferStatus)(0),           // 3: cloud9.transactions.BulkTransferStatus
	(*Transaction)(nil),               // 4: cloud9.transactions.Transaction
	(*CreateTransactionRequest)(nil),  // 5: cloud9.transactions.CreateTransactionRequest
	(*CreateTransactionResponse)(nil), // 6: cloud9.transactions.CreateTransactionResponse
	(*GetTransactionRequest)(nil),     // 7: cloud9.transactions.GetTransactionRequest
	(*GetTransactionResponse)(nil),    // 8: cloud9.transactions.GetTransactionResponse
	(*ListTransactionsRequest)(nil),   // 9: cloud9.transactions.ListTransactionsRequest
	(*ListTransactionsResponse)(nil),  // 10: cloud9.transactions.ListTransactionsResponse
	(*MpesaDeposit)(nil),              // 11: cloud9.transactions.MpesaDeposit
	(*MpesaWithdrawal)(nil),           // 12: cloud9.transactions.MpesaWithdrawal
	(*Transfer)(nil),                  // 13: cloud9.transactions.Transfer
	(*BulkTransfer)(nil),              // 14: cloud9.transactions.BulkTransfer
	nil,                               // 15: cloud9.transactions.Transaction.MetadataExtraEntry
	nil,                               // 16: cloud9.transactions.CreateTransactionRequest.MetadataEntry
	(*common.Metadata)(nil),           // 17: cloud9.common.Metadata
	(*common.Money)(nil),              // 18: cloud9.common.Money
	(common.Jurisdiction)(0),          // 19: cloud9.common.Jurisdiction
	(*timestamppb.Timestamp)(nil),     // 20: google.protobuf.Timestamp
	(*common.PaginationRequest)(nil),  // 21: cloud9.common.PaginationRequest
	(*common.PaginationResponse)(nil), // 22: cloud9.common.PaginationResponse
}
var file_transactions_transactions_proto_depIdxs = []int32{
	17, // 0: cloud9.transactions.Transaction.metadata:type_name -> cloud9.common.Metadata
	0,  // 1: cloud9.transactions.Transaction.type:type_name -> cloud9.transactions.TransactionType
	1,  // 2: cloud9.transactions.Transaction.status:type_name -> cloud9.transactions.TransactionStatus
	18, // 3: cloud9.transactions.Transaction.amount:type_name -> cloud9.common.Money
	18, // 4: cloud9.transactions.Transaction.fee:type_name -> cloud9.common.Money
	18, // 5: cloud9.transactions.Transaction.total_amount:type_name -> cloud9.common.Money
	19, // 6: cloud9.transactions.Transaction.jurisdiction:type_name -> cloud9.common.Jurisdiction
	20, // 7: cloud9.transactions.Transaction.initiated_at:type_name -> google.protobuf.Timestamp
	20, // 8: cloud9.transactions.Transaction.completed_at:type_name -> google.protobuf.Timestamp
	20, // 9: cloud9.transactions.Transaction.failed_at:type_name -> google.protobuf.Timestamp
	15, // 10: cloud9.transactions.Transaction.metadata_extra:type_name -> cloud9.transactions.Transaction.MetadataExtraEntry
	0,  // 11: cloud9.transactions.CreateTransactionRequest.type:type_name -> cloud9.transactions.TransactionType
	18, // 12: cloud9.transactions.CreateTransactionRequest.amount:type_name -> cloud9.common.Money
	16, // 13: cloud9.transactions.CreateTransactionRequest.metadata:type_name -> cloud9.transactions.CreateTransactionRequest.MetadataEntry
	4,  // 14: cloud9.transactions.CreateTransactionResponse.transaction:type_name -> cloud9.transactions.Transaction
	4,  // 15: cloud9.transactions.GetTransactionResponse.transaction:type_name -> cloud9.transactions.Transaction
	0,  // 16: cloud9.transactions.ListTransactionsRequest.type:type_name -> cloud9.transactions.TransactionType
	1,  // 17: cloud9.transactions.ListTransactionsRequest.status:type_name -> cloud9.transactions.TransactionStatus
	20, // 18: cloud9.transactions.ListTransactionsRequest.start_date:type_name -> google.protobuf.Timestamp
	20, // 19: cloud9.transactions.ListTransactionsRequest.end_date:type_name -> google.protobuf.Timestamp
	21, // 20: cloud9.transactions.ListTransactionsRequest.pagination:type_name -> cloud9.common.PaginationRequest
	4,  // 21: cloud9.transactions.ListTransactionsResponse.transactions:type_name -> cloud9.transactions.Transaction
	22, // 22: cloud9.transactions.ListTransactionsResponse.pagination:type_name -> cloud9.common.PaginationResponse
	18, // 23: cloud9.transactions.MpesaDeposit.amount:type_name -> cloud9.common.Money
	18, // 24: cloud9.transactions.MpesaWithdrawal.amount:type_name -> cloud9.common.Money
	18, // 25: cloud9.transactions.Transfer.amount:type_name -> cloud9.common.Money
	2,  // 26: cloud9.transactions.Transfer.transfer_type:type_name -> cloud9.transactions.TransferType
	13, // 27: cloud9.transactions.BulkTransfer.transfers:type_name -> cloud9.transactions.Transfer
	18, // 28: cloud9.transactions.BulkTransfer.total_amount:type_name -> cloud9.common.Money
	3,  // 29: cloud9.transactions.BulkTransfer.status:type_name -> cloud9.transactions.BulkTransferStatus
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_transactions_transactions_proto_init() }
func file_transactions_transactions_proto_init() {
	if File_transactions_transactions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transactions_transactions_proto_rawDesc), len(file_transactions_transactions_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transactions_transactions_proto_goTypes,
		DependencyIndexes: file_transactions_transactions_proto_depIdxs,
		EnumInfos:         file_transactions_transactions_proto_enumTypes,
		MessageInfos:      file_transactions_transactions_proto_msgTypes,
	}.Build()
	File_transactions_transactions_proto = out.File
	file_transactions_transactions_proto_goTypes = nil
	file_transactions_transactions_proto_depIdxs = nil
}
