// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.27.3
// source: rohan/rohan.proto

package rohanpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HasActivePaymentSessionsRequest identifies the payee by their current cloud9 tag
type HasActivePaymentSessionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The cloud9 tag to check (e.g. "$alice")
	Cloud9Tag     string `protobuf:"bytes,1,opt,name=cloud9_tag,json=cloud9Tag,proto3" json:"cloud9_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasActivePaymentSessionsRequest) Reset() {
	*x = HasActivePaymentSessionsRequest{}
	mi := &file_rohan_rohan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasActivePaymentSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasActivePaymentSessionsRequest) ProtoMessage() {}

func (x *HasActivePaymentSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rohan_rohan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasActivePaymentSessionsRequest.ProtoReflect.Descriptor instead.
func (*HasActivePaymentSessionsRequest) Descriptor() ([]byte, []int) {
	return file_rohan_rohan_proto_rawDescGZIP(), []int{0}
}

func (x *HasActivePaymentSessionsRequest) GetCloud9Tag() string {
	if x != nil {
		return x.Cloud9Tag
	}
	return ""
}

// HasActivePaymentSessionsResponse reports whether active sessions exist
type HasActivePaymentSessionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if at least one session with status 'pending' or 'stk_sent' exists and has not expired
	HasActiveSessions bool `protobuf:"varint,1,opt,name=has_active_sessions,json=hasActiveSessions,proto3" json:"has_active_sessions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HasActivePaymentSessionsResponse) Reset() {
	*x = HasActivePaymentSessionsResponse{}
	mi := &file_rohan_rohan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasActivePaymentSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasActivePaymentSessionsResponse) ProtoMessage() {}

func (x *HasActivePaymentSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rohan_rohan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasActivePaymentSessionsResponse.ProtoReflect.Descriptor instead.
func (*HasActivePaymentSessionsResponse) Descriptor() ([]byte, []int) {
	return file_rohan_rohan_proto_rawDescGZIP(), []int{1}
}

func (x *HasActivePaymentSessionsResponse) GetHasActiveSessions() bool {
	if x != nil {
		return x.HasActiveSessions
	}
	return false
}

var File_rohan_rohan_proto protoreflect.FileDescriptor

var file_rohan_rohan_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x72, 0x6f, 0x68, 0x61, 0x6e, 0x2f, 0x72, 0x6f, 0x68, 0x61, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x39, 0x2e, 0x72, 0x6f, 0x68, 0x61,
	0x6e, 0x22, 0x40, 0x0a, 0x1f, 0x48, 0x61, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x39, 0x5f, 0x74,
	0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x39,
	0x54, 0x61, 0x67, 0x22, 0x52, 0x0a, 0x20, 0x48, 0x61, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x68, 0x61, 0x73, 0x5f, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x68, 0x61, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0x89, 0x01, 0x0a, 0x0c, 0x52, 0x6f, 0x68, 0x61,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x79, 0x0a, 0x18, 0x48, 0x61, 0x73, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2d, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x39, 0x2e, 0x72, 0x6f,
	0x68, 0x61, 0x6e, 0x2e, 0x48, 0x61, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x39, 0x2e, 0x72, 0x6f, 0x68,
	0x61, 0x6e, 0x2e, 0x48, 0x61, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x39, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x2f, 0x61, 0x70,
	0x69, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72,
	0x6f, 0x68, 0x61, 0x6e, 0x3b, 0x72, 0x6f, 0x68, 0x61, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_rohan_rohan_proto_rawDescOnce sync.Once
	file_rohan_rohan_proto_rawDescData []byte
)

func file_rohan_rohan_proto_rawDescGZIP() []byte {
	file_rohan_rohan_proto_rawDescOnce.Do(func() {
		file_rohan_rohan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rohan_rohan_proto_rawDesc), len(file_rohan_rohan_proto_rawDesc)))
	})
	return file_rohan_rohan_proto_rawDescData
}

var file_rohan_rohan_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rohan_rohan_proto_goTypes = []any{
	(*HasActivePaymentSessionsRequest)(nil),  // 0: cloud9.rohan.HasActivePaymentSessionsRequest
	(*HasActivePaymentSessionsResponse)(nil), // 1: cloud9.rohan.HasActivePaymentSessionsResponse
}
var file_rohan_rohan_proto_depIdxs = []int32{
	0, // 0: cloud9.rohan.RohanService.HasActivePaymentSessions:input_type -> cloud9.rohan.HasActivePaymentSessionsRequest
	1, // 1: cloud9.rohan.RohanService.HasActivePaymentSessions:output_type -> cloud9.rohan.HasActivePaymentSessionsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rohan_rohan_proto_init() }
func file_rohan_rohan_proto_init() {
	if File_rohan_rohan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rohan_rohan_proto_rawDesc), len(file_rohan_rohan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rohan_rohan_proto_goTypes,
		DependencyIndexes: file_rohan_rohan_proto_depIdxs,
		MessageInfos:      file_rohan_rohan_proto_msgTypes,
	}.Build()
	File_rohan_rohan_proto = out.File
	file_rohan_rohan_proto_goTypes = nil
	file_rohan_rohan_proto_depIdxs = nil
}
