// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: products/products.proto

package productspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductQuantity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      uint64                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductQuantity) Reset() {
	*x = ProductQuantity{}
	mi := &file_products_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductQuantity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductQuantity) ProtoMessage() {}

func (x *ProductQuantity) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductQuantity.ProtoReflect.Descriptor instead.
func (*ProductQuantity) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{0}
}

func (x *ProductQuantity) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductQuantity) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CheckoutProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariantId     string                 `protobuf:"bytes,2,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	Quantity      uint64                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutProduct) Reset() {
	*x = CheckoutProduct{}
	mi := &file_products_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutProduct) ProtoMessage() {}

func (x *CheckoutProduct) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutProduct.ProtoReflect.Descriptor instead.
func (*CheckoutProduct) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{1}
}

func (x *CheckoutProduct) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CheckoutProduct) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *CheckoutProduct) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CheckoutProduct) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_products_products_proto protoreflect.FileDescriptor

const file_products_products_proto_rawDesc = "" +
	"\n" +
	"\x17products/products.proto\x12\x0fcloud9.products\"L\n" +
	"\x0fProductQuantity\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x04R\bquantity\"\x81\x01\n" +
	"\x0fCheckoutProduct\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x02 \x01(\tR\tvariantId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x04R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05priceB=Z;github.com/Cloud9Money/api-protos/proto/products;productspbb\x06proto3"

var (
	file_products_products_proto_rawDescOnce sync.Once
	file_products_products_proto_rawDescData []byte
)

func file_products_products_proto_rawDescGZIP() []byte {
	file_products_products_proto_rawDescOnce.Do(func() {
		file_products_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_products_products_proto_rawDesc), len(file_products_products_proto_rawDesc)))
	})
	return file_products_products_proto_rawDescData
}

var file_products_products_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_products_products_proto_goTypes = []any{
	(*ProductQuantity)(nil), // 0: cloud9.products.ProductQuantity
	(*CheckoutProduct)(nil), // 1: cloud9.products.CheckoutProduct
}
var file_products_products_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_products_products_proto_init() }
func file_products_products_proto_init() {
	if File_products_products_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_products_products_proto_rawDesc), len(file_products_products_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_products_products_proto_goTypes,
		DependencyIndexes: file_products_products_proto_depIdxs,
		MessageInfos:      file_products_products_proto_msgTypes,
	}.Build()
	File_products_products_proto = out.File
	file_products_products_proto_goTypes = nil
	file_products_products_proto_depIdxs = nil
}
