// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: checkout/checkout.proto

package checkoutpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CheckoutService_Create_FullMethodName                          = "/cloud9.checkout.CheckoutService/Create"
	CheckoutService_Update_FullMethodName                          = "/cloud9.checkout.CheckoutService/Update"
	CheckoutService_UpdateStatus_FullMethodName                    = "/cloud9.checkout.CheckoutService/UpdateStatus"
	CheckoutService_GetById_FullMethodName                         = "/cloud9.checkout.CheckoutService/GetById"
	CheckoutService_CreateShopCheckout_FullMethodName              = "/cloud9.checkout.CheckoutService/CreateShopCheckout"
	CheckoutService_CreateWhatsappCheckout_FullMethodName          = "/cloud9.checkout.CheckoutService/CreateWhatsappCheckout"
	CheckoutService_GetCheckoutItems_FullMethodName                = "/cloud9.checkout.CheckoutService/GetCheckoutItems"
	CheckoutService_GetCheckoutStatus_FullMethodName               = "/cloud9.checkout.CheckoutService/GetCheckoutStatus"
	CheckoutService_UpdateWhatsappCheckout_FullMethodName          = "/cloud9.checkout.CheckoutService/UpdateWhatsappCheckout"
	CheckoutService_UpdateWhatsappCheckoutItems_FullMethodName     = "/cloud9.checkout.CheckoutService/UpdateWhatsappCheckoutItems"
	CheckoutService_SyncShopifyOrders_FullMethodName               = "/cloud9.checkout.CheckoutService/SyncShopifyOrders"
	CheckoutService_SyncShopifyDraftOrders_FullMethodName          = "/cloud9.checkout.CheckoutService/SyncShopifyDraftOrders"
	CheckoutService_CreateAICheckout_FullMethodName                = "/cloud9.checkout.CheckoutService/CreateAICheckout"
	CheckoutService_GetAICheckout_FullMethodName                   = "/cloud9.checkout.CheckoutService/GetAICheckout"
	CheckoutService_UpdateAICheckoutStatus_FullMethodName          = "/cloud9.checkout.CheckoutService/UpdateAICheckoutStatus"
	CheckoutService_UpdateCheckoutStatusToAbandoned_FullMethodName = "/cloud9.checkout.CheckoutService/UpdateCheckoutStatusToAbandoned"
	CheckoutService_UpdateOrCreateShopifyCheckout_FullMethodName   = "/cloud9.checkout.CheckoutService/UpdateOrCreateShopifyCheckout"
	CheckoutService_GetRecoveredCheckoutsCount_FullMethodName      = "/cloud9.checkout.CheckoutService/GetRecoveredCheckoutsCount"
	CheckoutService_GetSuccessfulCheckoutCount_FullMethodName      = "/cloud9.checkout.CheckoutService/GetSuccessfulCheckoutCount"
	CheckoutService_CreateSMBCheckout_FullMethodName               = "/cloud9.checkout.CheckoutService/CreateSMBCheckout"
)

// CheckoutServiceClient is the client API for CheckoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckoutServiceClient interface {
	Create(ctx context.Context, in *CreateUpdateCheckoutRequest, opts ...grpc.CallOption) (*Response, error)
	Update(ctx context.Context, in *CreateUpdateCheckoutRequest, opts ...grpc.CallOption) (*Response, error)
	UpdateStatus(ctx context.Context, in *UpdateCheckoutStatusRequest, opts ...grpc.CallOption) (*UpdateCheckoutStatusResponse, error)
	GetById(ctx context.Context, in *GetShopCheckoutRequest, opts ...grpc.CallOption) (*AnyObject, error)
	CreateShopCheckout(ctx context.Context, in *CreateShopCheckoutRequest, opts ...grpc.CallOption) (*AnyObject, error)
	CreateWhatsappCheckout(ctx context.Context, in *CreateWhatsappCheckoutRequest, opts ...grpc.CallOption) (*CreateWhatsappCheckoutResponse, error)
	GetCheckoutItems(ctx context.Context, in *GetCheckoutItemsRequest, opts ...grpc.CallOption) (*GetCheckoutItemsResponse, error)
	GetCheckoutStatus(ctx context.Context, in *GetCheckoutStatusRequest, opts ...grpc.CallOption) (*GetCheckoutStatusResponse, error)
	UpdateWhatsappCheckout(ctx context.Context, in *UpdateWhatsappCheckoutRequest, opts ...grpc.CallOption) (*UpdateWhatsappCheckoutResponse, error)
	UpdateWhatsappCheckoutItems(ctx context.Context, in *UpdateWhatsappCheckoutItemsRequest, opts ...grpc.CallOption) (*UpdateWhatsappCheckoutItemsResponse, error)
	SyncShopifyOrders(ctx context.Context, in *SyncShopifyOrdersRequest, opts ...grpc.CallOption) (*SyncShopifyOrdersResponse, error)
	SyncShopifyDraftOrders(ctx context.Context, in *SyncShopifyDraftOrdersRequest, opts ...grpc.CallOption) (*SyncShopifyDraftOrdersResponse, error)
	CreateAICheckout(ctx context.Context, in *CreateAICheckoutRequest, opts ...grpc.CallOption) (*CreateAICheckoutResponse, error)
	GetAICheckout(ctx context.Context, in *GetAICheckoutRequest, opts ...grpc.CallOption) (*AnyObject, error)
	UpdateAICheckoutStatus(ctx context.Context, in *UpdateAICheckoutStatusRequest, opts ...grpc.CallOption) (*UpdateAICheckoutStatusResponse, error)
	UpdateCheckoutStatusToAbandoned(ctx context.Context, in *UpdateCheckoutStatusToAbandonedRequest, opts ...grpc.CallOption) (*UpdateCheckoutStatusToAbandonedResponse, error)
	UpdateOrCreateShopifyCheckout(ctx context.Context, in *UpdateOrCreateShopifyCheckoutRequest, opts ...grpc.CallOption) (*UpdateOrCreateShopifyCheckoutResponse, error)
	GetRecoveredCheckoutsCount(ctx context.Context, in *GetRecoveredCheckoutsCountRequest, opts ...grpc.CallOption) (*GetRecoveredCheckoutsCountResponse, error)
	GetSuccessfulCheckoutCount(ctx context.Context, in *GetSuccessfulCheckoutCountRequest, opts ...grpc.CallOption) (*GetSuccessfulCheckoutCountResponse, error)
	CreateSMBCheckout(ctx context.Context, in *CreateSMBCheckoutRequest, opts ...grpc.CallOption) (*CreateSMBCheckoutResponse, error)
}

type checkoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckoutServiceClient(cc grpc.ClientConnInterface) CheckoutServiceClient {
	return &checkoutServiceClient{cc}
}

func (c *checkoutServiceClient) Create(ctx context.Context, in *CreateUpdateCheckoutRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, CheckoutService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) Update(ctx context.Context, in *CreateUpdateCheckoutRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, CheckoutService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) UpdateStatus(ctx context.Context, in *UpdateCheckoutStatusRequest, opts ...grpc.CallOption) (*UpdateCheckoutStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCheckoutStatusResponse)
	err := c.cc.Invoke(ctx, CheckoutService_UpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) GetById(ctx context.Context, in *GetShopCheckoutRequest, opts ...grpc.CallOption) (*AnyObject, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnyObject)
	err := c.cc.Invoke(ctx, CheckoutService_GetById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) CreateShopCheckout(ctx context.Context, in *CreateShopCheckoutRequest, opts ...grpc.CallOption) (*AnyObject, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnyObject)
	err := c.cc.Invoke(ctx, CheckoutService_CreateShopCheckout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) CreateWhatsappCheckout(ctx context.Context, in *CreateWhatsappCheckoutRequest, opts ...grpc.CallOption) (*CreateWhatsappCheckoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWhatsappCheckoutResponse)
	err := c.cc.Invoke(ctx, CheckoutService_CreateWhatsappCheckout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) GetCheckoutItems(ctx context.Context, in *GetCheckoutItemsRequest, opts ...grpc.CallOption) (*GetCheckoutItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCheckoutItemsResponse)
	err := c.cc.Invoke(ctx, CheckoutService_GetCheckoutItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) GetCheckoutStatus(ctx context.Context, in *GetCheckoutStatusRequest, opts ...grpc.CallOption) (*GetCheckoutStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCheckoutStatusResponse)
	err := c.cc.Invoke(ctx, CheckoutService_GetCheckoutStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) UpdateWhatsappCheckout(ctx context.Context, in *UpdateWhatsappCheckoutRequest, opts ...grpc.CallOption) (*UpdateWhatsappCheckoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWhatsappCheckoutResponse)
	err := c.cc.Invoke(ctx, CheckoutService_UpdateWhatsappCheckout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) UpdateWhatsappCheckoutItems(ctx context.Context, in *UpdateWhatsappCheckoutItemsRequest, opts ...grpc.CallOption) (*UpdateWhatsappCheckoutItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWhatsappCheckoutItemsResponse)
	err := c.cc.Invoke(ctx, CheckoutService_UpdateWhatsappCheckoutItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) SyncShopifyOrders(ctx context.Context, in *SyncShopifyOrdersRequest, opts ...grpc.CallOption) (*SyncShopifyOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncShopifyOrdersResponse)
	err := c.cc.Invoke(ctx, CheckoutService_SyncShopifyOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) SyncShopifyDraftOrders(ctx context.Context, in *SyncShopifyDraftOrdersRequest, opts ...grpc.CallOption) (*SyncShopifyDraftOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncShopifyDraftOrdersResponse)
	err := c.cc.Invoke(ctx, CheckoutService_SyncShopifyDraftOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) CreateAICheckout(ctx context.Context, in *CreateAICheckoutRequest, opts ...grpc.CallOption) (*CreateAICheckoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAICheckoutResponse)
	err := c.cc.Invoke(ctx, CheckoutService_CreateAICheckout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) GetAICheckout(ctx context.Context, in *GetAICheckoutRequest, opts ...grpc.CallOption) (*AnyObject, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnyObject)
	err := c.cc.Invoke(ctx, CheckoutService_GetAICheckout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) UpdateAICheckoutStatus(ctx context.Context, in *UpdateAICheckoutStatusRequest, opts ...grpc.CallOption) (*UpdateAICheckoutStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAICheckoutStatusResponse)
	err := c.cc.Invoke(ctx, CheckoutService_UpdateAICheckoutStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) UpdateCheckoutStatusToAbandoned(ctx context.Context, in *UpdateCheckoutStatusToAbandonedRequest, opts ...grpc.CallOption) (*UpdateCheckoutStatusToAbandonedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCheckoutStatusToAbandonedResponse)
	err := c.cc.Invoke(ctx, CheckoutService_UpdateCheckoutStatusToAbandoned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) UpdateOrCreateShopifyCheckout(ctx context.Context, in *UpdateOrCreateShopifyCheckoutRequest, opts ...grpc.CallOption) (*UpdateOrCreateShopifyCheckoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOrCreateShopifyCheckoutResponse)
	err := c.cc.Invoke(ctx, CheckoutService_UpdateOrCreateShopifyCheckout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) GetRecoveredCheckoutsCount(ctx context.Context, in *GetRecoveredCheckoutsCountRequest, opts ...grpc.CallOption) (*GetRecoveredCheckoutsCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecoveredCheckoutsCountResponse)
	err := c.cc.Invoke(ctx, CheckoutService_GetRecoveredCheckoutsCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) GetSuccessfulCheckoutCount(ctx context.Context, in *GetSuccessfulCheckoutCountRequest, opts ...grpc.CallOption) (*GetSuccessfulCheckoutCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSuccessfulCheckoutCountResponse)
	err := c.cc.Invoke(ctx, CheckoutService_GetSuccessfulCheckoutCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) CreateSMBCheckout(ctx context.Context, in *CreateSMBCheckoutRequest, opts ...grpc.CallOption) (*CreateSMBCheckoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSMBCheckoutResponse)
	err := c.cc.Invoke(ctx, CheckoutService_CreateSMBCheckout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckoutServiceServer is the server API for CheckoutService service.
// All implementations must embed UnimplementedCheckoutServiceServer
// for forward compatibility.
type CheckoutServiceServer interface {
	Create(context.Context, *CreateUpdateCheckoutRequest) (*Response, error)
	Update(context.Context, *CreateUpdateCheckoutRequest) (*Response, error)
	UpdateStatus(context.Context, *UpdateCheckoutStatusRequest) (*UpdateCheckoutStatusResponse, error)
	GetById(context.Context, *GetShopCheckoutRequest) (*AnyObject, error)
	CreateShopCheckout(context.Context, *CreateShopCheckoutRequest) (*AnyObject, error)
	CreateWhatsappCheckout(context.Context, *CreateWhatsappCheckoutRequest) (*CreateWhatsappCheckoutResponse, error)
	GetCheckoutItems(context.Context, *GetCheckoutItemsRequest) (*GetCheckoutItemsResponse, error)
	GetCheckoutStatus(context.Context, *GetCheckoutStatusRequest) (*GetCheckoutStatusResponse, error)
	UpdateWhatsappCheckout(context.Context, *UpdateWhatsappCheckoutRequest) (*UpdateWhatsappCheckoutResponse, error)
	UpdateWhatsappCheckoutItems(context.Context, *UpdateWhatsappCheckoutItemsRequest) (*UpdateWhatsappCheckoutItemsResponse, error)
	SyncShopifyOrders(context.Context, *SyncShopifyOrdersRequest) (*SyncShopifyOrdersResponse, error)
	SyncShopifyDraftOrders(context.Context, *SyncShopifyDraftOrdersRequest) (*SyncShopifyDraftOrdersResponse, error)
	CreateAICheckout(context.Context, *CreateAICheckoutRequest) (*CreateAICheckoutResponse, error)
	GetAICheckout(context.Context, *GetAICheckoutRequest) (*AnyObject, error)
	UpdateAICheckoutStatus(context.Context, *UpdateAICheckoutStatusRequest) (*UpdateAICheckoutStatusResponse, error)
	UpdateCheckoutStatusToAbandoned(context.Context, *UpdateCheckoutStatusToAbandonedRequest) (*UpdateCheckoutStatusToAbandonedResponse, error)
	UpdateOrCreateShopifyCheckout(context.Context, *UpdateOrCreateShopifyCheckoutRequest) (*UpdateOrCreateShopifyCheckoutResponse, error)
	GetRecoveredCheckoutsCount(context.Context, *GetRecoveredCheckoutsCountRequest) (*GetRecoveredCheckoutsCountResponse, error)
	GetSuccessfulCheckoutCount(context.Context, *GetSuccessfulCheckoutCountRequest) (*GetSuccessfulCheckoutCountResponse, error)
	CreateSMBCheckout(context.Context, *CreateSMBCheckoutRequest) (*CreateSMBCheckoutResponse, error)
	mustEmbedUnimplementedCheckoutServiceServer()
}

// UnimplementedCheckoutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCheckoutServiceServer struct{}

func (UnimplementedCheckoutServiceServer) Create(context.Context, *CreateUpdateCheckoutRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCheckoutServiceServer) Update(context.Context, *CreateUpdateCheckoutRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCheckoutServiceServer) UpdateStatus(context.Context, *UpdateCheckoutStatusRequest) (*UpdateCheckoutStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedCheckoutServiceServer) GetById(context.Context, *GetShopCheckoutRequest) (*AnyObject, error) {
	return nil, status.Error(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedCheckoutServiceServer) CreateShopCheckout(context.Context, *CreateShopCheckoutRequest) (*AnyObject, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShopCheckout not implemented")
}
func (UnimplementedCheckoutServiceServer) CreateWhatsappCheckout(context.Context, *CreateWhatsappCheckoutRequest) (*CreateWhatsappCheckoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWhatsappCheckout not implemented")
}
func (UnimplementedCheckoutServiceServer) GetCheckoutItems(context.Context, *GetCheckoutItemsRequest) (*GetCheckoutItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCheckoutItems not implemented")
}
func (UnimplementedCheckoutServiceServer) GetCheckoutStatus(context.Context, *GetCheckoutStatusRequest) (*GetCheckoutStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCheckoutStatus not implemented")
}
func (UnimplementedCheckoutServiceServer) UpdateWhatsappCheckout(context.Context, *UpdateWhatsappCheckoutRequest) (*UpdateWhatsappCheckoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWhatsappCheckout not implemented")
}
func (UnimplementedCheckoutServiceServer) UpdateWhatsappCheckoutItems(context.Context, *UpdateWhatsappCheckoutItemsRequest) (*UpdateWhatsappCheckoutItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWhatsappCheckoutItems not implemented")
}
func (UnimplementedCheckoutServiceServer) SyncShopifyOrders(context.Context, *SyncShopifyOrdersRequest) (*SyncShopifyOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncShopifyOrders not implemented")
}
func (UnimplementedCheckoutServiceServer) SyncShopifyDraftOrders(context.Context, *SyncShopifyDraftOrdersRequest) (*SyncShopifyDraftOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncShopifyDraftOrders not implemented")
}
func (UnimplementedCheckoutServiceServer) CreateAICheckout(context.Context, *CreateAICheckoutRequest) (*CreateAICheckoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAICheckout not implemented")
}
func (UnimplementedCheckoutServiceServer) GetAICheckout(context.Context, *GetAICheckoutRequest) (*AnyObject, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAICheckout not implemented")
}
func (UnimplementedCheckoutServiceServer) UpdateAICheckoutStatus(context.Context, *UpdateAICheckoutStatusRequest) (*UpdateAICheckoutStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAICheckoutStatus not implemented")
}
func (UnimplementedCheckoutServiceServer) UpdateCheckoutStatusToAbandoned(context.Context, *UpdateCheckoutStatusToAbandonedRequest) (*UpdateCheckoutStatusToAbandonedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCheckoutStatusToAbandoned not implemented")
}
func (UnimplementedCheckoutServiceServer) UpdateOrCreateShopifyCheckout(context.Context, *UpdateOrCreateShopifyCheckoutRequest) (*UpdateOrCreateShopifyCheckoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOrCreateShopifyCheckout not implemented")
}
func (UnimplementedCheckoutServiceServer) GetRecoveredCheckoutsCount(context.Context, *GetRecoveredCheckoutsCountRequest) (*GetRecoveredCheckoutsCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecoveredCheckoutsCount not implemented")
}
func (UnimplementedCheckoutServiceServer) GetSuccessfulCheckoutCount(context.Context, *GetSuccessfulCheckoutCountRequest) (*GetSuccessfulCheckoutCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSuccessfulCheckoutCount not implemented")
}
func (UnimplementedCheckoutServiceServer) CreateSMBCheckout(context.Context, *CreateSMBCheckoutRequest) (*CreateSMBCheckoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSMBCheckout not implemented")
}
func (UnimplementedCheckoutServiceServer) mustEmbedUnimplementedCheckoutServiceServer() {}
func (UnimplementedCheckoutServiceServer) testEmbeddedByValue()                         {}

// UnsafeCheckoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckoutServiceServer will
// result in compilation errors.
type UnsafeCheckoutServiceServer interface {
	mustEmbedUnimplementedCheckoutServiceServer()
}

func RegisterCheckoutServiceServer(s grpc.ServiceRegistrar, srv CheckoutServiceServer) {
	// If the following call panics, it indicates UnimplementedCheckoutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CheckoutService_ServiceDesc, srv)
}

func _CheckoutService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUpdateCheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).Create(ctx, req.(*CreateUpdateCheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUpdateCheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).Update(ctx, req.(*CreateUpdateCheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCheckoutStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_UpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).UpdateStatus(ctx, req.(*UpdateCheckoutStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopCheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).GetById(ctx, req.(*GetShopCheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_CreateShopCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShopCheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).CreateShopCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_CreateShopCheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).CreateShopCheckout(ctx, req.(*CreateShopCheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_CreateWhatsappCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWhatsappCheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).CreateWhatsappCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_CreateWhatsappCheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).CreateWhatsappCheckout(ctx, req.(*CreateWhatsappCheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_GetCheckoutItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckoutItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).GetCheckoutItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_GetCheckoutItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).GetCheckoutItems(ctx, req.(*GetCheckoutItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_GetCheckoutStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckoutStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).GetCheckoutStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_GetCheckoutStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).GetCheckoutStatus(ctx, req.(*GetCheckoutStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_UpdateWhatsappCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWhatsappCheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).UpdateWhatsappCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_UpdateWhatsappCheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).UpdateWhatsappCheckout(ctx, req.(*UpdateWhatsappCheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_UpdateWhatsappCheckoutItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWhatsappCheckoutItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).UpdateWhatsappCheckoutItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_UpdateWhatsappCheckoutItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).UpdateWhatsappCheckoutItems(ctx, req.(*UpdateWhatsappCheckoutItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_SyncShopifyOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncShopifyOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).SyncShopifyOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_SyncShopifyOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).SyncShopifyOrders(ctx, req.(*SyncShopifyOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_SyncShopifyDraftOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncShopifyDraftOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).SyncShopifyDraftOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_SyncShopifyDraftOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).SyncShopifyDraftOrders(ctx, req.(*SyncShopifyDraftOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_CreateAICheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAICheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).CreateAICheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_CreateAICheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).CreateAICheckout(ctx, req.(*CreateAICheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_GetAICheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAICheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).GetAICheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_GetAICheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).GetAICheckout(ctx, req.(*GetAICheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_UpdateAICheckoutStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAICheckoutStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).UpdateAICheckoutStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_UpdateAICheckoutStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).UpdateAICheckoutStatus(ctx, req.(*UpdateAICheckoutStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_UpdateCheckoutStatusToAbandoned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCheckoutStatusToAbandonedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).UpdateCheckoutStatusToAbandoned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_UpdateCheckoutStatusToAbandoned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).UpdateCheckoutStatusToAbandoned(ctx, req.(*UpdateCheckoutStatusToAbandonedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_UpdateOrCreateShopifyCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrCreateShopifyCheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).UpdateOrCreateShopifyCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_UpdateOrCreateShopifyCheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).UpdateOrCreateShopifyCheckout(ctx, req.(*UpdateOrCreateShopifyCheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_GetRecoveredCheckoutsCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecoveredCheckoutsCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).GetRecoveredCheckoutsCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_GetRecoveredCheckoutsCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).GetRecoveredCheckoutsCount(ctx, req.(*GetRecoveredCheckoutsCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_GetSuccessfulCheckoutCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSuccessfulCheckoutCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).GetSuccessfulCheckoutCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_GetSuccessfulCheckoutCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).GetSuccessfulCheckoutCount(ctx, req.(*GetSuccessfulCheckoutCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_CreateSMBCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSMBCheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).CreateSMBCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_CreateSMBCheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).CreateSMBCheckout(ctx, req.(*CreateSMBCheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckoutService_ServiceDesc is the grpc.ServiceDesc for CheckoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud9.checkout.CheckoutService",
	HandlerType: (*CheckoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CheckoutService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CheckoutService_Update_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _CheckoutService_UpdateStatus_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _CheckoutService_GetById_Handler,
		},
		{
			MethodName: "CreateShopCheckout",
			Handler:    _CheckoutService_CreateShopCheckout_Handler,
		},
		{
			MethodName: "CreateWhatsappCheckout",
			Handler:    _CheckoutService_CreateWhatsappCheckout_Handler,
		},
		{
			MethodName: "GetCheckoutItems",
			Handler:    _CheckoutService_GetCheckoutItems_Handler,
		},
		{
			MethodName: "GetCheckoutStatus",
			Handler:    _CheckoutService_GetCheckoutStatus_Handler,
		},
		{
			MethodName: "UpdateWhatsappCheckout",
			Handler:    _CheckoutService_UpdateWhatsappCheckout_Handler,
		},
		{
			MethodName: "UpdateWhatsappCheckoutItems",
			Handler:    _CheckoutService_UpdateWhatsappCheckoutItems_Handler,
		},
		{
			MethodName: "SyncShopifyOrders",
			Handler:    _CheckoutService_SyncShopifyOrders_Handler,
		},
		{
			MethodName: "SyncShopifyDraftOrders",
			Handler:    _CheckoutService_SyncShopifyDraftOrders_Handler,
		},
		{
			MethodName: "CreateAICheckout",
			Handler:    _CheckoutService_CreateAICheckout_Handler,
		},
		{
			MethodName: "GetAICheckout",
			Handler:    _CheckoutService_GetAICheckout_Handler,
		},
		{
			MethodName: "UpdateAICheckoutStatus",
			Handler:    _CheckoutService_UpdateAICheckoutStatus_Handler,
		},
		{
			MethodName: "UpdateCheckoutStatusToAbandoned",
			Handler:    _CheckoutService_UpdateCheckoutStatusToAbandoned_Handler,
		},
		{
			MethodName: "UpdateOrCreateShopifyCheckout",
			Handler:    _CheckoutService_UpdateOrCreateShopifyCheckout_Handler,
		},
		{
			MethodName: "GetRecoveredCheckoutsCount",
			Handler:    _CheckoutService_GetRecoveredCheckoutsCount_Handler,
		},
		{
			MethodName: "GetSuccessfulCheckoutCount",
			Handler:    _CheckoutService_GetSuccessfulCheckoutCount_Handler,
		},
		{
			MethodName: "CreateSMBCheckout",
			Handler:    _CheckoutService_CreateSMBCheckout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "checkout/checkout.proto",
}

const (
	CheckoutAnalyticsService_EntityContactAnalytics_FullMethodName                 = "/cloud9.checkout.CheckoutAnalyticsService/EntityContactAnalytics"
	CheckoutAnalyticsService_EntityProductSalesAnalytics_FullMethodName            = "/cloud9.checkout.CheckoutAnalyticsService/EntityProductSalesAnalytics"
	CheckoutAnalyticsService_CampaignCheckoutAnalytics_FullMethodName              = "/cloud9.checkout.CheckoutAnalyticsService/CampaignCheckoutAnalytics"
	CheckoutAnalyticsService_CampaignCheckoutTimeSeriesAnalytics_FullMethodName    = "/cloud9.checkout.CheckoutAnalyticsService/CampaignCheckoutTimeSeriesAnalytics"
	CheckoutAnalyticsService_CampaignRevenueAnalytics_FullMethodName               = "/cloud9.checkout.CheckoutAnalyticsService/CampaignRevenueAnalytics"
	CheckoutAnalyticsService_GetRevenueAnalyticsForCampaigns_FullMethodName        = "/cloud9.checkout.CheckoutAnalyticsService/GetRevenueAnalyticsForCampaigns"
	CheckoutAnalyticsService_CheckoutAnalyticsForCampaigns_FullMethodName          = "/cloud9.checkout.CheckoutAnalyticsService/CheckoutAnalyticsForCampaigns"
	CheckoutAnalyticsService_AverageRevenuePerContactAnalytics_FullMethodName      = "/cloud9.checkout.CheckoutAnalyticsService/AverageRevenuePerContactAnalytics"
	CheckoutAnalyticsService_AverageRevenuePerNoOfMessagesAnalytics_FullMethodName = "/cloud9.checkout.CheckoutAnalyticsService/AverageRevenuePerNoOfMessagesAnalytics"
)

// CheckoutAnalyticsServiceClient is the client API for CheckoutAnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckoutAnalyticsServiceClient interface {
	EntityContactAnalytics(ctx context.Context, in *EntityContactAnalyticsRequest, opts ...grpc.CallOption) (*EntityContactAnalyticsResponse, error)
	EntityProductSalesAnalytics(ctx context.Context, in *EntityProductSalesAnalyticsRequest, opts ...grpc.CallOption) (*EntityProductSalesAnalyticsResponse, error)
	CampaignCheckoutAnalytics(ctx context.Context, in *CampaignCheckoutAnalyticsRequest, opts ...grpc.CallOption) (*CampaignCheckoutAnalyticsResponse, error)
	CampaignCheckoutTimeSeriesAnalytics(ctx context.Context, in *CampaignCheckoutTimeSeriesAnalyticsRequest, opts ...grpc.CallOption) (*CampaignCheckoutTimeSeriesAnalyticsResponse, error)
	CampaignRevenueAnalytics(ctx context.Context, in *CampaignRevenueAnalyticsRequest, opts ...grpc.CallOption) (*CampaignRevenueAnalyticsResponse, error)
	GetRevenueAnalyticsForCampaigns(ctx context.Context, in *GetRevenueAnalyticsForCampaignsRequest, opts ...grpc.CallOption) (*GetRevenueAnalyticsForCampaignsResponse, error)
	CheckoutAnalyticsForCampaigns(ctx context.Context, in *CheckoutAnalyticsForCampaignsRequest, opts ...grpc.CallOption) (*CheckoutAnalyticsForCampaignsResponse, error)
	AverageRevenuePerContactAnalytics(ctx context.Context, in *AverageRevenuePerContactAnalyticsRequest, opts ...grpc.CallOption) (*AverageRevenuePerContactAnalyticsResponse, error)
	AverageRevenuePerNoOfMessagesAnalytics(ctx context.Context, in *AverageRevenuePerNoOfMessagesAnalyticsRequest, opts ...grpc.CallOption) (*AverageRevenuePerNoOfMessagesAnalyticsResponse, error)
}

type checkoutAnalyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckoutAnalyticsServiceClient(cc grpc.ClientConnInterface) CheckoutAnalyticsServiceClient {
	return &checkoutAnalyticsServiceClient{cc}
}

func (c *checkoutAnalyticsServiceClient) EntityContactAnalytics(ctx context.Context, in *EntityContactAnalyticsRequest, opts ...grpc.CallOption) (*EntityContactAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityContactAnalyticsResponse)
	err := c.cc.Invoke(ctx, CheckoutAnalyticsService_EntityContactAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutAnalyticsServiceClient) EntityProductSalesAnalytics(ctx context.Context, in *EntityProductSalesAnalyticsRequest, opts ...grpc.CallOption) (*EntityProductSalesAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityProductSalesAnalyticsResponse)
	err := c.cc.Invoke(ctx, CheckoutAnalyticsService_EntityProductSalesAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutAnalyticsServiceClient) CampaignCheckoutAnalytics(ctx context.Context, in *CampaignCheckoutAnalyticsRequest, opts ...grpc.CallOption) (*CampaignCheckoutAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CampaignCheckoutAnalyticsResponse)
	err := c.cc.Invoke(ctx, CheckoutAnalyticsService_CampaignCheckoutAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutAnalyticsServiceClient) CampaignCheckoutTimeSeriesAnalytics(ctx context.Context, in *CampaignCheckoutTimeSeriesAnalyticsRequest, opts ...grpc.CallOption) (*CampaignCheckoutTimeSeriesAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CampaignCheckoutTimeSeriesAnalyticsResponse)
	err := c.cc.Invoke(ctx, CheckoutAnalyticsService_CampaignCheckoutTimeSeriesAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutAnalyticsServiceClient) CampaignRevenueAnalytics(ctx context.Context, in *CampaignRevenueAnalyticsRequest, opts ...grpc.CallOption) (*CampaignRevenueAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CampaignRevenueAnalyticsResponse)
	err := c.cc.Invoke(ctx, CheckoutAnalyticsService_CampaignRevenueAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutAnalyticsServiceClient) GetRevenueAnalyticsForCampaigns(ctx context.Context, in *GetRevenueAnalyticsForCampaignsRequest, opts ...grpc.CallOption) (*GetRevenueAnalyticsForCampaignsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRevenueAnalyticsForCampaignsResponse)
	err := c.cc.Invoke(ctx, CheckoutAnalyticsService_GetRevenueAnalyticsForCampaigns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutAnalyticsServiceClient) CheckoutAnalyticsForCampaigns(ctx context.Context, in *CheckoutAnalyticsForCampaignsRequest, opts ...grpc.CallOption) (*CheckoutAnalyticsForCampaignsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckoutAnalyticsForCampaignsResponse)
	err := c.cc.Invoke(ctx, CheckoutAnalyticsService_CheckoutAnalyticsForCampaigns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutAnalyticsServiceClient) AverageRevenuePerContactAnalytics(ctx context.Context, in *AverageRevenuePerContactAnalyticsRequest, opts ...grpc.CallOption) (*AverageRevenuePerContactAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AverageRevenuePerContactAnalyticsResponse)
	err := c.cc.Invoke(ctx, CheckoutAnalyticsService_AverageRevenuePerContactAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutAnalyticsServiceClient) AverageRevenuePerNoOfMessagesAnalytics(ctx context.Context, in *AverageRevenuePerNoOfMessagesAnalyticsRequest, opts ...grpc.CallOption) (*AverageRevenuePerNoOfMessagesAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AverageRevenuePerNoOfMessagesAnalyticsResponse)
	err := c.cc.Invoke(ctx, CheckoutAnalyticsService_AverageRevenuePerNoOfMessagesAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckoutAnalyticsServiceServer is the server API for CheckoutAnalyticsService service.
// All implementations must embed UnimplementedCheckoutAnalyticsServiceServer
// for forward compatibility.
type CheckoutAnalyticsServiceServer interface {
	EntityContactAnalytics(context.Context, *EntityContactAnalyticsRequest) (*EntityContactAnalyticsResponse, error)
	EntityProductSalesAnalytics(context.Context, *EntityProductSalesAnalyticsRequest) (*EntityProductSalesAnalyticsResponse, error)
	CampaignCheckoutAnalytics(context.Context, *CampaignCheckoutAnalyticsRequest) (*CampaignCheckoutAnalyticsResponse, error)
	CampaignCheckoutTimeSeriesAnalytics(context.Context, *CampaignCheckoutTimeSeriesAnalyticsRequest) (*CampaignCheckoutTimeSeriesAnalyticsResponse, error)
	CampaignRevenueAnalytics(context.Context, *CampaignRevenueAnalyticsRequest) (*CampaignRevenueAnalyticsResponse, error)
	GetRevenueAnalyticsForCampaigns(context.Context, *GetRevenueAnalyticsForCampaignsRequest) (*GetRevenueAnalyticsForCampaignsResponse, error)
	CheckoutAnalyticsForCampaigns(context.Context, *CheckoutAnalyticsForCampaignsRequest) (*CheckoutAnalyticsForCampaignsResponse, error)
	AverageRevenuePerContactAnalytics(context.Context, *AverageRevenuePerContactAnalyticsRequest) (*AverageRevenuePerContactAnalyticsResponse, error)
	AverageRevenuePerNoOfMessagesAnalytics(context.Context, *AverageRevenuePerNoOfMessagesAnalyticsRequest) (*AverageRevenuePerNoOfMessagesAnalyticsResponse, error)
	mustEmbedUnimplementedCheckoutAnalyticsServiceServer()
}

// UnimplementedCheckoutAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCheckoutAnalyticsServiceServer struct{}

func (UnimplementedCheckoutAnalyticsServiceServer) EntityContactAnalytics(context.Context, *EntityContactAnalyticsRequest) (*EntityContactAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EntityContactAnalytics not implemented")
}
func (UnimplementedCheckoutAnalyticsServiceServer) EntityProductSalesAnalytics(context.Context, *EntityProductSalesAnalyticsRequest) (*EntityProductSalesAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EntityProductSalesAnalytics not implemented")
}
func (UnimplementedCheckoutAnalyticsServiceServer) CampaignCheckoutAnalytics(context.Context, *CampaignCheckoutAnalyticsRequest) (*CampaignCheckoutAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CampaignCheckoutAnalytics not implemented")
}
func (UnimplementedCheckoutAnalyticsServiceServer) CampaignCheckoutTimeSeriesAnalytics(context.Context, *CampaignCheckoutTimeSeriesAnalyticsRequest) (*CampaignCheckoutTimeSeriesAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CampaignCheckoutTimeSeriesAnalytics not implemented")
}
func (UnimplementedCheckoutAnalyticsServiceServer) CampaignRevenueAnalytics(context.Context, *CampaignRevenueAnalyticsRequest) (*CampaignRevenueAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CampaignRevenueAnalytics not implemented")
}
func (UnimplementedCheckoutAnalyticsServiceServer) GetRevenueAnalyticsForCampaigns(context.Context, *GetRevenueAnalyticsForCampaignsRequest) (*GetRevenueAnalyticsForCampaignsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRevenueAnalyticsForCampaigns not implemented")
}
func (UnimplementedCheckoutAnalyticsServiceServer) CheckoutAnalyticsForCampaigns(context.Context, *CheckoutAnalyticsForCampaignsRequest) (*CheckoutAnalyticsForCampaignsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckoutAnalyticsForCampaigns not implemented")
}
func (UnimplementedCheckoutAnalyticsServiceServer) AverageRevenuePerContactAnalytics(context.Context, *AverageRevenuePerContactAnalyticsRequest) (*AverageRevenuePerContactAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AverageRevenuePerContactAnalytics not implemented")
}
func (UnimplementedCheckoutAnalyticsServiceServer) AverageRevenuePerNoOfMessagesAnalytics(context.Context, *AverageRevenuePerNoOfMessagesAnalyticsRequest) (*AverageRevenuePerNoOfMessagesAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AverageRevenuePerNoOfMessagesAnalytics not implemented")
}
func (UnimplementedCheckoutAnalyticsServiceServer) mustEmbedUnimplementedCheckoutAnalyticsServiceServer() {
}
func (UnimplementedCheckoutAnalyticsServiceServer) testEmbeddedByValue() {}

// UnsafeCheckoutAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckoutAnalyticsServiceServer will
// result in compilation errors.
type UnsafeCheckoutAnalyticsServiceServer interface {
	mustEmbedUnimplementedCheckoutAnalyticsServiceServer()
}

func RegisterCheckoutAnalyticsServiceServer(s grpc.ServiceRegistrar, srv CheckoutAnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedCheckoutAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CheckoutAnalyticsService_ServiceDesc, srv)
}

func _CheckoutAnalyticsService_EntityContactAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityContactAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutAnalyticsServiceServer).EntityContactAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutAnalyticsService_EntityContactAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutAnalyticsServiceServer).EntityContactAnalytics(ctx, req.(*EntityContactAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutAnalyticsService_EntityProductSalesAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityProductSalesAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutAnalyticsServiceServer).EntityProductSalesAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutAnalyticsService_EntityProductSalesAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutAnalyticsServiceServer).EntityProductSalesAnalytics(ctx, req.(*EntityProductSalesAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutAnalyticsService_CampaignCheckoutAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CampaignCheckoutAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutAnalyticsServiceServer).CampaignCheckoutAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutAnalyticsService_CampaignCheckoutAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutAnalyticsServiceServer).CampaignCheckoutAnalytics(ctx, req.(*CampaignCheckoutAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutAnalyticsService_CampaignCheckoutTimeSeriesAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CampaignCheckoutTimeSeriesAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutAnalyticsServiceServer).CampaignCheckoutTimeSeriesAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutAnalyticsService_CampaignCheckoutTimeSeriesAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutAnalyticsServiceServer).CampaignCheckoutTimeSeriesAnalytics(ctx, req.(*CampaignCheckoutTimeSeriesAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutAnalyticsService_CampaignRevenueAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CampaignRevenueAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutAnalyticsServiceServer).CampaignRevenueAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutAnalyticsService_CampaignRevenueAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutAnalyticsServiceServer).CampaignRevenueAnalytics(ctx, req.(*CampaignRevenueAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutAnalyticsService_GetRevenueAnalyticsForCampaigns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRevenueAnalyticsForCampaignsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutAnalyticsServiceServer).GetRevenueAnalyticsForCampaigns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutAnalyticsService_GetRevenueAnalyticsForCampaigns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutAnalyticsServiceServer).GetRevenueAnalyticsForCampaigns(ctx, req.(*GetRevenueAnalyticsForCampaignsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutAnalyticsService_CheckoutAnalyticsForCampaigns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckoutAnalyticsForCampaignsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutAnalyticsServiceServer).CheckoutAnalyticsForCampaigns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutAnalyticsService_CheckoutAnalyticsForCampaigns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutAnalyticsServiceServer).CheckoutAnalyticsForCampaigns(ctx, req.(*CheckoutAnalyticsForCampaignsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutAnalyticsService_AverageRevenuePerContactAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AverageRevenuePerContactAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutAnalyticsServiceServer).AverageRevenuePerContactAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutAnalyticsService_AverageRevenuePerContactAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutAnalyticsServiceServer).AverageRevenuePerContactAnalytics(ctx, req.(*AverageRevenuePerContactAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutAnalyticsService_AverageRevenuePerNoOfMessagesAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AverageRevenuePerNoOfMessagesAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutAnalyticsServiceServer).AverageRevenuePerNoOfMessagesAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutAnalyticsService_AverageRevenuePerNoOfMessagesAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutAnalyticsServiceServer).AverageRevenuePerNoOfMessagesAnalytics(ctx, req.(*AverageRevenuePerNoOfMessagesAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckoutAnalyticsService_ServiceDesc is the grpc.ServiceDesc for CheckoutAnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckoutAnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud9.checkout.CheckoutAnalyticsService",
	HandlerType: (*CheckoutAnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EntityContactAnalytics",
			Handler:    _CheckoutAnalyticsService_EntityContactAnalytics_Handler,
		},
		{
			MethodName: "EntityProductSalesAnalytics",
			Handler:    _CheckoutAnalyticsService_EntityProductSalesAnalytics_Handler,
		},
		{
			MethodName: "CampaignCheckoutAnalytics",
			Handler:    _CheckoutAnalyticsService_CampaignCheckoutAnalytics_Handler,
		},
		{
			MethodName: "CampaignCheckoutTimeSeriesAnalytics",
			Handler:    _CheckoutAnalyticsService_CampaignCheckoutTimeSeriesAnalytics_Handler,
		},
		{
			MethodName: "CampaignRevenueAnalytics",
			Handler:    _CheckoutAnalyticsService_CampaignRevenueAnalytics_Handler,
		},
		{
			MethodName: "GetRevenueAnalyticsForCampaigns",
			Handler:    _CheckoutAnalyticsService_GetRevenueAnalyticsForCampaigns_Handler,
		},
		{
			MethodName: "CheckoutAnalyticsForCampaigns",
			Handler:    _CheckoutAnalyticsService_CheckoutAnalyticsForCampaigns_Handler,
		},
		{
			MethodName: "AverageRevenuePerContactAnalytics",
			Handler:    _CheckoutAnalyticsService_AverageRevenuePerContactAnalytics_Handler,
		},
		{
			MethodName: "AverageRevenuePerNoOfMessagesAnalytics",
			Handler:    _CheckoutAnalyticsService_AverageRevenuePerNoOfMessagesAnalytics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "checkout/checkout.proto",
}
