// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: contacts/contacts.proto

package contactspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContactService_CreateContact_FullMethodName         = "/cloud9.contacts.ContactService/CreateContact"
	ContactService_CreateOrUpdateContact_FullMethodName = "/cloud9.contacts.ContactService/CreateOrUpdateContact"
	ContactService_GetOrCreateContact_FullMethodName    = "/cloud9.contacts.ContactService/GetOrCreateContact"
	ContactService_GetContact_FullMethodName            = "/cloud9.contacts.ContactService/GetContact"
	ContactService_ListContacts_FullMethodName          = "/cloud9.contacts.ContactService/ListContacts"
	ContactService_UpdateContact_FullMethodName         = "/cloud9.contacts.ContactService/UpdateContact"
	ContactService_DeleteContact_FullMethodName         = "/cloud9.contacts.ContactService/DeleteContact"
	ContactService_CountContacts_FullMethodName         = "/cloud9.contacts.ContactService/CountContacts"
	ContactService_UpdateContactConsent_FullMethodName  = "/cloud9.contacts.ContactService/UpdateContactConsent"
	ContactService_CreateContactAddress_FullMethodName  = "/cloud9.contacts.ContactService/CreateContactAddress"
	ContactService_ListContactAddresses_FullMethodName  = "/cloud9.contacts.ContactService/ListContactAddresses"
	ContactService_ImportContacts_FullMethodName        = "/cloud9.contacts.ContactService/ImportContacts"
	ContactService_BulkUpsertContacts_FullMethodName    = "/cloud9.contacts.ContactService/BulkUpsertContacts"
	ContactService_UpdateWhatsAppFacts_FullMethodName   = "/cloud9.contacts.ContactService/UpdateWhatsAppFacts"
)

// ContactServiceClient is the client API for ContactService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ContactService provides contact operations.
type ContactServiceClient interface {
	CreateContact(ctx context.Context, in *CreateContactRequest, opts ...grpc.CallOption) (*ContactResponse, error)
	CreateOrUpdateContact(ctx context.Context, in *CreateOrUpdateContactRequest, opts ...grpc.CallOption) (*ContactResponse, error)
	GetOrCreateContact(ctx context.Context, in *GetOrCreateContactRequest, opts ...grpc.CallOption) (*ContactResponse, error)
	GetContact(ctx context.Context, in *GetContactRequest, opts ...grpc.CallOption) (*ContactResponse, error)
	ListContacts(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (*ListContactsResponse, error)
	UpdateContact(ctx context.Context, in *UpdateContactRequest, opts ...grpc.CallOption) (*ContactResponse, error)
	DeleteContact(ctx context.Context, in *DeleteContactRequest, opts ...grpc.CallOption) (*DeleteContactResponse, error)
	CountContacts(ctx context.Context, in *CountContactsRequest, opts ...grpc.CallOption) (*CountContactsResponse, error)
	UpdateContactConsent(ctx context.Context, in *UpdateContactConsentRequest, opts ...grpc.CallOption) (*UpdateContactConsentResponse, error)
	CreateContactAddress(ctx context.Context, in *CreateContactAddressRequest, opts ...grpc.CallOption) (*ContactAddressResponse, error)
	ListContactAddresses(ctx context.Context, in *ListContactAddressesRequest, opts ...grpc.CallOption) (*ListContactAddressesResponse, error)
	ImportContacts(ctx context.Context, in *ImportContactsRequest, opts ...grpc.CallOption) (*ImportContactsResponse, error)
	BulkUpsertContacts(ctx context.Context, in *BulkUpsertContactsRequest, opts ...grpc.CallOption) (*BulkUpsertContactsResponse, error)
	UpdateWhatsAppFacts(ctx context.Context, in *UpdateWhatsAppFactsRequest, opts ...grpc.CallOption) (*UpdateWhatsAppFactsResponse, error)
}

type contactServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContactServiceClient(cc grpc.ClientConnInterface) ContactServiceClient {
	return &contactServiceClient{cc}
}

func (c *contactServiceClient) CreateContact(ctx context.Context, in *CreateContactRequest, opts ...grpc.CallOption) (*ContactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContactResponse)
	err := c.cc.Invoke(ctx, ContactService_CreateContact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) CreateOrUpdateContact(ctx context.Context, in *CreateOrUpdateContactRequest, opts ...grpc.CallOption) (*ContactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContactResponse)
	err := c.cc.Invoke(ctx, ContactService_CreateOrUpdateContact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) GetOrCreateContact(ctx context.Context, in *GetOrCreateContactRequest, opts ...grpc.CallOption) (*ContactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContactResponse)
	err := c.cc.Invoke(ctx, ContactService_GetOrCreateContact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) GetContact(ctx context.Context, in *GetContactRequest, opts ...grpc.CallOption) (*ContactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContactResponse)
	err := c.cc.Invoke(ctx, ContactService_GetContact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) ListContacts(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (*ListContactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContactsResponse)
	err := c.cc.Invoke(ctx, ContactService_ListContacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) UpdateContact(ctx context.Context, in *UpdateContactRequest, opts ...grpc.CallOption) (*ContactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContactResponse)
	err := c.cc.Invoke(ctx, ContactService_UpdateContact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) DeleteContact(ctx context.Context, in *DeleteContactRequest, opts ...grpc.CallOption) (*DeleteContactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteContactResponse)
	err := c.cc.Invoke(ctx, ContactService_DeleteContact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) CountContacts(ctx context.Context, in *CountContactsRequest, opts ...grpc.CallOption) (*CountContactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountContactsResponse)
	err := c.cc.Invoke(ctx, ContactService_CountContacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) UpdateContactConsent(ctx context.Context, in *UpdateContactConsentRequest, opts ...grpc.CallOption) (*UpdateContactConsentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateContactConsentResponse)
	err := c.cc.Invoke(ctx, ContactService_UpdateContactConsent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) CreateContactAddress(ctx context.Context, in *CreateContactAddressRequest, opts ...grpc.CallOption) (*ContactAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContactAddressResponse)
	err := c.cc.Invoke(ctx, ContactService_CreateContactAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) ListContactAddresses(ctx context.Context, in *ListContactAddressesRequest, opts ...grpc.CallOption) (*ListContactAddressesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContactAddressesResponse)
	err := c.cc.Invoke(ctx, ContactService_ListContactAddresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) ImportContacts(ctx context.Context, in *ImportContactsRequest, opts ...grpc.CallOption) (*ImportContactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportContactsResponse)
	err := c.cc.Invoke(ctx, ContactService_ImportContacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) BulkUpsertContacts(ctx context.Context, in *BulkUpsertContactsRequest, opts ...grpc.CallOption) (*BulkUpsertContactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkUpsertContactsResponse)
	err := c.cc.Invoke(ctx, ContactService_BulkUpsertContacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) UpdateWhatsAppFacts(ctx context.Context, in *UpdateWhatsAppFactsRequest, opts ...grpc.CallOption) (*UpdateWhatsAppFactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWhatsAppFactsResponse)
	err := c.cc.Invoke(ctx, ContactService_UpdateWhatsAppFacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactServiceServer is the server API for ContactService service.
// All implementations must embed UnimplementedContactServiceServer
// for forward compatibility.
//
// ContactService provides contact operations.
type ContactServiceServer interface {
	CreateContact(context.Context, *CreateContactRequest) (*ContactResponse, error)
	CreateOrUpdateContact(context.Context, *CreateOrUpdateContactRequest) (*ContactResponse, error)
	GetOrCreateContact(context.Context, *GetOrCreateContactRequest) (*ContactResponse, error)
	GetContact(context.Context, *GetContactRequest) (*ContactResponse, error)
	ListContacts(context.Context, *ListContactsRequest) (*ListContactsResponse, error)
	UpdateContact(context.Context, *UpdateContactRequest) (*ContactResponse, error)
	DeleteContact(context.Context, *DeleteContactRequest) (*DeleteContactResponse, error)
	CountContacts(context.Context, *CountContactsRequest) (*CountContactsResponse, error)
	UpdateContactConsent(context.Context, *UpdateContactConsentRequest) (*UpdateContactConsentResponse, error)
	CreateContactAddress(context.Context, *CreateContactAddressRequest) (*ContactAddressResponse, error)
	ListContactAddresses(context.Context, *ListContactAddressesRequest) (*ListContactAddressesResponse, error)
	ImportContacts(context.Context, *ImportContactsRequest) (*ImportContactsResponse, error)
	BulkUpsertContacts(context.Context, *BulkUpsertContactsRequest) (*BulkUpsertContactsResponse, error)
	UpdateWhatsAppFacts(context.Context, *UpdateWhatsAppFactsRequest) (*UpdateWhatsAppFactsResponse, error)
	mustEmbedUnimplementedContactServiceServer()
}

// UnimplementedContactServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContactServiceServer struct{}

func (UnimplementedContactServiceServer) CreateContact(context.Context, *CreateContactRequest) (*ContactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateContact not implemented")
}
func (UnimplementedContactServiceServer) CreateOrUpdateContact(context.Context, *CreateOrUpdateContactRequest) (*ContactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrUpdateContact not implemented")
}
func (UnimplementedContactServiceServer) GetOrCreateContact(context.Context, *GetOrCreateContactRequest) (*ContactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrCreateContact not implemented")
}
func (UnimplementedContactServiceServer) GetContact(context.Context, *GetContactRequest) (*ContactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContact not implemented")
}
func (UnimplementedContactServiceServer) ListContacts(context.Context, *ListContactsRequest) (*ListContactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListContacts not implemented")
}
func (UnimplementedContactServiceServer) UpdateContact(context.Context, *UpdateContactRequest) (*ContactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateContact not implemented")
}
func (UnimplementedContactServiceServer) DeleteContact(context.Context, *DeleteContactRequest) (*DeleteContactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteContact not implemented")
}
func (UnimplementedContactServiceServer) CountContacts(context.Context, *CountContactsRequest) (*CountContactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountContacts not implemented")
}
func (UnimplementedContactServiceServer) UpdateContactConsent(context.Context, *UpdateContactConsentRequest) (*UpdateContactConsentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateContactConsent not implemented")
}
func (UnimplementedContactServiceServer) CreateContactAddress(context.Context, *CreateContactAddressRequest) (*ContactAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateContactAddress not implemented")
}
func (UnimplementedContactServiceServer) ListContactAddresses(context.Context, *ListContactAddressesRequest) (*ListContactAddressesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListContactAddresses not implemented")
}
func (UnimplementedContactServiceServer) ImportContacts(context.Context, *ImportContactsRequest) (*ImportContactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportContacts not implemented")
}
func (UnimplementedContactServiceServer) BulkUpsertContacts(context.Context, *BulkUpsertContactsRequest) (*BulkUpsertContactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BulkUpsertContacts not implemented")
}
func (UnimplementedContactServiceServer) UpdateWhatsAppFacts(context.Context, *UpdateWhatsAppFactsRequest) (*UpdateWhatsAppFactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWhatsAppFacts not implemented")
}
func (UnimplementedContactServiceServer) mustEmbedUnimplementedContactServiceServer() {}
func (UnimplementedContactServiceServer) testEmbeddedByValue()                        {}

// UnsafeContactServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContactServiceServer will
// result in compilation errors.
type UnsafeContactServiceServer interface {
	mustEmbedUnimplementedContactServiceServer()
}

func RegisterContactServiceServer(s grpc.ServiceRegistrar, srv ContactServiceServer) {
	// If the following call panics, it indicates UnimplementedContactServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContactService_ServiceDesc, srv)
}

func _ContactService_CreateContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).CreateContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_CreateContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).CreateContact(ctx, req.(*CreateContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_CreateOrUpdateContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).CreateOrUpdateContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_CreateOrUpdateContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).CreateOrUpdateContact(ctx, req.(*CreateOrUpdateContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_GetOrCreateContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrCreateContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).GetOrCreateContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_GetOrCreateContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).GetOrCreateContact(ctx, req.(*GetOrCreateContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_GetContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).GetContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_GetContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).GetContact(ctx, req.(*GetContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_ListContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).ListContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_ListContacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).ListContacts(ctx, req.(*ListContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_UpdateContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).UpdateContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_UpdateContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).UpdateContact(ctx, req.(*UpdateContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_DeleteContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).DeleteContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_DeleteContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).DeleteContact(ctx, req.(*DeleteContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_CountContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).CountContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_CountContacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).CountContacts(ctx, req.(*CountContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_UpdateContactConsent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContactConsentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).UpdateContactConsent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_UpdateContactConsent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).UpdateContactConsent(ctx, req.(*UpdateContactConsentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_CreateContactAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContactAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).CreateContactAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_CreateContactAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).CreateContactAddress(ctx, req.(*CreateContactAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_ListContactAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContactAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).ListContactAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_ListContactAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).ListContactAddresses(ctx, req.(*ListContactAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_ImportContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).ImportContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_ImportContacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).ImportContacts(ctx, req.(*ImportContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_BulkUpsertContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkUpsertContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).BulkUpsertContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_BulkUpsertContacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).BulkUpsertContacts(ctx, req.(*BulkUpsertContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_UpdateWhatsAppFacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWhatsAppFactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).UpdateWhatsAppFacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_UpdateWhatsAppFacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).UpdateWhatsAppFacts(ctx, req.(*UpdateWhatsAppFactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContactService_ServiceDesc is the grpc.ServiceDesc for ContactService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContactService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud9.contacts.ContactService",
	HandlerType: (*ContactServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContact",
			Handler:    _ContactService_CreateContact_Handler,
		},
		{
			MethodName: "CreateOrUpdateContact",
			Handler:    _ContactService_CreateOrUpdateContact_Handler,
		},
		{
			MethodName: "GetOrCreateContact",
			Handler:    _ContactService_GetOrCreateContact_Handler,
		},
		{
			MethodName: "GetContact",
			Handler:    _ContactService_GetContact_Handler,
		},
		{
			MethodName: "ListContacts",
			Handler:    _ContactService_ListContacts_Handler,
		},
		{
			MethodName: "UpdateContact",
			Handler:    _ContactService_UpdateContact_Handler,
		},
		{
			MethodName: "DeleteContact",
			Handler:    _ContactService_DeleteContact_Handler,
		},
		{
			MethodName: "CountContacts",
			Handler:    _ContactService_CountContacts_Handler,
		},
		{
			MethodName: "UpdateContactConsent",
			Handler:    _ContactService_UpdateContactConsent_Handler,
		},
		{
			MethodName: "CreateContactAddress",
			Handler:    _ContactService_CreateContactAddress_Handler,
		},
		{
			MethodName: "ListContactAddresses",
			Handler:    _ContactService_ListContactAddresses_Handler,
		},
		{
			MethodName: "ImportContacts",
			Handler:    _ContactService_ImportContacts_Handler,
		},
		{
			MethodName: "BulkUpsertContacts",
			Handler:    _ContactService_BulkUpsertContacts_Handler,
		},
		{
			MethodName: "UpdateWhatsAppFacts",
			Handler:    _ContactService_UpdateWhatsAppFacts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contacts/contacts.proto",
}

const (
	SegmentService_CreateSegment_FullMethodName             = "/cloud9.contacts.SegmentService/CreateSegment"
	SegmentService_CreateSegmentFromTemplate_FullMethodName = "/cloud9.contacts.SegmentService/CreateSegmentFromTemplate"
	SegmentService_GetSegment_FullMethodName                = "/cloud9.contacts.SegmentService/GetSegment"
	SegmentService_GetSegmentsByIds_FullMethodName          = "/cloud9.contacts.SegmentService/GetSegmentsByIds"
	SegmentService_ListSegments_FullMethodName              = "/cloud9.contacts.SegmentService/ListSegments"
	SegmentService_UpdateSegment_FullMethodName             = "/cloud9.contacts.SegmentService/UpdateSegment"
	SegmentService_DeleteSegment_FullMethodName             = "/cloud9.contacts.SegmentService/DeleteSegment"
	SegmentService_CountSegmentMembers_FullMethodName       = "/cloud9.contacts.SegmentService/CountSegmentMembers"
	SegmentService_AddSegmentMembers_FullMethodName         = "/cloud9.contacts.SegmentService/AddSegmentMembers"
	SegmentService_RemoveSegmentMember_FullMethodName       = "/cloud9.contacts.SegmentService/RemoveSegmentMember"
	SegmentService_ListSegmentMembers_FullMethodName        = "/cloud9.contacts.SegmentService/ListSegmentMembers"
	SegmentService_ResolveAudience_FullMethodName           = "/cloud9.contacts.SegmentService/ResolveAudience"
)

// SegmentServiceClient is the client API for SegmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SegmentService provides segment operations.
type SegmentServiceClient interface {
	CreateSegment(ctx context.Context, in *CreateSegmentRequest, opts ...grpc.CallOption) (*SegmentResponse, error)
	CreateSegmentFromTemplate(ctx context.Context, in *CreateSegmentFromTemplateRequest, opts ...grpc.CallOption) (*SegmentResponse, error)
	GetSegment(ctx context.Context, in *GetSegmentRequest, opts ...grpc.CallOption) (*SegmentResponse, error)
	GetSegmentsByIds(ctx context.Context, in *GetSegmentsByIdsRequest, opts ...grpc.CallOption) (*GetSegmentsByIdsResponse, error)
	ListSegments(ctx context.Context, in *ListSegmentsRequest, opts ...grpc.CallOption) (*ListSegmentsResponse, error)
	UpdateSegment(ctx context.Context, in *UpdateSegmentRequest, opts ...grpc.CallOption) (*SegmentResponse, error)
	DeleteSegment(ctx context.Context, in *DeleteSegmentRequest, opts ...grpc.CallOption) (*DeleteSegmentResponse, error)
	CountSegmentMembers(ctx context.Context, in *CountSegmentMembersRequest, opts ...grpc.CallOption) (*CountSegmentMembersResponse, error)
	AddSegmentMembers(ctx context.Context, in *AddSegmentMembersRequest, opts ...grpc.CallOption) (*AddSegmentMembersResponse, error)
	RemoveSegmentMember(ctx context.Context, in *RemoveSegmentMemberRequest, opts ...grpc.CallOption) (*RemoveSegmentMemberResponse, error)
	ListSegmentMembers(ctx context.Context, in *ListSegmentMembersRequest, opts ...grpc.CallOption) (*ListSegmentMembersResponse, error)
	ResolveAudience(ctx context.Context, in *ResolveAudienceRequest, opts ...grpc.CallOption) (*ResolveAudienceResponse, error)
}

type segmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSegmentServiceClient(cc grpc.ClientConnInterface) SegmentServiceClient {
	return &segmentServiceClient{cc}
}

func (c *segmentServiceClient) CreateSegment(ctx context.Context, in *CreateSegmentRequest, opts ...grpc.CallOption) (*SegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SegmentResponse)
	err := c.cc.Invoke(ctx, SegmentService_CreateSegment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) CreateSegmentFromTemplate(ctx context.Context, in *CreateSegmentFromTemplateRequest, opts ...grpc.CallOption) (*SegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SegmentResponse)
	err := c.cc.Invoke(ctx, SegmentService_CreateSegmentFromTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) GetSegment(ctx context.Context, in *GetSegmentRequest, opts ...grpc.CallOption) (*SegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SegmentResponse)
	err := c.cc.Invoke(ctx, SegmentService_GetSegment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) GetSegmentsByIds(ctx context.Context, in *GetSegmentsByIdsRequest, opts ...grpc.CallOption) (*GetSegmentsByIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSegmentsByIdsResponse)
	err := c.cc.Invoke(ctx, SegmentService_GetSegmentsByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) ListSegments(ctx context.Context, in *ListSegmentsRequest, opts ...grpc.CallOption) (*ListSegmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSegmentsResponse)
	err := c.cc.Invoke(ctx, SegmentService_ListSegments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) UpdateSegment(ctx context.Context, in *UpdateSegmentRequest, opts ...grpc.CallOption) (*SegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SegmentResponse)
	err := c.cc.Invoke(ctx, SegmentService_UpdateSegment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) DeleteSegment(ctx context.Context, in *DeleteSegmentRequest, opts ...grpc.CallOption) (*DeleteSegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSegmentResponse)
	err := c.cc.Invoke(ctx, SegmentService_DeleteSegment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) CountSegmentMembers(ctx context.Context, in *CountSegmentMembersRequest, opts ...grpc.CallOption) (*CountSegmentMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountSegmentMembersResponse)
	err := c.cc.Invoke(ctx, SegmentService_CountSegmentMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) AddSegmentMembers(ctx context.Context, in *AddSegmentMembersRequest, opts ...grpc.CallOption) (*AddSegmentMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddSegmentMembersResponse)
	err := c.cc.Invoke(ctx, SegmentService_AddSegmentMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) RemoveSegmentMember(ctx context.Context, in *RemoveSegmentMemberRequest, opts ...grpc.CallOption) (*RemoveSegmentMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveSegmentMemberResponse)
	err := c.cc.Invoke(ctx, SegmentService_RemoveSegmentMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) ListSegmentMembers(ctx context.Context, in *ListSegmentMembersRequest, opts ...grpc.CallOption) (*ListSegmentMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSegmentMembersResponse)
	err := c.cc.Invoke(ctx, SegmentService_ListSegmentMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) ResolveAudience(ctx context.Context, in *ResolveAudienceRequest, opts ...grpc.CallOption) (*ResolveAudienceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveAudienceResponse)
	err := c.cc.Invoke(ctx, SegmentService_ResolveAudience_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SegmentServiceServer is the server API for SegmentService service.
// All implementations must embed UnimplementedSegmentServiceServer
// for forward compatibility.
//
// SegmentService provides segment operations.
type SegmentServiceServer interface {
	CreateSegment(context.Context, *CreateSegmentRequest) (*SegmentResponse, error)
	CreateSegmentFromTemplate(context.Context, *CreateSegmentFromTemplateRequest) (*SegmentResponse, error)
	GetSegment(context.Context, *GetSegmentRequest) (*SegmentResponse, error)
	GetSegmentsByIds(context.Context, *GetSegmentsByIdsRequest) (*GetSegmentsByIdsResponse, error)
	ListSegments(context.Context, *ListSegmentsRequest) (*ListSegmentsResponse, error)
	UpdateSegment(context.Context, *UpdateSegmentRequest) (*SegmentResponse, error)
	DeleteSegment(context.Context, *DeleteSegmentRequest) (*DeleteSegmentResponse, error)
	CountSegmentMembers(context.Context, *CountSegmentMembersRequest) (*CountSegmentMembersResponse, error)
	AddSegmentMembers(context.Context, *AddSegmentMembersRequest) (*AddSegmentMembersResponse, error)
	RemoveSegmentMember(context.Context, *RemoveSegmentMemberRequest) (*RemoveSegmentMemberResponse, error)
	ListSegmentMembers(context.Context, *ListSegmentMembersRequest) (*ListSegmentMembersResponse, error)
	ResolveAudience(context.Context, *ResolveAudienceRequest) (*ResolveAudienceResponse, error)
	mustEmbedUnimplementedSegmentServiceServer()
}

// UnimplementedSegmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSegmentServiceServer struct{}

func (UnimplementedSegmentServiceServer) CreateSegment(context.Context, *CreateSegmentRequest) (*SegmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSegment not implemented")
}
func (UnimplementedSegmentServiceServer) CreateSegmentFromTemplate(context.Context, *CreateSegmentFromTemplateRequest) (*SegmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSegmentFromTemplate not implemented")
}
func (UnimplementedSegmentServiceServer) GetSegment(context.Context, *GetSegmentRequest) (*SegmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSegment not implemented")
}
func (UnimplementedSegmentServiceServer) GetSegmentsByIds(context.Context, *GetSegmentsByIdsRequest) (*GetSegmentsByIdsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSegmentsByIds not implemented")
}
func (UnimplementedSegmentServiceServer) ListSegments(context.Context, *ListSegmentsRequest) (*ListSegmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSegments not implemented")
}
func (UnimplementedSegmentServiceServer) UpdateSegment(context.Context, *UpdateSegmentRequest) (*SegmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSegment not implemented")
}
func (UnimplementedSegmentServiceServer) DeleteSegment(context.Context, *DeleteSegmentRequest) (*DeleteSegmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSegment not implemented")
}
func (UnimplementedSegmentServiceServer) CountSegmentMembers(context.Context, *CountSegmentMembersRequest) (*CountSegmentMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountSegmentMembers not implemented")
}
func (UnimplementedSegmentServiceServer) AddSegmentMembers(context.Context, *AddSegmentMembersRequest) (*AddSegmentMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSegmentMembers not implemented")
}
func (UnimplementedSegmentServiceServer) RemoveSegmentMember(context.Context, *RemoveSegmentMemberRequest) (*RemoveSegmentMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveSegmentMember not implemented")
}
func (UnimplementedSegmentServiceServer) ListSegmentMembers(context.Context, *ListSegmentMembersRequest) (*ListSegmentMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSegmentMembers not implemented")
}
func (UnimplementedSegmentServiceServer) ResolveAudience(context.Context, *ResolveAudienceRequest) (*ResolveAudienceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveAudience not implemented")
}
func (UnimplementedSegmentServiceServer) mustEmbedUnimplementedSegmentServiceServer() {}
func (UnimplementedSegmentServiceServer) testEmbeddedByValue()                        {}

// UnsafeSegmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SegmentServiceServer will
// result in compilation errors.
type UnsafeSegmentServiceServer interface {
	mustEmbedUnimplementedSegmentServiceServer()
}

func RegisterSegmentServiceServer(s grpc.ServiceRegistrar, srv SegmentServiceServer) {
	// If the following call panics, it indicates UnimplementedSegmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SegmentService_ServiceDesc, srv)
}

func _SegmentService_CreateSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).CreateSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_CreateSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).CreateSegment(ctx, req.(*CreateSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_CreateSegmentFromTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSegmentFromTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).CreateSegmentFromTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_CreateSegmentFromTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).CreateSegmentFromTemplate(ctx, req.(*CreateSegmentFromTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_GetSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).GetSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_GetSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).GetSegment(ctx, req.(*GetSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_GetSegmentsByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSegmentsByIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).GetSegmentsByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_GetSegmentsByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).GetSegmentsByIds(ctx, req.(*GetSegmentsByIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_ListSegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSegmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).ListSegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_ListSegments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).ListSegments(ctx, req.(*ListSegmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_UpdateSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).UpdateSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_UpdateSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).UpdateSegment(ctx, req.(*UpdateSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_DeleteSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).DeleteSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_DeleteSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).DeleteSegment(ctx, req.(*DeleteSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_CountSegmentMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountSegmentMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).CountSegmentMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_CountSegmentMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).CountSegmentMembers(ctx, req.(*CountSegmentMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_AddSegmentMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSegmentMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).AddSegmentMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_AddSegmentMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).AddSegmentMembers(ctx, req.(*AddSegmentMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_RemoveSegmentMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSegmentMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).RemoveSegmentMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_RemoveSegmentMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).RemoveSegmentMember(ctx, req.(*RemoveSegmentMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_ListSegmentMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSegmentMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).ListSegmentMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_ListSegmentMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).ListSegmentMembers(ctx, req.(*ListSegmentMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_ResolveAudience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveAudienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).ResolveAudience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentService_ResolveAudience_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).ResolveAudience(ctx, req.(*ResolveAudienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SegmentService_ServiceDesc is the grpc.ServiceDesc for SegmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SegmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud9.contacts.SegmentService",
	HandlerType: (*SegmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSegment",
			Handler:    _SegmentService_CreateSegment_Handler,
		},
		{
			MethodName: "CreateSegmentFromTemplate",
			Handler:    _SegmentService_CreateSegmentFromTemplate_Handler,
		},
		{
			MethodName: "GetSegment",
			Handler:    _SegmentService_GetSegment_Handler,
		},
		{
			MethodName: "GetSegmentsByIds",
			Handler:    _SegmentService_GetSegmentsByIds_Handler,
		},
		{
			MethodName: "ListSegments",
			Handler:    _SegmentService_ListSegments_Handler,
		},
		{
			MethodName: "UpdateSegment",
			Handler:    _SegmentService_UpdateSegment_Handler,
		},
		{
			MethodName: "DeleteSegment",
			Handler:    _SegmentService_DeleteSegment_Handler,
		},
		{
			MethodName: "CountSegmentMembers",
			Handler:    _SegmentService_CountSegmentMembers_Handler,
		},
		{
			MethodName: "AddSegmentMembers",
			Handler:    _SegmentService_AddSegmentMembers_Handler,
		},
		{
			MethodName: "RemoveSegmentMember",
			Handler:    _SegmentService_RemoveSegmentMember_Handler,
		},
		{
			MethodName: "ListSegmentMembers",
			Handler:    _SegmentService_ListSegmentMembers_Handler,
		},
		{
			MethodName: "ResolveAudience",
			Handler:    _SegmentService_ResolveAudience_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contacts/contacts.proto",
}

const (
	TagService_CreateTag_FullMethodName       = "/cloud9.contacts.TagService/CreateTag"
	TagService_GetTag_FullMethodName          = "/cloud9.contacts.TagService/GetTag"
	TagService_ListTags_FullMethodName        = "/cloud9.contacts.TagService/ListTags"
	TagService_UpdateTag_FullMethodName       = "/cloud9.contacts.TagService/UpdateTag"
	TagService_DeleteTag_FullMethodName       = "/cloud9.contacts.TagService/DeleteTag"
	TagService_AddTagMembers_FullMethodName   = "/cloud9.contacts.TagService/AddTagMembers"
	TagService_RemoveTagMember_FullMethodName = "/cloud9.contacts.TagService/RemoveTagMember"
)

// TagServiceClient is the client API for TagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TagService provides tag operations.
type TagServiceClient interface {
	CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*TagResponse, error)
	GetTag(ctx context.Context, in *GetTagRequest, opts ...grpc.CallOption) (*TagResponse, error)
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error)
	UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*TagResponse, error)
	DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error)
	AddTagMembers(ctx context.Context, in *AddTagMembersRequest, opts ...grpc.CallOption) (*AddTagMembersResponse, error)
	RemoveTagMember(ctx context.Context, in *RemoveTagMemberRequest, opts ...grpc.CallOption) (*RemoveTagMemberResponse, error)
}

type tagServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTagServiceClient(cc grpc.ClientConnInterface) TagServiceClient {
	return &tagServiceClient{cc}
}

func (c *tagServiceClient) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*TagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagResponse)
	err := c.cc.Invoke(ctx, TagService_CreateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagServiceClient) GetTag(ctx context.Context, in *GetTagRequest, opts ...grpc.CallOption) (*TagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagResponse)
	err := c.cc.Invoke(ctx, TagService_GetTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagServiceClient) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagsResponse)
	err := c.cc.Invoke(ctx, TagService_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagServiceClient) UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*TagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagResponse)
	err := c.cc.Invoke(ctx, TagService_UpdateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagServiceClient) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTagResponse)
	err := c.cc.Invoke(ctx, TagService_DeleteTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagServiceClient) AddTagMembers(ctx context.Context, in *AddTagMembersRequest, opts ...grpc.CallOption) (*AddTagMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTagMembersResponse)
	err := c.cc.Invoke(ctx, TagService_AddTagMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagServiceClient) RemoveTagMember(ctx context.Context, in *RemoveTagMemberRequest, opts ...grpc.CallOption) (*RemoveTagMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveTagMemberResponse)
	err := c.cc.Invoke(ctx, TagService_RemoveTagMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TagServiceServer is the server API for TagService service.
// All implementations must embed UnimplementedTagServiceServer
// for forward compatibility.
//
// TagService provides tag operations.
type TagServiceServer interface {
	CreateTag(context.Context, *CreateTagRequest) (*TagResponse, error)
	GetTag(context.Context, *GetTagRequest) (*TagResponse, error)
	ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
	UpdateTag(context.Context, *UpdateTagRequest) (*TagResponse, error)
	DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error)
	AddTagMembers(context.Context, *AddTagMembersRequest) (*AddTagMembersResponse, error)
	RemoveTagMember(context.Context, *RemoveTagMemberRequest) (*RemoveTagMemberResponse, error)
	mustEmbedUnimplementedTagServiceServer()
}

// UnimplementedTagServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTagServiceServer struct{}

func (UnimplementedTagServiceServer) CreateTag(context.Context, *CreateTagRequest) (*TagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTag not implemented")
}
func (UnimplementedTagServiceServer) GetTag(context.Context, *GetTagRequest) (*TagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTag not implemented")
}
func (UnimplementedTagServiceServer) ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTags not implemented")
}
func (UnimplementedTagServiceServer) UpdateTag(context.Context, *UpdateTagRequest) (*TagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTag not implemented")
}
func (UnimplementedTagServiceServer) DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTag not implemented")
}
func (UnimplementedTagServiceServer) AddTagMembers(context.Context, *AddTagMembersRequest) (*AddTagMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTagMembers not implemented")
}
func (UnimplementedTagServiceServer) RemoveTagMember(context.Context, *RemoveTagMemberRequest) (*RemoveTagMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTagMember not implemented")
}
func (UnimplementedTagServiceServer) mustEmbedUnimplementedTagServiceServer() {}
func (UnimplementedTagServiceServer) testEmbeddedByValue()                    {}

// UnsafeTagServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TagServiceServer will
// result in compilation errors.
type UnsafeTagServiceServer interface {
	mustEmbedUnimplementedTagServiceServer()
}

func RegisterTagServiceServer(s grpc.ServiceRegistrar, srv TagServiceServer) {
	// If the following call panics, it indicates UnimplementedTagServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TagService_ServiceDesc, srv)
}

func _TagService_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServiceServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TagService_CreateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServiceServer).CreateTag(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TagService_GetTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServiceServer).GetTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TagService_GetTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServiceServer).GetTag(ctx, req.(*GetTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TagService_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServiceServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TagService_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServiceServer).ListTags(ctx, req.(*ListTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TagService_UpdateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServiceServer).UpdateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TagService_UpdateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServiceServer).UpdateTag(ctx, req.(*UpdateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TagService_DeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServiceServer).DeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TagService_DeleteTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServiceServer).DeleteTag(ctx, req.(*DeleteTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TagService_AddTagMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTagMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServiceServer).AddTagMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TagService_AddTagMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServiceServer).AddTagMembers(ctx, req.(*AddTagMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TagService_RemoveTagMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTagMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServiceServer).RemoveTagMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TagService_RemoveTagMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServiceServer).RemoveTagMember(ctx, req.(*RemoveTagMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TagService_ServiceDesc is the grpc.ServiceDesc for TagService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TagService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud9.contacts.TagService",
	HandlerType: (*TagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTag",
			Handler:    _TagService_CreateTag_Handler,
		},
		{
			MethodName: "GetTag",
			Handler:    _TagService_GetTag_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _TagService_ListTags_Handler,
		},
		{
			MethodName: "UpdateTag",
			Handler:    _TagService_UpdateTag_Handler,
		},
		{
			MethodName: "DeleteTag",
			Handler:    _TagService_DeleteTag_Handler,
		},
		{
			MethodName: "AddTagMembers",
			Handler:    _TagService_AddTagMembers_Handler,
		},
		{
			MethodName: "RemoveTagMember",
			Handler:    _TagService_RemoveTagMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contacts/contacts.proto",
}
